### PR TITLE
More sifter improvements

### PR DESCRIPTION
**Pull request by Mekle001**
# Changes proposed in this pull request:
- Add icons of possible drops defined in secondaryoutputs when primaryoutputs is empty in display of recipes
- Add support for more context in loot tables, but don't enable it yet.  (This allows loot tables to use mob loot tables)

The additional context is intended to be used in the nether resource gatherer, and possibly even a rudimentary expedition hut, but it's not used by normal crafting. I will likely add a property to crafters that can be used to enable it in the future, or it will be called directly similar to the way the sifter calls today. 

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
:shipit:

**Comment by Raycoms** [comment]
conflicts @Mekle001

**Review by someaddons — APPROVED** [review]

**Review by LDTTeam-Buildsystem — APPROVED** [review]

**Comment by LDTTeam-Buildsystem** [comment]
Yeah you need to fix the conflicts @Mekle

**Comment by LDTTeam-Buildsystem** [comment]
Okey now it looks good.

**Review by LDTTeam-Buildsystem — APPROVED** [review]

**Comment by ravenbuilder934** [comment]
Don't think you meant to close this :P

**Pull request merged**
