### PR TITLE
Add option to enable/disable zombie villager converting to visitor

### PR DESCRIPTION
**Pull request by cylian914**
# Changes proposed in this pull request
- Add server config  to disable zombie villager -> visitor 

## Testing
- [X] Yes I tested this before submitting it.
- [X] I also did a multiplayer test.

Review please

### CODE REVIEW

**Review by Thodor12 — CHANGES_REQUESTED** [review]
Thanks for your contribution. I'm pretty sure the requested changes are fine to have, however one remark. Config options require 2 translation strings which are written in the config file, please add the following 2 lines in the `manual_en_us.json`:
```json
  "minecolonies.config.convertzombievillagertovisitor": "<config name>",
  "minecolonies.config.convertzombievillagertovisitor.comment": "<config description>",
```
  
 (Also you have to sign the CLA)

**Comment by cylian914** [comment]
forgot to add it, should be fixed now

**Comment by Thodor12** [comment]
You should have it fully lowercase, it has to match the text you put in the config option, not the name of the variable.
I'm not sure if translation strings are case insensitive, probably not.

**Comment by cylian914** [comment]
it should be the final fix

**Review by Thodor12 — APPROVED** [review]

**Review by marchermans — APPROVED** [review]

**Pull request merged**
