### PR TITLE
Updates recipes to utilize forge chests

### LINKED ISSUE #4937: Other Chests for Postbox and Stash
Im using: minecolonies 0.11.918.-Beta-universal

When I try to Craft Stash or a Postbox JEI say I Need a regular Vanilla Chest. I can´t use Chests from Quark.

Can you please add the Tag: Accepts any: forge:chest like the in the Warehous-Recipe, so we can use all types of chests and not only minecraft:chest.

LG Jonas

### PR DESCRIPTION
**Pull request by PowerSchill**
Allows any Forge chest to be used for recipes that use minecraft chests.

Signed-off-by: Mark E. Schill <Mark.Schill@cmschill.net>

Closes #4937
Closes #
Closes #

# Changes proposed in this pull request:
-
-
-

Review please

### CODE REVIEW

**Comment by ToMe25** [comment]
This should use "tag": instead of "item": in the beginning, this way it works only sometimes(or never, not sure)

**Comment by ToMe25** [comment]
This way he searches for an item named "forge:chests", not a tag.

**Comment by Raycoms** [comment]
Good catch, totally passed by me

**Comment by Raycoms** [comment]
Added to my PR

**Comment by ToMe25** [comment]
oh, then i will remove the branch i made for this.

**Pull request merged**
