### PR TITLE
Feature/#618 in game config

### LINKED ISSUE #618: in-game config
It'd be awesome to be able to change some things in the config for the mod from in-game. Things like if builders have infinite resources or not, or adjusting the build/dig speed for citizens.

### PR DESCRIPTION
**Pull request by carif**
Closes #618 

# Changes proposed in this pull request:
- Implemented a full functional in-game GUI for the config.

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
Seems nice. Can't find anything wrong.
Can you just run our formatter once over the files?

**Comment by carif** [comment]
How can I do this?

**Comment by Raycoms** [comment]
Let me see. We have that formatter file for intellij/eclipse somewhere.

**Comment by Raycoms** [comment]
Ah you should have that installed with the repository. Just format the code with the selected formatter that should do it.

**Comment by marvin-bitterlich** [comment]
The formatter is in the documentation folder, just import it into intelliJ

**Comment by carif** [comment]
Only problem, I'm using eclipse.

**Comment by Raycoms** [comment]
I will check the pr out on my pc then and run it over it as soon as it is ready.
Can you commit it to our repo so the checks can analyze the pr?

**Comment by carif** [comment]
How?

**Comment by Raycoms** [comment]
Create a branch in our repo and push it to that branch and create a pr from
that branch.

2017-03-24 17:56 GMT-03:00 MinecraftPlaye <notifications@github.com>:

**Comment by carif** [comment]
Well, it seems like I can't create a branch here.

**Comment by Raycoms** [comment]
Ahh, You weren't invited to the team yet. I invited you now.

2017-03-24 17:59 GMT-03:00 MinecraftPlaye <notifications@github.com>:

**Comment by carif** [comment]
Well, could be a little problem. Just created now the branch (from the current develop branch) and put my changes in it, but Github Desktop isn't showing me that anything changed nor that I could upload anything.

**Comment by Raycoms** [comment]
you did merge your changes to the branch you created?
You tried cherrypicking as well?
you pushed your changes afterwards?

2017-03-24 20:16 GMT-03:00 MinecraftPlaye <notifications@github.com>:

**Comment by carif** [comment]
Whats cherrypicking? And nope... just created the branch and trying to upload the changes... thought Github Desktop seems to have it's problems with recognizing the changes...

**Comment by Raycoms** [comment]
try it with gitKraken that's what most of us use.

2017-03-24 20:23 GMT-03:00 MinecraftPlaye <notifications@github.com>:

**Comment by carif** [comment]
Hm... well... it seems to be that something from git broke... Or in some cached data from git itself is an error... no clue...

**Comment by Raycoms** [comment]
Nothing arrived here on my side. Only that you created a branch. Did you
tried restarting your pc?

2017-03-24 20:31 GMT-03:00 MinecraftPlaye <notifications@github.com>:

**Comment by carif** [comment]
Yep, tried to restart the PC. no change. Just got that far that git at least knows about new added files, but not about changed files.

**Comment by Raycoms** [comment]
and you tried gitkraken?

2017-03-24 20:45 GMT-03:00 MinecraftPlaye <notifications@github.com>:

**Comment by carif** [comment]
Got it now working after deleting some files from github desktop and git and stuff like that. ^^
All changed files are now uploaded...
Thought it might not build as I'm using the code from the current develop branch as a basis and this branch seems not to build after github.

**Comment by Raycoms** [comment]
can you change your pr then, so that your branch in our repo points to it?
2017-03-24 21:08 GMT-03:00 MinecraftPlaye <notifications@github.com>:

**Comment by carif** [comment]
As it is not possible to change the branch other than the base branch, I've created a new pr. ;)

**Comment by Raycoms** [comment]
Yeah that's what I wanted to say =D

2017-03-24 21:38 GMT-03:00 MinecraftPlaye <notifications@github.com>:

**Comment by Raycoms** [comment]
then we can close this here

**Comment by Raycoms** [comment]
Fixed the building as well, you can merge now develop again into yours

2017-03-24 21:39 GMT-03:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Pull request closed without merging**
