### PR TITLE
Remove warnings

### PR DESCRIPTION
**Pull request by xavierh**
# Changes proposed in this pull request:
- Remove most warning 
- Still one type left about getStateForPlacement being deprecated, not sure what the right thing to do for this one

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
You tested this well?

**Comment by xavierh** [comment]
Tested in Single player only

**Comment by Raycoms** [comment]
Guard armor and everything still works quite well? 
(Everywhere you made changes)

**Comment by xavierh** [comment]
Are you referring to 88f580f17554699f301ac2b8d4635a36f5ed7936 specifically ?

I will try the guard's armor tonight

**Comment by Raycoms** [comment]
Can you send us your email so we can add you to our developers chat. That
would make things easier.

2017-01-19 11:55 GMT-02:00 xavierh <notifications@github.com>:

**Comment by xavierh** [comment]
Where can I send it without being public ?

**Comment by Raycoms** [comment]
send it to "H3lay" on the forums.

2017-01-19 12:14 GMT-02:00 xavierh <notifications@github.com>:

**Comment by xavierh** [comment]
Done

**Comment by Raycoms** [comment]
Great we'll send you an invitation in the next hours.

2017-01-19 12:46 GMT-02:00 xavierh <notifications@github.com>:

> Done
>

**Comment by xavierh** [comment]
Ok, I tested this one with guard as follow:
- Creative mode
- Single player
- Guard at the lowest level
- I put leather armors (boot, pants, tunis and cap ) in his inventory (not the hut one) and he is wearing them.
- If I put the armor in the tower chest, he doesn't take them (don't know if it is intended)

Is that what you wanted to check ?

**Comment by Raycoms** [comment]
It wears it and it gets damaged etc?

2017-01-19 17:03 GMT-02:00 xavierh <notifications@github.com>:

**Comment by xavierh** [comment]
yes and yes

**Comment by Raycoms** [comment]
:shipit: for me

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/469/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by marvin-bitterlich** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/469/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Pull request merged**
