### PR TITLE
Speed configuration for placing and mining blocks

### LINKED ISSUE #451: [1.11.2] Builder Working speeds
### Minecolonies version

latest Commit on version 1.11.2 54fb0c710118074f92401f3881decf869d62cc2d

### Expected behavior

- Builder Works at (roughly) the Players speed or Maybe half as fast to let the workers level do the Progress 
- Miner and forester may be a lot slower, progressing greatly by levels

### Actual behaviour

- When Digging/Clearing The Builder is roughly 10 Times slower than the player. While this is fine for All workers for the builder it is terribly annoying because you cann not watch for example when he clears out the area. I changed my behavior to clear all trees and dig out the area manually due to that

- When Building the builder is roughly 100-1000 times(!) faster than normal players. This is a result of blocks beeing placed instantly and no repositioning is needed - probably a _bigger_ pause (0.5~2 seconds) between placement of Blocks ould be great

### Steps to reproduce the problem

1. Build a building and whatch the builder do his Job

### PR DESCRIPTION
**Pull request by xavierh**
Closes #451 

# Changes proposed in this pull request:
- Allow to change the mining speed from the configuration file (blockMiningDelayModifier default to 1000)
- Allow to add a delay between placing block for the builder from the config file (to give a more natural feel) (builderBuildBlockDelay default to 0 i.e. no delay)

Review please

### CODE REVIEW

**Comment by forReason** [comment]
two questions:

blockMiningDelayModifier <1000 = slower; >1000=faster?
builderBuildBlockDelay default to 0 <- in seconds I guess? or ms?

**Comment by xavierh** [comment]
blockMiningDelayModifier: the lower is the faster, I believe this is the number of minecraft tick before the block is considered mined. other variables are taken into account 
builderBuildBlockDelay in minecraft tick

The default value is does not change minecolonies current behaviour

**Comment by marvin-bitterlich** [comment]
LGTM @Raycoms 
Thanks a lot for the pr @xavierh 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/455/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by marvin-bitterlich** [comment]
@xavierh can you move this comment out into a different pr? then we can review it separately

**Comment by xavierh** [comment]
Hi Kostronor,

I did not mean to do that. Not familiar with git, and github. How do I do that ?

I thought I was going to do another pr from my last push

**Comment by marvin-bitterlich** [comment]
Hey @xavierh,
create a new branch and commit your changes there. Then (after extracting the changes) reset this branch to the previous commit and force push.

If you use a graphical user interface like gitkraken then this should be fairly easy :)

**Comment by marvin-bitterlich** [comment]
@xavierh now you redo you first commit and we shoudl be okay ;D

**Comment by xavierh** [comment]
Family priority right now.

The right way to do it is to do a branch do the change on it, commit, push
and push request. Rince and repeat for each different patches?

Is that correct?


On 13 Jan 2017 21:31, "Marvin Hofmann" <notifications@github.com> wrote:

@xavierh <https://github.com/xavierh> now you redo you first commit and we
shoudl be okay ;D

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Minecolonies/minecolonies/pull/455#issuecomment-272553152>,
or mute the thread

**Comment by marvin-bitterlich** [comment]
@xavierh Currently this branch had two commits, commit 1 and 2. You reverted 2 👍 but you then reverted 1 👎 because now the pr is effectively empty.

Best would be to have this pr contain commit 1 and open up a new one for commit 2

And no worries :) Take your time

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/455/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by xavierh** [comment]
Ok, You should have only the first commit now.

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/455/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by xavierh** [comment]
I am a bit confused.

For a second pr, I need to created a new local branch with minecolonies/version/1.11.

Do some change on it, then push to a new remote branch and then a pr between minecolonies/version/1.11 and xavierh/mynewbranch. Is that correct ?

If so, how do I do the new local branch? if I do:
git push -u origin version/1.11, I will get the version with my previous pr.

How do I get the minecolonies version?

(Using git over ssh)

**Comment by Raycoms** [comment]
I always just right click the commit and click "create new branch here" and
then push that new branch =)

2017-01-14 9:39 GMT-02:00 xavierh <notifications@github.com>:

**Comment by marvin-bitterlich** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/455/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Pull request merged**
