### PR TITLE
Allow use bonemeal to crops

### PR DESCRIPTION
**Pull request by gisellevonbingen**
Closes #
Closes #
Closes #

# Changes proposed in this pull request:
- MinecoloniesCropBlock implements BonemealableBlock
-
-

[ x ] Yes I tested this before submitting it.
[ ] I also did a multiplayer test.

Review please

### CODE REVIEW

**Comment by Thodor12** [comment]
If you want to make this extend BonemealableBlock you have to remove the `use` method. Compost is already implemented with a useOn that applies bonemeal similar to how vanilla bonemeal works, it checks for BonemealableBlock instances.
You can combine your 2 PR's into one

**Comment by gisellevonbingen** [comment]
I used translator for my poor english.
In Minecraft vanilla, the convention for bonemeal handling is to implement BonemealableBlock.
Also, I have never seen an example of being implemented it directly via the useOn method.

And 2 PR's are logically different features.
So, there are should be separated.

**Comment by someaddons** [comment]
it is intentionally not bonemealable due to other mods using it in very inflationary ways

**Comment by Thodor12** [comment]
> I used translator for my poor english. In Minecraft vanilla, the convention for bonemeal handling is to implement BonemealableBlock. Also, I have never seen an example of being implemented it directly via the useOn method.
> 
> And 2 PR's are logically different features. So, there are should be separated.

I meant the second PR would be automatically fixed if you already did this change alone

**Comment by Shadizar** [comment]
> it is intentionally not bonemealable due to other mods using it in very inflationary ways

It'd seem to be unharmful no? i.e., if folks want to play that way it doesn't really harm anything right?
It does seem this is the sort of thing that pushes folks more into mixins when there's closed-off options?

**Comment by gisellevonbingen** [comment]
> > I used translator for my poor english. In Minecraft vanilla, the convention for bonemeal handling is to implement BonemealableBlock. Also, I have never seen an example of being implemented it directly via the useOn method.
> > And 2 PR's are logically different features. So, there are should be separated.
> 
> I meant the second PR would be automatically fixed if you already did this change alone

2 PR is on each other issue.
and second PR is on another branch where from based on master.

**Comment by Thodor12** [comment]
> it is intentionally not bonemealable due to other mods using it in very inflationary ways

On one hand I get where you're coming from, on the other I feel like this is not really useful.
Remember that this interaction is only for the player growing the crops, colonists do not reuse this logic and can only cope with compost anyway. So at best you want to limit the player in this sense, who already cannot grow these crops.

I think it is fair to allow this to grow since:
A: Make use of vanilla logic
B: People can create bulk compost anyway to mass grow for the colonists

**Comment by someaddons** [comment]
> > it is intentionally not bonemealable due to other mods using it in very inflationary ways
> 
> On one hand I get where you're coming from, on the other I feel like this is not really useful. Remember that this interaction is only for the player growing the crops, colonists do not reuse this logic and can only cope with compost anyway. So at best you want to limit the player in this sense, who already cannot grow these crops.
> 
> I think it is fair to allow this to grow since: A: Make use of vanilla logic B: People can create bulk compost anyway to mass grow for the colonists

please dont use code review to discuss design, do that in discord. Also this is ray choice

**Comment by Shadizar** [comment]
> > > it is intentionally not bonemealable due to other mods using it in very inflationary ways
> > 
> > 
> > On one hand I get where you're coming from, on the other I feel like this is not really useful. Remember that this interaction is only for the player growing the crops, colonists do not reuse this logic and can only cope with compost anyway. So at best you want to limit the player in this sense, who already cannot grow these crops.
> > I think it is fair to allow this to grow since: A: Make use of vanilla logic B: People can create bulk compost anyway to mass grow for the colonists
> 
> please dont use code review to discuss design, do that in discord. Also this is ray choice

Gotcha...I guess I was confused because you commented on design discussion topic which seemed to open that door

**Pull request closed without merging**
