### PR TITLE
[omnibus draft] Codebase cleanup - Valentine present for Ray :)

### PR DESCRIPTION
**Pull request by Nightenom**
# Instead, for reviewing check omnibus PRs at https://github.com/Nightenom/minecolonies/pulls

_sorta sorry for long pr description_ 🤷

# Changes proposed in this pull request:
- you really dont want to click _Files changed_ tab in github
- if some part is questionable for you I'm free to take it out
- please, pay attention to things in "Changes" as they might be _problematic_
- now follows list of all commits categorized by merge-safety from mergeable to need check
- added todos in: 78a0ea4, 9ca325e, [forge tier registry](https://github.com/ldtteam/minecolonies/blob/27f26cf95ab7b5358f707394b0aa7f23fef2a457/src/api/java/com/minecolonies/api/util/ItemStackUtils.java#L281) and noted also below: 28d5a3b, def630c

## Things that are completely safe to merge (no code changes)
- [x] 0f85b38 - Replace javax.annotations with jetbrain equivalent - notnull, nullable etc.
- [ ] 431ba38 - Remove unused imports (also in few others, this was first huge pass)
- [x] b283483 - Suppress unused variables in model classes - over 1200 warnings :D
- [ ] 8f12cf7 - Suppress unchecked casts - half is to mute RS type casting, rest is spread among rest of code base
- [ ] a547045 - Suppress deprecated overrides (Block methods)

## Things that are more likely safe to merge
- [x] 7031833 - Rawtypes - mix of changes around generics to remove rawtype warnings
- [x] 5330607 - change to static access - discussed with Ray
- [ ] 9ca325e - last commit of this cleanup containing unclassifiable changes

## Code cleanups (better to check if make sense)
- [x] 4ddfec6 - Remove old ID references from items - old registry key class member
- [x] 6d7b683 - Remove resLoc ID references from recipe/guard/interaction types - same reason as above
- [x] 45404a4 - Remove dead registry methods - ...
- [x] 4f911f3 - Slim down guard type - remove few unused variables
- [x] 9b77739 - Remove unused private code - uncomment code that was marked as unreferenced (no public members removed)
- [x] aba25d8 - Remove faulty unused public code - discussed with Ray
- [x] af841c0 - Remove useless override - if I'm not blind this method did nothing but super call
- [x] b80dfc3 - Remove redundant superinterfaces - might lower typing readability
- [x] f729cc4 - Remove varargs method in IRequest - unused methods producing _unsafe varargs_ warning
- [ ] b43a49b - Some random code extractions - mix of small changes to reduce count of _unclosed resource_ warnings (blame mojang)
- [ ] 1c85b8c - almost last commit containing two code relocations and one code streamlining
- [x] 1c74110 - IAIState typing - add @SafeVarargs to registerTargets for AI classes, fixes rawtyping for callers of registerTargets
- [x] 6daa9d8 and def630c - building#getModules typing - redirect getModules to typed stream, might expose that method to public? (to reduce creation of intermediate lists)

## Deprecation fixes (code cleanups) - check almost required
- [x] 8101db7 - getFoodProperties - using stack sensitive variant over item one, also adds `hasSufficientNutrition` to ItemStorage
- [ ] c5118c2 - rest of deprecation fixes - add isEntireAreaLoaded(world, centerPos, blockRange) method to replace vanilla like and with same safe checks as rest of WorldUtils methods

## Changes (just another code cleanup category), any of these are potential candidates for reversal if no likey
- [x] d99c789 - Make blockhut normal BlockItem - removed ItemBlockHut class which was just extended class (api change)
- [x] 9c16f1d - Make ThreatTable not generic - it was made generic just for constructor typing
- [x] f8cf1a7 + a99405f - Remove generic from PathResult job type - change `job` from Callable<Path> to AbstractPathJob to strengthen typing
- [x] a5d3b3c - Fill incomplete switches - add branches for enum switches, added exceptions are impossible? to reach but may catch missed updates in future
- [x] 28d5a3b - getItemFromBlock redirect? - **needs testing and discusion**
- [ ] 05f19eb - instanceof pattern matching - huge commit to use pattern matching for nearly every `instanceof`, few times this change appears in other commits
- [x] 403ff80 - generics for Class#forName - typing in RS
- [x] 93ac384 - Change array to list in TimeBasedHappinessModifier - varargs redundancy

## Additions
- [x] 9964e76 - method for cast filtering Stream - even suggested use from jdk javadoc
- [x] noted above in 8101db7 - adds `hasSufficientNutrition` to ItemStorage
- [ ] noted above in c5118c2  - adds `isEntireAreaLoaded` to WorldUtils

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
Please cut this into several smaller PRs. Definitely import cleanup into a completely separate one

**Comment by Nightenom** [comment]
> Please cut this into several smaller PRs. Definitely import cleanup into a completely separate one

will take out import as requested, but just before merging

**Comment by Nightenom** [comment]
Added [gist with checklist](https://gist.githubusercontent.com/Nightenom/664806be317e0a97625a9ff4cd0ebedc/raw/5c3c4f072a2702cdae831f906ace1bbe3acef285/cleanup_pr.md) for making reviewing a bit easier - you can track progress of what you have reviewed, just copy that and comment with it

**Comment by marchermans** [comment]
Split this into seperate PRs.
This won't be merged in its current state.
Way to many commits, with way to many changes which are all unrelated to each other!

**Comment by Nightenom** [comment]
well, ngl, i expected you to see at least one of two messages to review through my fork <https://github.com/Nightenom/minecolonies/pulls>
and they are all related - they are cleanup :D

**Pull request closed without merging**
