### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Starshak3r**
Removed unwanted "sheep spawn egg" from the Level 5 NBT for the "Birch" Stylepack 
Note! This is NOT the Medeival Birch pack.

This is in response to Lady_Dria on Discord, and other possible users not being able to upgrade the Baker from level 4 to level 5 due to this requested item

Closes #
Closes #
Closes #

# Changes proposed in this pull request:
- Fixed Builder Requesting a Sheep Spawn Egg, no other changes made to NBT
-
-

Review please

### CODE REVIEW

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 47 issues
* ![MAJOR][MAJOR] 47 major

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [blocks#](https://github.com/ldtteam/minecolonies/blob/d0f841f586dba5846f81544ad36492383f0620a8/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/ldtteam/minecolonies/blob/d0f841f586dba5846f81544ad36492383f0620a8/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [render#](https://github.com/ldtteam/minecolonies/blob/d0f841f586dba5846f81544ad36492383f0620a8/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [permissions#](https://github.com/ldtteam/minecolonies/blob/d0f841f586dba5846f81544ad36492383f0620a8/src/main/java/com/minecolonies/coremod/colony/permissions#): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [requestable#](https://github.com/ldtteam/minecolonies/blob/d0f841f586dba5846f81544ad36492383f0620a8/src/main/java/com/minecolonies/coremod/colony/requestable#): Add a 'package-info.java' file to document the 'requestable' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [data#](https://github.com/ldtteam/minecolonies/blob/d0f841f586dba5846f81544ad36492383f0620a8/src/main/java/com/minecolonies/coremod/colony/requestsystem/data#): Add a 'package-info.java' file to document the 'data' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [init#](https://github.com/ldtteam/minecolonies/blob/d0f841f586dba5846f81544ad36492383f0620a8/src/main/java/com/minecolonies/coremod/colony/requestsystem/init#): Add a 'package-info.java' file to document the 'init' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [locations#](https://github.com/ldtteam/minecolonies/blob/d0f841f586dba5846f81544ad36492383f0620a8/src/main/java/com/minecolonies/coremod/colony/requestsystem/locations#): Add a 'package-info.java' file to document the 'locations' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [management#](https://github.com/ldtteam/minecolonies/blob/d0f841f586dba5846f81544ad36492383f0620a8/src/main/java/com/minecolonies/coremod/colony/requestsystem/management#): Add a 'package-info.java' file to document the 'management' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [handlers#](https://github.com/ldtteam/minecolonies/blob/d0f841f586dba5846f81544ad36492383f0620a8/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers#): Add a 'package-info.java' file to document the 'handlers' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Review by Asherslab — DISMISSED** [review]
Schematic file is in the wrong directory =D

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 47 issues
* ![MAJOR][MAJOR] 47 major

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [blocks#](https://github.com/ldtteam/minecolonies/blob/9a9aaaefee0a0c9f45365772db55eb1f5c751f4c/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/ldtteam/minecolonies/blob/9a9aaaefee0a0c9f45365772db55eb1f5c751f4c/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [render#](https://github.com/ldtteam/minecolonies/blob/9a9aaaefee0a0c9f45365772db55eb1f5c751f4c/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [permissions#](https://github.com/ldtteam/minecolonies/blob/9a9aaaefee0a0c9f45365772db55eb1f5c751f4c/src/main/java/com/minecolonies/coremod/colony/permissions#): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [requestable#](https://github.com/ldtteam/minecolonies/blob/9a9aaaefee0a0c9f45365772db55eb1f5c751f4c/src/main/java/com/minecolonies/coremod/colony/requestable#): Add a 'package-info.java' file to document the 'requestable' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [data#](https://github.com/ldtteam/minecolonies/blob/9a9aaaefee0a0c9f45365772db55eb1f5c751f4c/src/main/java/com/minecolonies/coremod/colony/requestsystem/data#): Add a 'package-info.java' file to document the 'data' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [init#](https://github.com/ldtteam/minecolonies/blob/9a9aaaefee0a0c9f45365772db55eb1f5c751f4c/src/main/java/com/minecolonies/coremod/colony/requestsystem/init#): Add a 'package-info.java' file to document the 'init' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [locations#](https://github.com/ldtteam/minecolonies/blob/9a9aaaefee0a0c9f45365772db55eb1f5c751f4c/src/main/java/com/minecolonies/coremod/colony/requestsystem/locations#): Add a 'package-info.java' file to document the 'locations' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [management#](https://github.com/ldtteam/minecolonies/blob/9a9aaaefee0a0c9f45365772db55eb1f5c751f4c/src/main/java/com/minecolonies/coremod/colony/requestsystem/management#): Add a 'package-info.java' file to document the 'management' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [handlers#](https://github.com/ldtteam/minecolonies/blob/9a9aaaefee0a0c9f45365772db55eb1f5c751f4c/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers#): Add a 'package-info.java' file to document the 'handlers' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Review by Starshak3r — COMMENTED** [review]
Added file to the correct directory

**Pull request closed without merging**
