### PR TITLE
fixed placing of CTape in void world

### LINKED ISSUE #595: Construction tape in a void world hangs the game
Version 0.6 Solid (0.6.2849)

On a skyblock map, if the construction tape is allowed in settings and the tape would be above the void, the game hangs indefinitely. Turning off construction tape in the settings fixes the issue.

### PR DESCRIPTION
**Pull request by nojo121**
Closes #595 

Review please

### CODE REVIEW

**Comment by marvin-bitterlich** [comment]
Will this place the tape on y=0 or completely stop placing tape for such events?

**Comment by nojo121** [comment]
@Kostronor It'll place the tape at the y coordinates of the hut block

**Comment by marvin-bitterlich** [comment]
So they will float in the air and likely fall down immediately? Or will they stay in the air?

**Comment by nojo121** [comment]
They stay in the air

**Comment by marvin-bitterlich** [comment]
LGTM!

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/597/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/597/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Pull request merged**
