### PR TITLE
Fix upgrade button label for town hall

### PR DESCRIPTION
**Pull request by xavierh**
# Changes proposed in this pull request:
- show when the town hall is upgradeable
using com.minecolonies.coremod.gui.workerHuts.upgrade

Review please

### CODE REVIEW

**Comment by marvin-bitterlich** [comment]
For this one it's fine but please use branches from the repo, not from your fork 😉

**Comment by xavierh** [comment]
Sorry about that.

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/543/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by cltnschlosser** [comment]
I think this should be changed in the window class instead of the xml

**Comment by Raycoms** [comment]
The building still has "build" after the hut is placed or is it "upgrade" from the beginning.
If #2, we have to adjust this. We will have to set from the buildingView the "upgrade" after building is level 1.
That should be quite analogous to the other buildings.

**Comment by xavierh** [comment]
Upgrade building is the default and I didn't 2 translation texts was needed.

**Comment by cltnschlosser** [comment]
Okay, so this should be reverted and more logic should be added to the window class

**Comment by xavierh** [comment]
@Kostronor is it better like this, or do I do something wrong still?
@cltnschlosser I kept the new string in the xml but added the logic

**Comment by Raycoms** [comment]
Please change the string in the xml back and then we're good to go.
(The default version should be in the xml)

**Comment by xavierh** [comment]
@Raycoms, I will but I widen the pr scope. I should update it today

**Comment by marvin-bitterlich** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/543/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Pull request merged**
