### PR TITLE
Added datapack for indian names for citizens

### PR DESCRIPTION
**Pull request by jjackofall**
Closes #
Closes #
Closes #

# Changes proposed in this pull request:
- Added data pack for citizen names of Indian names
-
-

Review please

### CODE REVIEW

**Comment by Thodor12** [comment]
I'm not sure what you've done or if you copied something, but can you take a look at the "Md", "Mh", etc names.
These appear multiple times and (excuse me if I'm wrong) don't sound like names.

**Comment by jjackofall** [comment]
> I'm not sure what you've done or if you copied something, but can you take a look at the "Md", "Mh", etc names. These appear multiple times and (excuse me if I'm wrong) don't sound like names.

**Comment by jjackofall** [comment]
@Thodor12 Md. stands for Muhammad or Mohammed, which generally people use in India, but I think I should remove it.

**Comment by Thodor12** [comment]
Makes sense, although it did not include a dot behind it, it just said "Md" instead of "Md.", hence my confusion.
You are free to add those names in, either short or full name, as long as there's no duplicate ones.

**Comment by jjackofall** [comment]
@Thodor12 Can you please approve it

**Comment by Thodor12** [comment]
My approval won't matter, you will have to wait until others approve it.

**Review by someaddons — APPROVED** [review]

**Pull request merged**
