### PR TITLE
Dynamic trees re-compat

### PR DESCRIPTION
**Pull request by uecasm**
Closes [discord request](https://discord.com/channels/139070364159311872/1141796121958678639/1195780723186089984)
Closes [discord request](https://discord.com/channels/139070364159311872/240841248750043137/1257470648687530084)

# Changes proposed in this pull request:
- Enable Dynamic Trees compatibility for 1.20

[x] Yes I tested this before submitting it.
[ ] I also did a multiplayer test.

Review please (do not backport)

~Might want to avoid merging until DynamicTreesTeam/DynamicTrees#835 is fixed; it didn't crash on me when the forester was felling the tree, but then nobody was standing in the way...~

### CODE REVIEW

**Comment by uecasm** [comment]
Switching to draft due to maven issues.

**Review by marchermans — DISMISSED** [review]

**Comment by uecasm** [comment]
It lives again!

**Review by Raycoms — APPROVED** [review]

**Review by Thodor12 — APPROVED** [review]

**Comment by supermassimo** [comment]
Adding to this, the latest beta of DT now includes a "falling_tree_damage_immune" entity type tag. If the colonist entity is added to this tag they will not be dealt damage by falling trees

**Comment by Talyda** [comment]
Is this ready to go BTW?
We daily get people asking, or having problems because it isn't in!

**Pull request merged**
