### PR TITLE
Fix Warnings

### LINKED ISSUE #1095: Build error java
### Minecolonies version

version 0.8

### Expected behavior

./gradlew build
...
>BUILD SUCCESSFUL

### Actual behaviour

i have error on **"./gradlew build"** and
When start server minecraft , mod isnt launch

### Steps to reproduce the problem

**1/** ./gradlew build
```

This mapping 'snapshot_20161209' was designed for MC 1.11! Use at your own peril.
Cannot run the CurseUpload sequence. No API-Key or release type has been provided.
Found AccessTransformer: minecolonies_at.cfg
:deobfCompileDummyTask
:deobfProvidedDummyTask
:sourceApiJava UP-TO-DATE
:compileApiJava
Note: /home/game/minecraft/minecolonies/build/sources/api/java/com/minecolonies/api/colony/requestsystem/factory/IFactoryController.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:processApiResources UP-TO-DATE
:apiClasses
:apiJar UP-TO-DATE
:sourceBlockOutJava UP-TO-DATE
:compileBlockOutJava UP-TO-DATE
:processBlockOutResources UP-TO-DATE
:blockOutClasses UP-TO-DATE
:blockOutJar UP-TO-DATE
:sourceMainJava UP-TO-DATE
:sourceStructuresJava UP-TO-DATE
:compileStructuresJava UP-TO-DATE
:processStructuresResources UP-TO-DATE
:structuresClasses UP-TO-DATE
:compileJava
**/home/game/minecraft/minecolonies/build/sources/main/java/com/minecolonies/coremod/entity/EntityCitizen.java:861: warning: [unchecked] unchecked cast
            return (T) new InvWrapper(inventory);
                       ^
  required: T
  found:    InvWrapper
  where T is a type-variable:
    T extends Object declared in method <T>getCapability(Capability<T>,EnumFacing)
/home/game/minecraft/minecolonies/build/sources/main/java/com/minecolonies/coremod/inventory/api/AbstractCombinedItemHandler.java:77: warning: [rawtypes] found raw type: INBTSerializable
                final INBTSerializable serializable = (INBTSerializable) handlerModifiable;
                      ^
  missing type arguments for generic class INBTSerializable<T>
  where T is a type-variable:
    T extends NBTBase declared in interface INBTSerializable
/home/game/minecraft/minecolonies/build/sources/main/java/com/minecolonies/coremod/inventory/api/AbstractCombinedItemHandler.java:109: warning: [rawtypes] found raw type: INBTSerializable
                    final INBTSerializable serializable = (INBTSerializable) modifiable;
                          ^
  missing type arguments for generic class INBTSerializable<T>
  where T is a type-variable:
    T extends NBTBase declared in interface INBTSerializable
/home/game/minecraft/minecolonies/build/sources/main/java/com/minecolonies/coremod/inventory/api/AbstractCombinedItemHandler.java:110: warning: [unchecked] unchecked call to deserializeNBT(T) as a member of the raw type INBTSerializable
                    serializable.deserializeNBT(handlerCompound);
                                               ^
  where T is a type-variable:
    T extends NBTBase declared in interface INBTSerializable
4 warnings**
:processResources UP-TO-DATE
:classes
:deobfJar UP-TO-DATE
:structuresJar UP-TO-DATE
:jar
:sourceTestJava UP-TO-DATE
:compileTestJava
:processTestResources UP-TO-DATE
:testClasses
:test
:extractMcpData SKIPPED
:extractMcpMappings SKIPPED
:getVersionJson
:extractUserdev UP-TO-DATE
:genSrgs SKIPPED
:reobfJar
:extractRangemapReplacedMain
/home/game/minecraft/minecolonies/build/sources/main/java
:retromapReplacedMain UP-TO-DATE
:sourceJar UP-TO-DATE
:assemble
:check
:signJar SKIPPED
:build

BUILD SUCCESSFUL

```

_PS : you need to update your README.md_

### PR DESCRIPTION
**Pull request by marvin-bitterlich**
Closes #1095

### CODE REVIEW

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 52 issues
* ![MAJOR][MAJOR] 21 major
* ![MINOR][MINOR] 28 minor
* ![INFO][INFO] 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/9f60aea06beb1c5bae74572ff8a0032f533cb46e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.292 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L69](https://github.com/Minecolonies/minecolonies/blob/9f60aea06beb1c5bae74572ff8a0032f533cb46e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L69): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 57 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L69](https://github.com/Minecolonies/minecolonies/blob/9f60aea06beb1c5bae74572ff8a0032f533cb46e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L69): class "EntityCitizen" has 94 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L350](https://github.com/Minecolonies/minecolonies/blob/9f60aea06beb1c5bae74572ff8a0032f533cb46e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L350): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L352](https://github.com/Minecolonies/minecolonies/blob/9f60aea06beb1c5bae74572ff8a0032f533cb46e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L352): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/9f60aea06beb1c5bae74572ff8a0032f533cb46e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/9f60aea06beb1c5bae74572ff8a0032f533cb46e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L356](https://github.com/Minecolonies/minecolonies/blob/9f60aea06beb1c5bae74572ff8a0032f533cb46e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L356): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L356](https://github.com/Minecolonies/minecolonies/blob/9f60aea06beb1c5bae74572ff8a0032f533cb46e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L356): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L357](https://github.com/Minecolonies/minecolonies/blob/9f60aea06beb1c5bae74572ff8a0032f533cb46e/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L357): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 52 issues
* ![MAJOR][MAJOR] 21 major
* ![MINOR][MINOR] 28 minor
* ![INFO][INFO] 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/b0c17294d0a54ef73d88ae4233eedfb7bc1216ff/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.292 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L69](https://github.com/Minecolonies/minecolonies/blob/b0c17294d0a54ef73d88ae4233eedfb7bc1216ff/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L69): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 57 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L69](https://github.com/Minecolonies/minecolonies/blob/b0c17294d0a54ef73d88ae4233eedfb7bc1216ff/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L69): class "EntityCitizen" has 94 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L350](https://github.com/Minecolonies/minecolonies/blob/b0c17294d0a54ef73d88ae4233eedfb7bc1216ff/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L350): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L352](https://github.com/Minecolonies/minecolonies/blob/b0c17294d0a54ef73d88ae4233eedfb7bc1216ff/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L352): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/b0c17294d0a54ef73d88ae4233eedfb7bc1216ff/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/b0c17294d0a54ef73d88ae4233eedfb7bc1216ff/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L356](https://github.com/Minecolonies/minecolonies/blob/b0c17294d0a54ef73d88ae4233eedfb7bc1216ff/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L356): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L356](https://github.com/Minecolonies/minecolonies/blob/b0c17294d0a54ef73d88ae4233eedfb7bc1216ff/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L356): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L357](https://github.com/Minecolonies/minecolonies/blob/b0c17294d0a54ef73d88ae4233eedfb7bc1216ff/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L357): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1097/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Review by cltnschlosser — APPROVED** [review]
I think if we used generics better, we wouldn't need all these suppressions, but I'll approve.

**Pull request merged**
