### PR TITLE
Fix #3860

### LINKED ISSUE #3860: Config comments
1.14 branch is missing config comments
copying them from field javadocs should be fine

### PR DESCRIPTION
**Pull request by Nightenom**
Closes #3860

Review please

### CODE REVIEW

**Comment by Nightenom** [comment]
Can someone tell me what is that gradle error (in build log) about?

**Comment by Nightenom** [comment]
There are some `build.gradle` changes, just to make sure I haven't touched anything build system breaking.

**Review by marchermans — DISMISSED** [review]

**Comment by Nightenom** [comment]
@OrionDevelopment The build system is failing if I add `org.gradle.jvmargs=-Xmx<insert any value here, tried 4 up to 8>G` to gradle.properties

**Comment by marchermans** [comment]
@Nightenom add a settings.gradle file exactly like this one: https://github.com/ldtteam/Structurize/blob/version/1.14/settings.gradle

**Pull request merged**
