### PR TITLE
Update issue template for more consistent issues

### PR DESCRIPTION
**Pull request by PoroUsedSnax**
# Changes proposed in this pull request:
- This will update the issue template with comments describing what we want to see in their bug reports, hopefully making issues more consistent and easier to work with on our end. People can remove or leave the comments in without creating problems for the issue once posted.

Review please

### CODE REVIEW

**Review by Raycoms — COMMENTED** [review]
In the last field the grammar seems strange. Also add: Videos, images and logs if possible

**Comment by PoroUsedSnax** [comment]
Updated, hopefully the section I changed was the part you were talking about, and is a bit better now as a result

**Review by LDTTeam-Buildsystem — DISMISSED** [review]
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  |   0   |  0  |  0  |  0   |
| Errors |   0   |  0  |  0  |  0   |
##### More Information:

**Review by LDTTeam-Buildsystem — DISMISSED** [review]
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  |   0   |  0  |  0  |  0   |
| Errors |   0   |  0  |  0  |  0   |
##### More Information:

**Review by LDTTeam-Buildsystem — APPROVED** [review]
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  |   0   |  0  |  0  |  0   |
| Errors |   0   |  0  |  0  |  0   |
##### More Information:

**Review by marchermans — APPROVED** [review]

**Pull request merged**
