### PR TITLE
Held items now Look better 

### PR DESCRIPTION
**Pull request by Asherslab**
# Changes proposed in this pull request:
- Same as 1.11 version

Review please

### CODE REVIEW

**Comment by xavierh** [comment]
Worth title ever ! Well done, new achievement unlocked :D

Asher: Whoops, i didn't even notice the title, i thought it'd be my branch one not my commit one. lol

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 26 issues
* ![MINOR][MINOR] 26 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/4beb3482634f32ec8ffe2dd6bb61431d36c1ee37/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/4beb3482634f32ec8ffe2dd6bb61431d36c1ee37/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/4beb3482634f32ec8ffe2dd6bb61431d36c1ee37/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/4beb3482634f32ec8ffe2dd6bb61431d36c1ee37/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/4beb3482634f32ec8ffe2dd6bb61431d36c1ee37/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions](https://github.com/Minecolonies/minecolonies/blob/4beb3482634f32ec8ffe2dd6bb61431d36c1ee37/src/main/java/com/minecolonies/coremod/colony/permissions): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [creativetab](https://github.com/Minecolonies/minecolonies/blob/4beb3482634f32ec8ffe2dd6bb61431d36c1ee37/src/main/java/com/minecolonies/coremod/creativetab): Add a 'package-info.java' file to document the 'creativetab' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [entity](https://github.com/Minecolonies/minecolonies/blob/4beb3482634f32ec8ffe2dd6bb61431d36c1ee37/src/main/java/com/minecolonies/coremod/entity): Add a 'package-info.java' file to document the 'entity' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [baker](https://github.com/Minecolonies/minecolonies/blob/4beb3482634f32ec8ffe2dd6bb61431d36c1ee37/src/main/java/com/minecolonies/coremod/entity/ai/citizen/baker): Add a 'package-info.java' file to document the 'baker' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [farmer](https://github.com/Minecolonies/minecolonies/blob/4beb3482634f32ec8ffe2dd6bb61431d36c1ee37/src/main/java/com/minecolonies/coremod/entity/ai/citizen/farmer): Add a 'package-info.java' file to document the 'farmer' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Asherslab** [comment]
Blargh! i can't change it from in progress to Ready, lol (not sure why, probably internet troubles) can someone do it for me please?

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1210/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Review by xavierh — APPROVED** [review]

**Pull request merged**
