### PR TITLE
Avoid nearby colony lookup on each frame

### PR DESCRIPTION
**Pull request by someaddons**
Closes #
Closes #
Closes #

# Changes proposed in this pull request:
- Avoid nearby colony lookup on each frame

[x ] Yes I tested this before submitting it.
[ ] I also did a multiplayer test.

Review please

### CODE REVIEW

**Review by Raycoms — APPROVED** [review]

**Comment by uecasm** [comment]
Wouldn't it make more sense to cache this based on the player crossing chunk boundaries?  There's already some other stuff in here that does that, and the nearby colony is unlikely to change without the player moving around.

**Comment by someaddons** [comment]
The other stuff you're thinking on is serverside, clientside just has one player and data is more volatile due to sync timing. So performance wise there is little benefit to more caching and it'd have a higher risk of problems

**Comment by Nightenom** [comment]
Just wonderin, can't we do once per second vs random out of 20?

**Comment by uecasm** [comment]
No, it's client-side too.  Look inside the `ColonyBorderRenderer` and the `ColonyBlueprintRenderer` for example.

**Pull request merged**
