### PR TITLE
Extend research unlocked loot condition

### PR DESCRIPTION
**Pull request by uecasm**
Closes ldtteam/minecolonies-features#747

# Changes proposed in this pull request:
- Check additional loot parameters such that `research_unlocked` works for crafting recipes too
- Allow checking for specific research effect strength ranges too

Review please (could backport)

### CODE REVIEW

**Review by marchermans — COMMENTED** [review]
In general this is a good addition, but personally I would prefer if it is a seperate kind of loot condition

**Comment by uecasm** [comment]
> In general this is a good addition, but personally I would prefer if it is a seperate kind of loot condition

What do you mean by separate?  I don't think it makes much sense in having two conditions that both check for research unlocks... or do you mean one that checks purely for any unlock and another that checks for strength?  I don't really see why that would be useful to separate, that would just make the code more complicated.

**Comment by sweg4552** [comment]
Is there a reason that the research_unlocked checks the effect and not just the research itself?
Unlockable crafting recipes are able to take the research-id without needing an effect at all. 

As a datapacker it would be most intuitive to have a research_unlocked that takes research id & checks as a bool, and a effect_strength that takes effect id & checks it's integer value
If that's possible

**Comment by uecasm** [comment]
Because the way the research system is structured, the effects are intended to be the thing that actually has the gameplay effect (hence the name), while the research just unlocks the effects (and a bit of lore).

One idea is that you could make a "total conversion" research datapack that changes all the research but keeps the same effects.  (While you can change the effects that only affect recipes and loot tables, most of the others are used in the code and so have to remain essentially as-is anyway.)

The recipes were actually recently changed so that (while they still can refer to either research or effect) all the default recipes exclusively use effects now.

**Pull request merged**
