### PR TITLE
Feature/limit warehouse

### PR DESCRIPTION
**Pull request by Raycoms**
Limit warehouse to 1 per colony.
Also already merge release hotfix changes to version

@Kostronor @cltnschlosser 

Review please

### CODE REVIEW

**Review by marchermans — APPROVED** [review]
Looks good.
We might want to change this in the feature to allow only an arbitrary max number not just one.

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 83 issues
* ![MAJOR][MAJOR] 22 major
* ![MINOR][MINOR] 51 minor
* ![INFO][INFO] 10 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/9bd298b1ded93e6348e307cab69c0bce184fd51f/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.233 lines, which is greater than 750 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L43](https://github.com/Minecolonies/minecolonies/blob/9bd298b1ded93e6348e307cab69c0bce184fd51f/src/main/java/com/minecolonies/coremod/colony/Colony.java#L43): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 43 to the maximum authorized 20 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L43](https://github.com/Minecolonies/minecolonies/blob/9bd298b1ded93e6348e307cab69c0bce184fd51f/src/main/java/com/minecolonies/coremod/colony/Colony.java#L43): class "Colony" has 82 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L43](https://github.com/Minecolonies/minecolonies/blob/9bd298b1ded93e6348e307cab69c0bce184fd51f/src/main/java/com/minecolonies/coremod/colony/Colony.java#L43): Refactor this class so it has no more than 20 fields, rather than the 36 it currently has. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1820)
1. ![MAJOR][MAJOR] [Colony.java#L641](https://github.com/Minecolonies/minecolonies/blob/9bd298b1ded93e6348e307cab69c0bce184fd51f/src/main/java/com/minecolonies/coremod/colony/Colony.java#L641): Reduce the number of returns of this method 11, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L1159](https://github.com/Minecolonies/minecolonies/blob/9bd298b1ded93e6348e307cab69c0bce184fd51f/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1159): Assign this magic number 20 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1160](https://github.com/Minecolonies/minecolonies/blob/9bd298b1ded93e6348e307cab69c0bce184fd51f/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1160): Assign this magic number 60 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1273](https://github.com/Minecolonies/minecolonies/blob/9bd298b1ded93e6348e307cab69c0bce184fd51f/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1273): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1275](https://github.com/Minecolonies/minecolonies/blob/9bd298b1ded93e6348e307cab69c0bce184fd51f/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1275): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1277](https://github.com/Minecolonies/minecolonies/blob/9bd298b1ded93e6348e307cab69c0bce184fd51f/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1277): Assign this magic number 128 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

**Comment by Raycoms** [comment]
Actually, I don't see the usage of more warehouses (more than 1).
5 Deliverymen should be enough if not we can offer level 6,7,8,9 warehouse
upgrades.
What we should change in the future is a way to upgrade the storage limit
of the warehouse itself imo.

2017-05-07 11:36 GMT-03:00 Marc Hermans <notifications@github.com>:

**Comment by marvin-bitterlich** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/948/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Pull request merged**
