### PR TITLE
Translation first batch

### PR DESCRIPTION
**Pull request by marvin-bitterlich**
Our first batch of translations after the new translation system. 

Current Status:
image

All untranslated strings are inherited from the default and will be replaced once translated.

### CODE REVIEW

**Comment by marvin-bitterlich** [comment]
Deleted old languages for merge, so it goes clean.

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 38 issues
* ![MINOR][MINOR] 38 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/4dbb4e7a70d340506ddafe85e232442558e3a45f/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/4dbb4e7a70d340506ddafe85e232442558e3a45f/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render#](https://github.com/Minecolonies/minecolonies/blob/4dbb4e7a70d340506ddafe85e232442558e3a45f/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony#](https://github.com/Minecolonies/minecolonies/blob/4dbb4e7a70d340506ddafe85e232442558e3a45f/src/main/java/com/minecolonies/coremod/colony#): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings#](https://github.com/Minecolonies/minecolonies/blob/4dbb4e7a70d340506ddafe85e232442558e3a45f/src/main/java/com/minecolonies/coremod/colony/buildings#): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions#](https://github.com/Minecolonies/minecolonies/blob/4dbb4e7a70d340506ddafe85e232442558e3a45f/src/main/java/com/minecolonies/coremod/colony/permissions#): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [init#](https://github.com/Minecolonies/minecolonies/blob/4dbb4e7a70d340506ddafe85e232442558e3a45f/src/main/java/com/minecolonies/coremod/colony/requestsystem/init#): Add a 'package-info.java' file to document the 'init' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [locations#](https://github.com/Minecolonies/minecolonies/blob/4dbb4e7a70d340506ddafe85e232442558e3a45f/src/main/java/com/minecolonies/coremod/colony/requestsystem/locations#): Add a 'package-info.java' file to document the 'locations' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [management#](https://github.com/Minecolonies/minecolonies/blob/4dbb4e7a70d340506ddafe85e232442558e3a45f/src/main/java/com/minecolonies/coremod/colony/requestsystem/management#): Add a 'package-info.java' file to document the 'management' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [handlers#](https://github.com/Minecolonies/minecolonies/blob/4dbb4e7a70d340506ddafe85e232442558e3a45f/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers#): Add a 'package-info.java' file to document the 'handlers' package [rule](https://sonar.orionminecraft.com/coding_rules#rule_key=squid%3AS1228)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Raycoms** [comment]
:shipit: looks good for me

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1728/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Review by Asherslab — APPROVED** [review]
Honestly how am i even supposed to review this 😜 ? It looks good to me, i've no idea if the translations are correct 😛

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 38 issues
* ![MINOR][MINOR] 38 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/4dbb4e7a70d340506ddafe85e232442558e3a45f/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/4dbb4e7a70d340506ddafe85e232442558e3a45f/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render#](https://github.com/Minecolonies/minecolonies/blob/4dbb4e7a70d340506ddafe85e232442558e3a45f/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony#](https://github.com/Minecolonies/minecolonies/blob/4dbb4e7a70d340506ddafe85e232442558e3a45f/src/main/java/com/minecolonies/coremod/colony#): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings#](https://github.com/Minecolonies/minecolonies/blob/4dbb4e7a70d340506ddafe85e232442558e3a45f/src/main/java/com/minecolonies/coremod/colony/buildings#): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions#](https://github.com/Minecolonies/minecolonies/blob/4dbb4e7a70d340506ddafe85e232442558e3a45f/src/main/java/com/minecolonies/coremod/colony/permissions#): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [init#](https://github.com/Minecolonies/minecolonies/blob/4dbb4e7a70d340506ddafe85e232442558e3a45f/src/main/java/com/minecolonies/coremod/colony/requestsystem/init#): Add a 'package-info.java' file to document the 'init' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [locations#](https://github.com/Minecolonies/minecolonies/blob/4dbb4e7a70d340506ddafe85e232442558e3a45f/src/main/java/com/minecolonies/coremod/colony/requestsystem/locations#): Add a 'package-info.java' file to document the 'locations' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [management#](https://github.com/Minecolonies/minecolonies/blob/4dbb4e7a70d340506ddafe85e232442558e3a45f/src/main/java/com/minecolonies/coremod/colony/requestsystem/management#): Add a 'package-info.java' file to document the 'management' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [handlers#](https://github.com/Minecolonies/minecolonies/blob/4dbb4e7a70d340506ddafe85e232442558e3a45f/src/main/java/com/minecolonies/coremod/colony/requestsystem/management/handlers#): Add a 'package-info.java' file to document the 'handlers' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
