### PR TITLE
DRAFT: Initial refactor of ItemStorage into two objects

### PR DESCRIPTION
**Pull request by Mekle001**
# Changes proposed in this pull request:
- Create ItemStackHandling for comparison purposes
- Create ItemStackStorage for storage purposes
- Both extend the now-abstract ItemStorage
- Much of the functionality is still in the base, we can work to simplify and move unique functionality to the specific classes in the future. 

This is not yet ready to merge, much testing is still required. 

Review please

### CODE REVIEW

**Comment by marchermans** [comment]
I am going to be honest, I don't see a reason todo this.

From your code, and from the PR description this is completely unclear, increases the clutter and maintenance burden, and has no advantages, over just once class that can do both.

Could you make it more clear why we should take the hits in both complexity as well as burden of maintenance vs the older solution?

**Comment by Raycoms** [comment]
> I am going to be honest, I don't see a reason todo this.
> 
> From your code, and from the PR description this is completely unclear, increases the clutter and maintenance burden, and has no advantages, over just once class that can do both.
> 
> Could you make it more clear why we should take the hits in both complexity as well as burden of maintenance vs the older solution?

I had been talking with him about this. This has one big reason. We want to be able to do partial matching.
I.e: We look for an item with nbt x, we could allow fulfillment if the item in storage has nbt x+y. Now, if we do this, we need to know which one is the stored the stack (shouldn't ever have a ignorenbt etc) and the queried stack.

**Comment by marchermans** [comment]
I see no reason Todo this.
Your search will still be in a linear factor. So no performance improvement is to be expected.

**Comment by Raycoms** [comment]
> I see no reason Todo this.
> Your search will still be in a linear factor. So no performance improvement is to be expected.

It's not for performance. It's so that we can do one sided matches.

**Comment by Mekle001** [comment]
this is old enough, it's probably faster to recreate it post modularization.

**Pull request closed without merging**
