### PR TITLE
Guard need the right weapon (Ranger vs Knight)

### PR DESCRIPTION
**Pull request by xavierh**
Change neededForWorker so that the Knight vs Ranger is taken into account.

I also removed ItemTool, do they need tools ?

Review please

### CODE REVIEW

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 38 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 37 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [BuildingGuardTower.java#L548](https://github.com/Minecolonies/minecolonies/blob/b24215d323ce0fc521b984e50b4bc39ec435e571/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingGuardTower.java#L548): Reduce this class from 58 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/b24215d323ce0fc521b984e50b4bc39ec435e571/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/b24215d323ce0fc521b984e50b4bc39ec435e571/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/b24215d323ce0fc521b984e50b4bc39ec435e571/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/b24215d323ce0fc521b984e50b4bc39ec435e571/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/b24215d323ce0fc521b984e50b4bc39ec435e571/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/b24215d323ce0fc521b984e50b4bc39ec435e571/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/b24215d323ce0fc521b984e50b4bc39ec435e571/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/b24215d323ce0fc521b984e50b4bc39ec435e571/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [BuildingGuardTower.java#L553](https://github.com/Minecolonies/minecolonies/blob/b24215d323ce0fc521b984e50b4bc39ec435e571/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingGuardTower.java#L553): Make assignManually a static final constant or non-public and provide accessors if needed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 38 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 37 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [BuildingGuardTower.java#L548](https://github.com/Minecolonies/minecolonies/blob/edbe4a086d5369aed41fd9ea57d5f1967d4fc50b/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingGuardTower.java#L548): Reduce this class from 58 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/edbe4a086d5369aed41fd9ea57d5f1967d4fc50b/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/edbe4a086d5369aed41fd9ea57d5f1967d4fc50b/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/edbe4a086d5369aed41fd9ea57d5f1967d4fc50b/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/edbe4a086d5369aed41fd9ea57d5f1967d4fc50b/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/edbe4a086d5369aed41fd9ea57d5f1967d4fc50b/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/edbe4a086d5369aed41fd9ea57d5f1967d4fc50b/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/edbe4a086d5369aed41fd9ea57d5f1967d4fc50b/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/edbe4a086d5369aed41fd9ea57d5f1967d4fc50b/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [BuildingGuardTower.java#L553](https://github.com/Minecolonies/minecolonies/blob/edbe4a086d5369aed41fd9ea57d5f1967d4fc50b/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingGuardTower.java#L553): Make assignManually a static final constant or non-public and provide accessors if needed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1057/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 38 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 37 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [BuildingGuardTower.java#L548](https://github.com/Minecolonies/minecolonies/blob/bfdcacc61ebc432f628c82de9f4250b1f6c3556a/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingGuardTower.java#L548): Reduce this class from 58 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/bfdcacc61ebc432f628c82de9f4250b1f6c3556a/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/bfdcacc61ebc432f628c82de9f4250b1f6c3556a/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/bfdcacc61ebc432f628c82de9f4250b1f6c3556a/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/bfdcacc61ebc432f628c82de9f4250b1f6c3556a/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/bfdcacc61ebc432f628c82de9f4250b1f6c3556a/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/bfdcacc61ebc432f628c82de9f4250b1f6c3556a/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/bfdcacc61ebc432f628c82de9f4250b1f6c3556a/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/bfdcacc61ebc432f628c82de9f4250b1f6c3556a/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [BuildingGuardTower.java#L553](https://github.com/Minecolonies/minecolonies/blob/bfdcacc61ebc432f628c82de9f4250b1f6c3556a/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingGuardTower.java#L553): Make assignManually a static final constant or non-public and provide accessors if needed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by marvin-bitterlich** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1057/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 35 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 34 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [BuildingGuardTower.java#L548](https://github.com/Minecolonies/minecolonies/blob/ec2e98ec92a8d6cb1baf2ac5630bb0a03cb4b393/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingGuardTower.java#L548): Reduce this class from 58 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/ec2e98ec92a8d6cb1baf2ac5630bb0a03cb4b393/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/ec2e98ec92a8d6cb1baf2ac5630bb0a03cb4b393/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/ec2e98ec92a8d6cb1baf2ac5630bb0a03cb4b393/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/ec2e98ec92a8d6cb1baf2ac5630bb0a03cb4b393/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/ec2e98ec92a8d6cb1baf2ac5630bb0a03cb4b393/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [BuildingGuardTower.java#L553](https://github.com/Minecolonies/minecolonies/blob/ec2e98ec92a8d6cb1baf2ac5630bb0a03cb4b393/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingGuardTower.java#L553): Make assignManually a static final constant or non-public and provide accessors if needed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![MINOR][MINOR] [BuildingGuardTower.java#L558](https://github.com/Minecolonies/minecolonies/blob/ec2e98ec92a8d6cb1baf2ac5630bb0a03cb4b393/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingGuardTower.java#L558): Make retrieveOnLowHealth a static final constant or non-public and provide accessors if needed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![MINOR][MINOR] [BuildingGuardTower.java#L563](https://github.com/Minecolonies/minecolonies/blob/ec2e98ec92a8d6cb1baf2ac5630bb0a03cb4b393/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingGuardTower.java#L563): Make patrolManually a static final constant or non-public and provide accessors if needed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)
1. ![MINOR][MINOR] [BuildingGuardTower.java#L568](https://github.com/Minecolonies/minecolonies/blob/ec2e98ec92a8d6cb1baf2ac5630bb0a03cb4b393/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingGuardTower.java#L568): Make task a static final constant or non-public and provide accessors if needed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AClassVariableVisibilityCheck)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
