### PR TITLE
Comments out colony specialization button

### PR DESCRIPTION
**Pull request by PowerSchill**
Closes # https://github.com/ldtteam/minecolonies-features/issues/55
Closes #
Closes #

# Changes proposed in this pull request:
-
-
-

Review please

### CODE REVIEW

**Comment by Nightenom** [comment]
You can disable it tho

**Comment by ravenbuilder934** [comment]
Why does it close the issue? The issue isn't for removing the button, it's for adding a function to the button. This is just a temporary fix.

**Comment by Raycoms** [comment]
Ye, doesn't have to close it. But def :shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/5586/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Comment by PowerSchill** [comment]
Well we could create a new feature request since this request is vague but I think this is one of those huge features that live on the developers' personal lists.

**Pull request merged**
