### PR TITLE
move more utils

### PR DESCRIPTION
**Pull request by marvin-bitterlich**
Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
:shipit:

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1069/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 256 issues
* ![MAJOR][MAJOR] 152 major
* ![MINOR][MINOR] 55 minor
* ![INFO][INFO] 49 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [WindowHireWorker.java#L125](https://github.com/Minecolonies/minecolonies/blob/005d786fe1e12b25d27c1ac65f809bbf88ce19ea/src/main/java/com/minecolonies/coremod/client/gui/WindowHireWorker.java#L125): Reduce this anonymous class number of lines from 31 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowHutFarmer.java#L206](https://github.com/Minecolonies/minecolonies/blob/005d786fe1e12b25d27c1ac65f809bbf88ce19ea/src/main/java/com/minecolonies/coremod/client/gui/WindowHutFarmer.java#L206): Reduce this anonymous class number of lines from 37 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowHutMiner.java#L59](https://github.com/Minecolonies/minecolonies/blob/005d786fe1e12b25d27c1ac65f809bbf88ce19ea/src/main/java/com/minecolonies/coremod/client/gui/WindowHutMiner.java#L59): Reduce this anonymous class number of lines from 22 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L472](https://github.com/Minecolonies/minecolonies/blob/005d786fe1e12b25d27c1ac65f809bbf88ce19ea/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L472): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L627](https://github.com/Minecolonies/minecolonies/blob/005d786fe1e12b25d27c1ac65f809bbf88ce19ea/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L627): Reduce this anonymous class number of lines from 24 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L728](https://github.com/Minecolonies/minecolonies/blob/005d786fe1e12b25d27c1ac65f809bbf88ce19ea/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L728): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L886](https://github.com/Minecolonies/minecolonies/blob/005d786fe1e12b25d27c1ac65f809bbf88ce19ea/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L886): Reduce this anonymous class number of lines from 40 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [CitizenData.java#L23](https://github.com/Minecolonies/minecolonies/blob/005d786fe1e12b25d27c1ac65f809bbf88ce19ea/src/main/java/com/minecolonies/coremod/colony/CitizenData.java#L23): class "CitizenData" has 43 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/005d786fe1e12b25d27c1ac65f809bbf88ce19ea/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.223 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L46](https://github.com/Minecolonies/minecolonies/blob/005d786fe1e12b25d27c1ac65f809bbf88ce19ea/src/main/java/com/minecolonies/coremod/colony/Colony.java#L46): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 43 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by cltnschlosser** [comment]
Just the duplicate imports, and then syncing with version/1.11, and I'd say this is good.

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 253 issues
* ![MAJOR][MAJOR] 154 major
* ![MINOR][MINOR] 49 minor
* ![INFO][INFO] 50 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [WindowHireWorker.java#L125](https://github.com/Minecolonies/minecolonies/blob/e52117a61d4a906c38c5727fdc26a15eb6bbff27/src/main/java/com/minecolonies/coremod/client/gui/WindowHireWorker.java#L125): Reduce this anonymous class number of lines from 31 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowHutFarmer.java#L206](https://github.com/Minecolonies/minecolonies/blob/e52117a61d4a906c38c5727fdc26a15eb6bbff27/src/main/java/com/minecolonies/coremod/client/gui/WindowHutFarmer.java#L206): Reduce this anonymous class number of lines from 37 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowHutMiner.java#L59](https://github.com/Minecolonies/minecolonies/blob/e52117a61d4a906c38c5727fdc26a15eb6bbff27/src/main/java/com/minecolonies/coremod/client/gui/WindowHutMiner.java#L59): Reduce this anonymous class number of lines from 22 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L472](https://github.com/Minecolonies/minecolonies/blob/e52117a61d4a906c38c5727fdc26a15eb6bbff27/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L472): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L627](https://github.com/Minecolonies/minecolonies/blob/e52117a61d4a906c38c5727fdc26a15eb6bbff27/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L627): Reduce this anonymous class number of lines from 24 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L728](https://github.com/Minecolonies/minecolonies/blob/e52117a61d4a906c38c5727fdc26a15eb6bbff27/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L728): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L886](https://github.com/Minecolonies/minecolonies/blob/e52117a61d4a906c38c5727fdc26a15eb6bbff27/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L886): Reduce this anonymous class number of lines from 40 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [CitizenData.java#L23](https://github.com/Minecolonies/minecolonies/blob/e52117a61d4a906c38c5727fdc26a15eb6bbff27/src/main/java/com/minecolonies/coremod/colony/CitizenData.java#L23): class "CitizenData" has 43 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/e52117a61d4a906c38c5727fdc26a15eb6bbff27/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.224 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L46](https://github.com/Minecolonies/minecolonies/blob/e52117a61d4a906c38c5727fdc26a15eb6bbff27/src/main/java/com/minecolonies/coremod/colony/Colony.java#L46): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 44 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 303 issues
* ![MAJOR][MAJOR] 183 major
* ![MINOR][MINOR] 68 minor
* ![INFO][INFO] 52 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [WindowHireWorker.java#L125](https://github.com/Minecolonies/minecolonies/blob/16f5ccb545d62a50c27ca2efecf2e8def5763ca0/src/main/java/com/minecolonies/coremod/client/gui/WindowHireWorker.java#L125): Reduce this anonymous class number of lines from 31 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowHutFarmer.java#L206](https://github.com/Minecolonies/minecolonies/blob/16f5ccb545d62a50c27ca2efecf2e8def5763ca0/src/main/java/com/minecolonies/coremod/client/gui/WindowHutFarmer.java#L206): Reduce this anonymous class number of lines from 37 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowHutMiner.java#L59](https://github.com/Minecolonies/minecolonies/blob/16f5ccb545d62a50c27ca2efecf2e8def5763ca0/src/main/java/com/minecolonies/coremod/client/gui/WindowHutMiner.java#L59): Reduce this anonymous class number of lines from 22 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L472](https://github.com/Minecolonies/minecolonies/blob/16f5ccb545d62a50c27ca2efecf2e8def5763ca0/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L472): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L627](https://github.com/Minecolonies/minecolonies/blob/16f5ccb545d62a50c27ca2efecf2e8def5763ca0/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L627): Reduce this anonymous class number of lines from 24 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L728](https://github.com/Minecolonies/minecolonies/blob/16f5ccb545d62a50c27ca2efecf2e8def5763ca0/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L728): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L886](https://github.com/Minecolonies/minecolonies/blob/16f5ccb545d62a50c27ca2efecf2e8def5763ca0/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L886): Reduce this anonymous class number of lines from 40 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [CitizenData.java#L23](https://github.com/Minecolonies/minecolonies/blob/16f5ccb545d62a50c27ca2efecf2e8def5763ca0/src/main/java/com/minecolonies/coremod/colony/CitizenData.java#L23): class "CitizenData" has 43 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/16f5ccb545d62a50c27ca2efecf2e8def5763ca0/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.226 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L48](https://github.com/Minecolonies/minecolonies/blob/16f5ccb545d62a50c27ca2efecf2e8def5763ca0/src/main/java/com/minecolonies/coremod/colony/Colony.java#L48): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 44 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
