### PR TITLE
Fix smelter fuel retaining to not be coal greedy

### PR DESCRIPTION
**Pull request by Mekle001**
# Changes proposed in this pull request:
- change the keep to be only one stack of fuel, and properly compare against allowed fuels

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
Well, maybe furnaces * stacks?

**Comment by Raycoms** [comment]
Or buildinglevel stacks

**Comment by Mekle001** [comment]
Went to a constant 5 stacks retained, as both building level and furnacecount are not available in the constructor.

**Comment by uecasm** [comment]
Can't you just adjust the keepX stack size after the data is loaded / level up?

**Comment by Raycoms** [comment]
> Can't you just adjust the keepX stack size after the data is loaded / level up?

Well, there is the method that queries the keepX where we could adjust it manually.

**Comment by Mekle001** [comment]
Ok, moved all of the retention down to abstractBuildingFurnaceUser, and have it auto-calcing the size to retain based on building level. This actually fixes all of our furnace users, which had varying levels of support for fuel retention.

**Review by Raycoms — APPROVED** [review]

**Pull request merged**
