### PR TITLE
Recipe templates

### PR DESCRIPTION
**Pull request by uecasm**
# Changes proposed in this pull request:
- Adds "custom recipe templates".  These are similar in format to custom recipes but with an extra wrapper that specifies a tag and filter -- for each item in the tag matching the filter, it will attempt to substitute the resource id into the recipe template contents, and if **all** of these substitutions result in valid items, the recipe is considered valid and added.
    - `"type"` is always `"recipe-template"`
    - `"tag"` specifies the name of a tag to search (without leading `#`)
    - `"filter"` is either a single string or an array of strings.  Only items containing at least one of these strings are included.
        - Alternatively, it can be an object with `"include"` and `"exclude"` (each either string or list as above).  As you'd expect, any substring in `include` adds it unless it also matches any substring in `exclude`.
    - `"recipe"` is the actual custom recipe, with properties as normal except that anywhere that an item id is specified, you may either specify a fixed id as usual or you can use one of the following substitutions (amongst other fixed characters):
        - `[NS]` => the namespace of the tag item
        - `[PATH]` => the path of the tag item
        - `[PATH:abc=def]` => the path of the tag item, replacing `abc` with `def`
- Removes the old datagen recipes for log stripping.
- Adds new (non-datagen) recipe templates for log stripping.
    - Notably, these add support for mangrove, and should in theory automatically extend to modded logs, provided they're added to the `minecraft:logs` tag and they fit the standard naming conventions (including having a `wood` form).
- If `auditcraftingtags` is enabled, it logs status on login/reload (to minecraft logs, not files) to help confirm that it's generating the recipes you're expecting.
- Special exception: an `"alternate-output"` that fails to generate a real item will be ignored (and logged) instead of rejecting the entire recipe -- unless everything fails and the whole recipe then has no outputs, in which case it's still rejected.
- In order to support that, it's now allowed (only when using `alternate-output`) to not specify a `result` and only have alternates.

Review please (could port)

~~Not currently implemented, but considering: relaxing the "all must be valid" restriction specifically for the alternative outputs.  This would for example extend support to logs that don't have a `wood` form.  I don't want to relax the rules for the input or output, though, as that might cause unintended recipes.~~

### CODE REVIEW

**Comment by Shadizar** [comment]
I recommend in-game testing with BoP and BYG at least, before pushing into actual releases...when doing datapacks, BYG had some 'interesting' wood permutations.

Will this break existing datapacks that implemented log handling? Or will the log handling portions simply no longer function and this new template will work instead?

**Comment by MotionlessTrain** [comment]
> Will this break existing datapacks that implemented log handling? Or will the log handling portions simply no longer function and this new template will work instead?

I guess the recipe would be registered twice

**Comment by uecasm** [comment]
@Shadizar yes, that's right, if it's also in a datapack then you'll get two copies of the same recipe.  Other than wasting a slot (which is harmless for the forester) it just means they'll pick one at semi-random, which is mostly harmless when the recipes are the same, but ideally once this lands you should remove the duplicate recipe from the datapack.

As for BoP/BYG compat, this is the current status of things:

```
Template minecolonies:lumberjack/strip_logs with minecraft:dark_oak_log: success
Template minecolonies:lumberjack/strip_logs with minecraft:stripped_dark_oak_log: rejecting result minecraft:stripped_stripped_dark_oak_log
Template minecolonies:lumberjack/strip_logs with minecraft:oak_log: success
Template minecolonies:lumberjack/strip_logs with minecraft:stripped_oak_log: rejecting result minecraft:stripped_stripped_oak_log
Template minecolonies:lumberjack/strip_logs with byg:withering_oak_log: rejecting result byg:stripped_withering_oak_log
Template minecolonies:lumberjack/strip_logs with minecraft:acacia_log: success
Template minecolonies:lumberjack/strip_logs with minecraft:stripped_acacia_log: rejecting result minecraft:stripped_stripped_acacia_log
Template minecolonies:lumberjack/strip_logs with minecraft:birch_log: success
Template minecolonies:lumberjack/strip_logs with minecraft:stripped_birch_log: rejecting result minecraft:stripped_stripped_birch_log
Template minecolonies:lumberjack/strip_logs with minecraft:jungle_log: success
Template minecolonies:lumberjack/strip_logs with minecraft:stripped_jungle_log: rejecting result minecraft:stripped_stripped_jungle_log
Template minecolonies:lumberjack/strip_logs with minecraft:spruce_log: success
Template minecolonies:lumberjack/strip_logs with minecraft:stripped_spruce_log: rejecting result minecraft:stripped_stripped_spruce_log
Template minecolonies:lumberjack/strip_logs with minecraft:mangrove_log: success
Template minecolonies:lumberjack/strip_logs with minecraft:stripped_mangrove_log: rejecting result minecraft:stripped_stripped_mangrove_log
Template minecolonies:lumberjack/strip_logs with byg:aspen_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_aspen_log: rejecting result byg:stripped_stripped_aspen_log
Template minecolonies:lumberjack/strip_logs with byg:baobab_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_baobab_log: rejecting result byg:stripped_stripped_baobab_log
Template minecolonies:lumberjack/strip_logs with byg:blue_enchanted_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_blue_enchanted_log: rejecting result byg:stripped_stripped_blue_enchanted_log
Template minecolonies:lumberjack/strip_logs with byg:cherry_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_cherry_log: rejecting result byg:stripped_stripped_cherry_log
Template minecolonies:lumberjack/strip_logs with byg:cika_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_cika_log: rejecting result byg:stripped_stripped_cika_log
Template minecolonies:lumberjack/strip_logs with byg:cypress_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_cypress_log: rejecting result byg:stripped_stripped_cypress_log
Template minecolonies:lumberjack/strip_logs with byg:ebony_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_ebony_log: rejecting result byg:stripped_stripped_ebony_log
Template minecolonies:lumberjack/strip_logs with byg:ether_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_ether_log: rejecting result byg:stripped_stripped_ether_log
Template minecolonies:lumberjack/strip_logs with byg:fir_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_fir_log: rejecting result byg:stripped_stripped_fir_log
Template minecolonies:lumberjack/strip_logs with byg:green_enchanted_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_green_enchanted_log: rejecting result byg:stripped_stripped_green_enchanted_log
Template minecolonies:lumberjack/strip_logs with byg:holly_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_holly_log: rejecting result byg:stripped_stripped_holly_log
Template minecolonies:lumberjack/strip_logs with byg:jacaranda_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_jacaranda_log: rejecting result byg:stripped_stripped_jacaranda_log
Template minecolonies:lumberjack/strip_logs with byg:mahogany_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_mahogany_log: rejecting result byg:stripped_stripped_mahogany_log
Template minecolonies:lumberjack/strip_logs with byg:maple_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_maple_log: rejecting result byg:stripped_stripped_maple_log
Template minecolonies:lumberjack/strip_logs with byg:nightshade_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_nightshade_log: rejecting result byg:stripped_stripped_nightshade_log
Template minecolonies:lumberjack/strip_logs with byg:palm_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_palm_log: rejecting result byg:stripped_stripped_palm_log
Template minecolonies:lumberjack/strip_logs with byg:pine_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_pine_log: rejecting result byg:stripped_stripped_pine_log
Template minecolonies:lumberjack/strip_logs with byg:rainbow_eucalyptus_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_rainbow_eucalyptus_log: rejecting result byg:stripped_stripped_rainbow_eucalyptus_log
Template minecolonies:lumberjack/strip_logs with byg:redwood_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_redwood_log: rejecting result byg:stripped_stripped_redwood_log
Template minecolonies:lumberjack/strip_logs with byg:skyris_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_skyris_log: rejecting result byg:stripped_stripped_skyris_log
Template minecolonies:lumberjack/strip_logs with byg:stripped_white_mangrove_log: rejecting result byg:stripped_stripped_white_mangrove_log
Template minecolonies:lumberjack/strip_logs with byg:white_mangrove_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_willow_log: rejecting result byg:stripped_stripped_willow_log
Template minecolonies:lumberjack/strip_logs with byg:willow_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_witch_hazel_log: rejecting result byg:stripped_stripped_witch_hazel_log
Template minecolonies:lumberjack/strip_logs with byg:witch_hazel_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_zelkova_log: rejecting result byg:stripped_stripped_zelkova_log
Template minecolonies:lumberjack/strip_logs with byg:zelkova_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:fir_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:stripped_fir_log: rejecting result biomesoplenty:stripped_stripped_fir_log
Template minecolonies:lumberjack/strip_logs with biomesoplenty:redwood_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:stripped_redwood_log: rejecting result biomesoplenty:stripped_stripped_redwood_log
Template minecolonies:lumberjack/strip_logs with biomesoplenty:cherry_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:stripped_cherry_log: rejecting result biomesoplenty:stripped_stripped_cherry_log
Template minecolonies:lumberjack/strip_logs with biomesoplenty:mahogany_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:stripped_mahogany_log: rejecting result biomesoplenty:stripped_stripped_mahogany_log
Template minecolonies:lumberjack/strip_logs with biomesoplenty:jacaranda_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:stripped_jacaranda_log: rejecting result biomesoplenty:stripped_stripped_jacaranda_log
Template minecolonies:lumberjack/strip_logs with biomesoplenty:palm_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:stripped_palm_log: rejecting result biomesoplenty:stripped_stripped_palm_log
Template minecolonies:lumberjack/strip_logs with biomesoplenty:willow_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:stripped_willow_log: rejecting result biomesoplenty:stripped_stripped_willow_log
Template minecolonies:lumberjack/strip_logs with biomesoplenty:dead_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:stripped_dead_log: rejecting result biomesoplenty:stripped_stripped_dead_log
Template minecolonies:lumberjack/strip_logs with biomesoplenty:magic_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:stripped_magic_log: rejecting result biomesoplenty:stripped_stripped_magic_log
Template minecolonies:lumberjack/strip_logs with biomesoplenty:umbran_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:stripped_umbran_log: rejecting result biomesoplenty:stripped_stripped_umbran_log
Template minecolonies:lumberjack/strip_logs with byg:lament_log: success
Template minecolonies:lumberjack/strip_logs with byg:stripped_lament_log: rejecting result byg:stripped_stripped_lament_log
Template minecolonies:lumberjack/strip_logs with biomesoplenty:hellbark_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:stripped_hellbark_log: rejecting result biomesoplenty:stripped_stripped_hellbark_log
Template minecolonies:lumberjack/strip_stems with minecraft:crimson_stem: success
Template minecolonies:lumberjack/strip_stems with minecraft:stripped_crimson_stem: rejecting result minecraft:stripped_stripped_crimson_stem
Template minecolonies:lumberjack/strip_stems with minecraft:warped_stem: success
Template minecolonies:lumberjack/strip_stems with minecraft:stripped_warped_stem: rejecting result minecraft:stripped_stripped_warped_stem
Template minecolonies:lumberjack/strip_stems with byg:bulbis_stem: rejecting alternate-output byg:bulbis_hyphae
Template minecolonies:lumberjack/strip_stems with byg:stripped_bulbis_stem: rejecting result byg:stripped_stripped_bulbis_stem
Template minecolonies:lumberjack/strip_stems with byg:imparius_stem: rejecting result byg:stripped_imparius_stem
Template minecolonies:lumberjack/strip_stems with byg:stripped_sythian_stem: rejecting result byg:stripped_stripped_sythian_stem
Template minecolonies:lumberjack/strip_stems with byg:sythian_stem: success
```
Note that the "stripped_*: rejecting result stripped_stripped_" is normal and expected -- that happens because both the regular and the stripped logs are `minecraft:logs`.  Anything else indicates something not following the standard naming patterns.

As far as I can see, the only actual mismatch here is that the `byg:bulbis_stem` doesn't seem to have a matching `_hyphae` -- which currently means that it won't let you strip it at all.  Looking in-game, it appears it has `_wood` instead, which seems like an odd choice, and perhaps a bug on their side.  Though I could perhaps restructure things to make this case work as well, if I allow optional additional outputs.  Though that would make this logging a bit more spammy.

**Comment by Shadizar** [comment]
another:
`{
  "type" : "recipe",
  "crafter": "lumberjack_custom",
  "inputs": [
    {
        "item" : "byg:embur_pedu",
        "count": 1
    }
  ],
  "alternate-output" : [
    {
        "item" : "byg:embur_hyphae",
        "count": 1
    },
    {
        "item" : "byg:stripped_embur_hyphae",
        "count": 1
    }
  ],
  "result": "byg:stripped_embur_pedu",
  "count": 1,
  "tool": "axe",
  "intermediate" : "minecraft:air"
}`

looking for more

**Comment by Shadizar** [comment]
`{
  "type" : "recipe",
  "crafter": "lumberjack_custom",
  "inputs": [
    {
        "item" : "byg:fungal_imparius_stem",
        "count": 1
    }
  ],
  "result": "byg:fungal_imparius_hyphae",
  "count": 1,
  "tool": "axe",
  "intermediate" : "minecraft:air"
}

and
{
  "type" : "recipe",
  "crafter": "lumberjack_custom",
  "inputs": [
    {
        "item" : "byg:imparius_stem",
        "count": 1
    }
  ],
  "result": "byg:imparius_hyphae",
  "count": 1,
  "tool": "axe",
  "intermediate" : "minecraft:air"
}`

**Comment by Shadizar** [comment]
`{
  "type" : "recipe",
  "crafter": "lumberjack_custom",
  "inputs": [
    {
        "item" : "byg:palo_verde_log",
        "count": 1
    }
  ],
  "alternate-output" : [
    {
        "item" : "byg:palo_verde_wood",
        "count": 1
    },
    {
        "item" : "byg:stripped_palo_verde_wood",
        "count": 1
    }
  ],
  "result": "byg:stripped_palo_verde_log",
  "count": 1,
  "tool": "axe",
  "intermediate" : "minecraft:air"
}`

but, you can see the other ones at <https://github.com/Shadizar/minecoloniesbiomesyoullgodatapack/tree/main/minecoloniesbiomesyoullgodatapack/data/bygminecolonies/crafterrecipes>
haven't looked beyond palo verde yet

**Comment by uecasm** [comment]
Well, `palo_verde_log` should be reported to BYG as a bug, since it's not actually a `#minecraft:logs`.  They didn't even add it to their own `logs` tag.  That's probably true for the others too, but I didn't specifically check.

You could probably add them to the tag in your datapack until they fix that (which would be needed for tree-cutting to work too anyway).

As for `embur_pedu`, you'd probably still need a custom recipe for that one.  I'm not going to add non-standard names just for a single mod-specific case.

**Comment by uecasm** [comment]
Improved the filtering a bit and made it support optional outputs, including a workaround for Bulbis.  So now the list is:

```
Template minecolonies:lumberjack/strip_logs with minecraft:dark_oak_log: success
Template minecolonies:lumberjack/strip_logs with minecraft:oak_log: success
Template minecolonies:lumberjack/strip_logs with minecraft:acacia_log: success
Template minecolonies:lumberjack/strip_logs with minecraft:birch_log: success
Template minecolonies:lumberjack/strip_logs with minecraft:jungle_log: success
Template minecolonies:lumberjack/strip_logs with minecraft:spruce_log: success
Template minecolonies:lumberjack/strip_logs with minecraft:mangrove_log: success
Template minecolonies:lumberjack/strip_logs with byg:aspen_log: success
Template minecolonies:lumberjack/strip_logs with byg:baobab_log: success
Template minecolonies:lumberjack/strip_logs with byg:blue_enchanted_log: success
Template minecolonies:lumberjack/strip_logs with byg:cherry_log: success
Template minecolonies:lumberjack/strip_logs with byg:cika_log: success
Template minecolonies:lumberjack/strip_logs with byg:cypress_log: success
Template minecolonies:lumberjack/strip_logs with byg:ebony_log: success
Template minecolonies:lumberjack/strip_logs with byg:ether_log: success
Template minecolonies:lumberjack/strip_logs with byg:fir_log: success
Template minecolonies:lumberjack/strip_logs with byg:green_enchanted_log: success
Template minecolonies:lumberjack/strip_logs with byg:holly_log: success
Template minecolonies:lumberjack/strip_logs with byg:jacaranda_log: success
Template minecolonies:lumberjack/strip_logs with byg:mahogany_log: success
Template minecolonies:lumberjack/strip_logs with byg:maple_log: success
Template minecolonies:lumberjack/strip_logs with byg:nightshade_log: success
Template minecolonies:lumberjack/strip_logs with byg:palm_log: success
Template minecolonies:lumberjack/strip_logs with byg:pine_log: success
Template minecolonies:lumberjack/strip_logs with byg:rainbow_eucalyptus_log: success
Template minecolonies:lumberjack/strip_logs with byg:redwood_log: success
Template minecolonies:lumberjack/strip_logs with byg:skyris_log: success
Template minecolonies:lumberjack/strip_logs with byg:white_mangrove_log: success
Template minecolonies:lumberjack/strip_logs with byg:willow_log: success
Template minecolonies:lumberjack/strip_logs with byg:witch_hazel_log: success
Template minecolonies:lumberjack/strip_logs with byg:withering_oak_log: ignoring alternate-output byg:stripped_withering_oak_log
Template minecolonies:lumberjack/strip_logs with byg:withering_oak_log: ignoring alternate-output byg:stripped_withering_oak_wood
Template minecolonies:lumberjack/strip_logs with byg:withering_oak_log: success
Template minecolonies:lumberjack/strip_logs with byg:zelkova_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:fir_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:redwood_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:cherry_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:mahogany_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:jacaranda_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:palm_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:willow_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:dead_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:magic_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:umbran_log: success
Template minecolonies:lumberjack/strip_logs with byg:lament_log: success
Template minecolonies:lumberjack/strip_logs with biomesoplenty:hellbark_log: success
Template minecolonies:lumberjack/strip_stems with minecraft:crimson_stem: ignoring alternate-output minecraft:crimson_wood
Template minecolonies:lumberjack/strip_stems with minecraft:crimson_stem: ignoring alternate-output minecraft:stripped_crimson_wood
Template minecolonies:lumberjack/strip_stems with minecraft:crimson_stem: success
Template minecolonies:lumberjack/strip_stems with minecraft:warped_stem: ignoring alternate-output minecraft:warped_wood
Template minecolonies:lumberjack/strip_stems with minecraft:warped_stem: ignoring alternate-output minecraft:stripped_warped_wood
Template minecolonies:lumberjack/strip_stems with minecraft:warped_stem: success
Template minecolonies:lumberjack/strip_stems with byg:bulbis_stem: ignoring alternate-output byg:bulbis_hyphae
Template minecolonies:lumberjack/strip_stems with byg:bulbis_stem: ignoring alternate-output byg:stripped_bulbis_hyphae
Template minecolonies:lumberjack/strip_stems with byg:bulbis_stem: success
Template minecolonies:lumberjack/strip_stems with byg:imparius_stem: ignoring alternate-output byg:stripped_imparius_stem
Template minecolonies:lumberjack/strip_stems with byg:imparius_stem: ignoring alternate-output byg:stripped_imparius_hyphae
Template minecolonies:lumberjack/strip_stems with byg:imparius_stem: ignoring alternate-output byg:imparius_wood
Template minecolonies:lumberjack/strip_stems with byg:imparius_stem: ignoring alternate-output byg:stripped_imparius_wood
Template minecolonies:lumberjack/strip_stems with byg:imparius_stem: success
Template minecolonies:lumberjack/strip_stems with byg:sythian_stem: ignoring alternate-output byg:sythian_wood
Template minecolonies:lumberjack/strip_stems with byg:sythian_stem: ignoring alternate-output byg:stripped_sythian_wood
Template minecolonies:lumberjack/strip_stems with byg:sythian_stem: success
```

If something isn't listed at all, it means that it's not in the tag or doesn't conform to the `_log` or `_stem` suffix, and would still need to be in a datapack or (preferably) fixed in BYG itself.

**Review by Raycoms — APPROVED** [review]

**Comment by uecasm** [comment]
Builds fine locally, so I'm assuming that's TeamCity being a derp.

**Pull request merged**
