### PR TITLE
Fix citizen icon rendering

### LINKED ISSUE #5: Minecolonies Bug with Oculus
Check here for the Issue https://github.com/LunaPixelStudios/Medieval-Minecraft/issues/96#issuecomment-1062769844

Minecolonies Icons bugging out with Oculus

### LINKED ISSUE #84: [1.18.2] Character rendering problem with Minecolonies
### What happened?

Reproduce with:
minecolonies-1.18.2-1.0.720-ALPHA

### Screenshots

Without Oculus:

With Oculus:

Only change oculus,always install rubidium

### Relevant log output

_No response_

### Minecraft Version

1.18.2

### Iris Version

oculus-mc1.18.2-1.2.4

### Sodium Version

rubidium-0.5.2a

### Operating System

Win10

### What is your GPU?

GTX1650

### Java Version

java17

### Additional context

_No response_

### LINKED ISSUE #126: Graphical Artefacts with Minecolonies (Mod) UI Elements
### What happened?

UI Elements used in the Minecolonies mod breaks Oculus.

Two issues.

The inworld UI elements above NPCs draw connected voids between each other across the screen. This issue disappears when F1 is used.

When using the Structurize build function (Bundled with the Minecolonies) the template distorts in a way where it is showing the backside of the blocks, almost in negative space. This issue remains when F1 is used.

Was able to isolate this to Oculus with a few levels of troubleshooting:

- With Oculus disabled the issue is gone
- Not related to shader pack choice as occurs on all shaders and even shaders disabled
- Have toggled pretty much every setting in Oculus and the Shader settings in hopes of finding a particular setting that is causing the issue but no luck

Attached are screenshots showing the draw issue.
UI Screen Draws
F1 - True
F1 - False

Screenshot of the Structurize build tool issue
Structurize Build Tool Issue

### Screenshots

_No response_

### Relevant log output

_No response_

### Minecraft Version

1.18.2

### Iris Version

mc1.18.2-1.2.5 and 1.2.4 (Rolled back for testing)

### Sodium Version

Rubidium-0.5.2a

### Operating System

Windows 11

### What is your GPU?

Nvidia GeForce RTX 2070 Super

### Java Version

17.0.1

### Additional context

_No response_

### LINKED ISSUE #142: Rubidium + Oculus (AstraLex Shader) + Minecolonies colonists have weird graphical glitch.
### What happened?

When I had switched over from using optifine, to Rubidium, & Oculus, I loaded into my world only to notice a weird yellow line in the world. I followed it to find the colonists from Minecolonies had a weird visual glitch over their heads. If you need anything more than what I've provided, please let me know! 

### Screenshots

Edit: Wrong screenshot, oops.
2022-07-29_02 22 17-min

### Relevant log output

_No response_

### Minecraft Version

1.18.2

### Iris Version

Oculus-mc1.18.2-1.2.5

### Sodium Version

Rubidium-0.5.3

### Operating System

Win 10

### What is your GPU?

Nvidea GeForce RTX 3070 TI

### Java Version

Using Curseforge, don't know which is exactly running, but java -version returns Java 18

### Additional context

Here's the latest.log
[latest.log](https://github.com/Asek3/Oculus/files/9218163/latest.log)

### PR DESCRIPTION
**Pull request by Shadows-of-Fire**
Fixes https://github.com/Asek3/Oculus/issues/5
Fixes https://github.com/Asek3/Oculus/issues/84
Fixes https://github.com/Asek3/Oculus/issues/126
Fixes https://github.com/Asek3/Oculus/issues/142

This removes the (weird) custom rendertype that was being used for the citizen icon and moves it to entity cutout.  This resolves an issue with Oculus where vertices leaked since the custom render type was set to mode triangles when it was drawing quads.
The render type was removed since it is unnecessary, the issue @OrionDevelopment mentioned (transparency sorting) is no longer present on any graphics mode, and the icon renders as expected in front of water and clouds.

### CODE REVIEW

**Review by Nightenom — APPROVED** [review]
Don't know if entity cutout is fine/isn't overkill for primitive texturing but w/e. Did u test vanilla/optifine/your mod?

**Comment by MotionlessTrain** [comment]
Could someone port this PR to 1.19?

**Comment by Raycoms** [comment]
@Shadows-of-Fire this is not working as intended at all. Icons are supposed to render through walls just like the citizen names. It's essential to see if a citizen is "blocked from working" etc.

**Comment by Shadows-of-Fire** [comment]
Sounds like a custom render type with depth testing disabled is necessary then.  The changes wouldn't be significant (just copypaste the decl for the rtype it's using and add the depth test decl).

**Comment by Raycoms** [comment]
did this here: https://github.com/ldtteam/minecolonies/pull/8644

**Pull request merged**
