### PR TITLE
optimize images

### PR DESCRIPTION
**Pull request by ravenbuilder934**
Closes #
Closes #
Closes #

# Changes proposed in this pull request:
- optimizes images, reduces file size by about 0.2MB total
-
-

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
Bets are on the table, how many textures did Raven break this time?

**Comment by ravenbuilder934** [comment]
Aw come on, I used a bot! It ~~shouldn't have~~ _**didn't**_ move around or rename any textures!

**Comment by Asherslab** [comment]
Did you compile and test it?

**Comment by ravenbuilder934** [comment]
yeah, works fine

**Comment by marchermans** [comment]
CLA not signed!

**Comment by ravenbuilder934** [comment]
*I* signed the CLA but imgbot hasn't. lemme see if I can get it to recognize me as the rightful owner of the commit, give me a bit

**Pull request closed without merging**
