### PR TITLE
Improve raider entity spawn position

### PR DESCRIPTION
**Pull request by someaddons**
Closes #
Closes #
Closes #

# Changes proposed in this pull request:
- Improve raider entity spawn position
- Fix dimensions of a few textures

[ x] Yes I tested this before submitting it.
[x ] I also did a multiplayer test.

Review please

### CODE REVIEW

**Review by Thodor12 — CHANGES_REQUESTED** [review]
Not sure it's a smart idea to modify the size of the builder_paper to 256 in height, that's going to break about every window in the mod.

**Comment by Raycoms** [comment]
> Not sure it's a smart idea to modify the size of the builder_paper to 256 in height, that's going to break about every window in the mod.

Please make sure that where it's used we properly give it a size so it can downscale and don't do just 100%

**Comment by Thodor12** [comment]
By changing the dimensions of the background, you not only have to make sure all of the windows get the new correct size, but you have to change *every, single, element* it's position relative to the new size. So that is quite a massive thing to do.

**Comment by Raycoms** [comment]
> By changing the dimensions of the background, you not only have to make sure all of the windows get the new correct size, but you have to change _every, single, element_ it's position relative to the new size. So that is quite a massive thing to do.

No no. We downscale to the size we want.

**Comment by Thodor12** [comment]
But is that not going to stretch the texture?

**Pull request merged**
