### PR TITLE
bug #1014 fix crash when a colony does not have any owner

### LINKED ISSUE #1014: colony member hungry now world crashes.
### Minecolonies version

minecolonies-universal-1.10.2-0.8.1257

### Expected behavior

trying to log in

### Actual behavior

crashes every time
http://paste.ubuntu.com/24595737/

I updated to newest versions of galacticraft, planets, microdoodle and hatchery and was able to ge into game now console is getting spammed with this.
http://paste.ubuntu.com/24596266/

### PR DESCRIPTION
**Pull request by xavierh**
Closes #1014
Review please

### CODE REVIEW

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 55 issues
* ![MAJOR][MAJOR] 14 major
* ![MINOR][MINOR] 38 minor
* ![INFO][INFO] 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/138460990cc7601790186a8870f9b50c18d1e5fb/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.280 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L64](https://github.com/Minecolonies/minecolonies/blob/138460990cc7601790186a8870f9b50c18d1e5fb/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L64): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 58 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L64](https://github.com/Minecolonies/minecolonies/blob/138460990cc7601790186a8870f9b50c18d1e5fb/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L64): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L351](https://github.com/Minecolonies/minecolonies/blob/138460990cc7601790186a8870f9b50c18d1e5fb/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L351): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L352](https://github.com/Minecolonies/minecolonies/blob/138460990cc7601790186a8870f9b50c18d1e5fb/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L352): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L352](https://github.com/Minecolonies/minecolonies/blob/138460990cc7601790186a8870f9b50c18d1e5fb/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L352): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/138460990cc7601790186a8870f9b50c18d1e5fb/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/138460990cc7601790186a8870f9b50c18d1e5fb/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 6.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L383](https://github.com/Minecolonies/minecolonies/blob/138460990cc7601790186a8870f9b50c18d1e5fb/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L383): Assign this magic number 3 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L596](https://github.com/Minecolonies/minecolonies/blob/138460990cc7601790186a8870f9b50c18d1e5fb/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L596): Refactor this method to reduce its Cognitive Complexity from 25 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by marvin-bitterlich** [comment]
:shipit:

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1016/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 55 issues
* ![MAJOR][MAJOR] 14 major
* ![MINOR][MINOR] 38 minor
* ![INFO][INFO] 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/2e77a2abf203fce76489ed2990e97b09b6bcdc32/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.276 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L64](https://github.com/Minecolonies/minecolonies/blob/2e77a2abf203fce76489ed2990e97b09b6bcdc32/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L64): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 58 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L64](https://github.com/Minecolonies/minecolonies/blob/2e77a2abf203fce76489ed2990e97b09b6bcdc32/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L64): class "EntityCitizen" has 93 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L351](https://github.com/Minecolonies/minecolonies/blob/2e77a2abf203fce76489ed2990e97b09b6bcdc32/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L351): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L352](https://github.com/Minecolonies/minecolonies/blob/2e77a2abf203fce76489ed2990e97b09b6bcdc32/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L352): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L352](https://github.com/Minecolonies/minecolonies/blob/2e77a2abf203fce76489ed2990e97b09b6bcdc32/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L352): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/2e77a2abf203fce76489ed2990e97b09b6bcdc32/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L354](https://github.com/Minecolonies/minecolonies/blob/2e77a2abf203fce76489ed2990e97b09b6bcdc32/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L354): Assign this magic number 6.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L383](https://github.com/Minecolonies/minecolonies/blob/2e77a2abf203fce76489ed2990e97b09b6bcdc32/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L383): Assign this magic number 3 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L596](https://github.com/Minecolonies/minecolonies/blob/2e77a2abf203fce76489ed2990e97b09b6bcdc32/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L596): Refactor this method to reduce its Cognitive Complexity from 25 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1016/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by marvin-bitterlich** [comment]
:shipit:

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1016/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Pull request merged**
