### PR TITLE
1.16/bump structurize

### PR DESCRIPTION
**Pull request by Nightenom**
_Feel free to link close issues_

# Changes proposed in this pull request:
- bump gradle and structurize, mod.toml
- strengthen generic pager [(commit)](https://github.com/ldtteam/minecolonies/commit/ec92fd1d4ecc2dbd22631694708e28c3ea0bde64#diff-be71109b2c2bb2c23f71da316fa6d3571cfbe95ad324dab070221e3d2c200211L143)
- text/tooltip builder examples [(commit)](https://github.com/ldtteam/minecolonies/commit/9a7630694d83820961a88b4c00c269572438d764) (you have to put the pane into window before building tooltip)
- reworked/adjusted some guis due to textscale being a bit problematic  [(commit)](https://github.com/ldtteam/minecolonies/commit/43d44adc43b118660fc445b094a579faff59d05a)
- bug hunting, please check! [(commit)](https://github.com/ldtteam/minecolonies/commit/a7c1e7cdac4479809938feba43fa97c33261d7d6)

Review please

### CODE REVIEW

**Review by ravenbuilder934 — CHANGES_REQUESTED** [review]
You set the bumped structurize version to 126 but the latest is 129

**Comment by Nightenom** [comment]
> You set the bumped structurize version to 126 but the latest is 129

You don't say 🙃, I have local version, that's why this is draft

**Review by ravenbuilder934 — COMMENTED** [review]
Why'd you add `megatile.png` and `megatile_light.png`? As far as I can tell, they aren't called anywhere, and just add to the file size

**Comment by Nightenom** [comment]
> Why'd you add `megatile.png` and `megatile_light.png`? As far as I can tell, they aren't called anywhere, and just add to the file size

@gattsuru use them (either dark or light) as the research background, size is `w|h = 83 + 50 * x | 84 + 50 * y` where x,y are independent integers
`<imagerepeat source="minecolonies:textures/gui/megatile.png" textureoffset="0 0" texturesize="133 134" repeatoffset="40 40" repeatsize="50 50" />`

**Pull request merged**
