### PR TITLE
Add fallback for mods that hate server-side creative tabs

### LINKED ISSUE #9008: [BUG] CompatibilityManager#discoverAllItems is being called on server side
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19.3

### MineColonies Version

1.0.1275-ALPHA

### Structurize Version

1.0.484-ALPHA

### Related Mods and their Versions

1. Forge Version: 44.1.21
2. Create Version: 1.19.3 0.5.0j

### Current Behavior

`CompatibilityManager#discoverAllItems` is getting called on the server side by `DataPackSyncEventHandler$ServerEvents#loadRecipes` which causes crashes when other mods run client side only code to build their creative mode tabs. The specific incompatibility is with Create.

### Expected Behavior

`CompatibilityManager#discoverAllItems` not be called on the server side.

### Reproduction Steps

1. Install Create & MineColonies
2. Run server

### Logs

https://gist.github.com/Ackar77/9121a3c738ff8e658bc40d2a7c07f35a

### Anything else?

The issue on Create's repo Creators-Of-Create/Create#4545

### PR DESCRIPTION
**Pull request by uecasm**
Closes #9008

# Changes proposed in this pull request:
- Adds workaround for mods that don't implement `fillItemCategory` on server-side properly.  Ideally still needs to be fixed on their side though for proper functionality.

Review please (could backport)

I have not tested this with Create, but I expect that it will work around the issue (somewhat) until they fix it on their side.

### CODE REVIEW

**Comment by Ackar77** [comment]
Still fails to work with create on server-side. (using minecolonies 1.19.3-1.0.1298-ALPHA with create 1.19.3-0.5.0.j-2)

**Comment by MotionlessTrain** [comment]
This PR has never been ported to 1.19.3/1.19.4

**Comment by Raycoms** [comment]
Ported to 1.19.4.

**Comment by Ackar77** [comment]
Please port to 1.19.3 if possible?

**Comment by Thodor12** [comment]
With the release of 1.19.4, 1.19.3 support has been dropped. You may be lucky but I wouldn't count on it being ported anymore.

**Comment by MotionlessTrain** [comment]
The 1.19.4 version of minecolonies has not been released just yet, so we are technically still supporting 1.19.3 at the moment
(I'm not sure when it will drop though, very likely very soon)

**Pull request merged**
