### PR TITLE
Guards not wearing Mekanism armors anymore  #2670

### LINKED ISSUE #2670: Guards not wearing Mekanism armors anymore
forge-1.12.2-14.23.4.2739-universal.jar
minecolonies-1.12.2-0.9.37-ALPHA-universal.jar

This is happening since a few releases ago.

### PR DESCRIPTION
**Pull request by bob0bob**
Ok. I've added a LEVEL system for the armors. Now armor are not requested by type. They have a range instead of an request of an item. The async request will go out with the range for items. This should allow any type of armor be able to be used. Only requirement is that they inherit from ItemArmor at some point. The code will check to see if that is an instance and then if the material type and equipment type are set using the standard enum values. MC will be happy using those items.

Closes #2670
Closes #
Closes #

# Changes proposed in this pull request:
-
-
-

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/2706/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Review by marchermans — COMMENTED** [review]
Isn't there a ArmorType class?

**Comment by Raycoms** [comment]
I think there is none, only the armor slot.

2018-07-29 18:04 GMT-03:00 Marc Hermans <notifications@github.com>:

**Comment by bob0bob** [comment]
No armortype class.

There is only an enum for armortype  just like material for armor.  There is only one class ItemArmor its used for EVERY type of armor.  You pass in the type of armor it is.

**Review by LDTTeam-Buildsystem — APPROVED** [review]
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  | 39044 |  2  |  4  |  -2  |
| Errors |  592  |  0  |  0  |  0   |
##### More Information:
- [Analysis - Full](https://teamcity.minecolonies.com/viewLog.html?buildId=14373&tab=Inspection&buildTypeId=bt88)

**Review by LDTTeam-Buildsystem — APPROVED** [review]
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  | 39044 |  2  |  4  |  -2  |
| Errors |  592  |  0  |  0  |  0   |
##### More Information:
- [Analysis - Full](https://teamcity.minecolonies.com/viewLog.html?buildId=14325&tab=Inspection&buildTypeId=bt88)

**Review by LDTTeam-Buildsystem — APPROVED** [review]
#### Analysis Complete
##### Statistics
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  |  666  |  0  |  0  |  0   |
| Errors |  10   |  0  |  0  |  0   |

**Review by marchermans — APPROVED** [review]

**Pull request merged**
