### PR TITLE
Feature/improve build repair buttons

### PR DESCRIPTION
**Pull request by xavierh**
# Changes proposed in this pull request:
- Allow to cancel a repair from the hut gui
- Allow to cancel an upgrade from the hut gui

Note: 
- The Town Hall Gui do no longer display the buttons as **Build Town Hall** and **Repair Town Hall** but will use the generic **Build Building** and **Repair Building** label.

Review please

### CODE REVIEW

**Comment by xavierh** [comment]
I don't like that **requestRepair** and **requestUpgrade** method can be use to delete a work order instead.

I will take the logic outside those two methods

**Comment by Raycoms** [comment]
I like that pr =D Seems very useful!

**Comment by xavierh** [comment]
I was fed up to have to go back to the Town Hall whenever I wanted to cancel a repair of upgrade :)

**Comment by xavierh** [comment]
Not sure I I am meant to use the tag **Not ready** / **Ready**.

Anyway the pr is ready for review

**Comment by cltnschlosser** [comment]
@xavierh In general you wouldn't create a PR until it is ready, so the "ready" tag isn't needed. The "not ready" tag is used when you create a PR before it is ready, for whatever reason.

**Comment by xavierh** [comment]
I tend to do a pr. And then find things which need to be improved. Sorry
for the noise I am doing.

On 7 Feb 2017 15:57, "Colton Schlosser" <notifications@github.com> wrote:

@xavierh <https://github.com/xavierh> In general you wouldn't create a PR
until it is ready, so the "ready" tag isn't needed. The "not ready" tag is
used when you create a PR before it is ready, for whatever reason.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Minecolonies/minecolonies/pull/556#issuecomment-278043357>,
or mute the thread

**Comment by marvin-bitterlich** [comment]
:shipit: @Raycoms @cltnschlosser 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/556/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by Raycoms** [comment]
:shipit: I'm good with it.

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/556/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by xavierh** [comment]
Cheers

**Pull request merged**
