### PR TITLE
[Draft] [1.12.2] Info Tabs

### PR DESCRIPTION
**Pull request by Asherslab**
# Changes proposed in this pull request:
- Adds dynamically added information tabs to worker huts (dynamically based on lang entries)

Lang entires support newlines via \n

Review please

### CODE REVIEW

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/client/gui/WindowInfo.java  5
- src/api/java/com/minecolonies/blockout/controls/Label.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Minecolonies/minecolonies/pullRequest?prid=4627772&bid=15513346)

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/client/gui/WindowInfo.java  5
- src/api/java/com/minecolonies/blockout/controls/Label.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Minecolonies/minecolonies/pullRequest?prid=4627772&bid=15513346)

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/api/java/com/minecolonies/blockout/controls/Label.java  2
- src/main/java/com/minecolonies/coremod/client/gui/WindowInfo.java  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Minecolonies/minecolonies/pullRequest?prid=4627772&bid=15513346)

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/client/gui/WindowInfo.java  5
- src/api/java/com/minecolonies/blockout/controls/Label.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Minecolonies/minecolonies/pullRequest?prid=4627772&bid=15513346)

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/client/gui/WindowInfo.java  5
- src/api/java/com/minecolonies/blockout/controls/Label.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Minecolonies/minecolonies/pullRequest?prid=4627772&bid=15513346)

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/client/gui/WindowInfo.java  5
- src/api/java/com/minecolonies/blockout/controls/Label.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Minecolonies/minecolonies/pullRequest?prid=4627772&bid=15513346)

**Comment by marvin-bitterlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/api/java/com/minecolonies/blockout/controls/Label.java  2
- src/main/java/com/minecolonies/coremod/client/gui/WindowInfo.java  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Minecolonies/minecolonies/pullRequest?prid=4627772&bid=15513346)

**Pull request merged**
