### PR TITLE
Feature/1.10 efficient dman

### PR DESCRIPTION
**Pull request by xavierh**
# Changes proposed in this pull request:
- port from 1.11

Review please

### CODE REVIEW

**Comment by marvin-bitterlich** [comment]
:shipit: nice

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1044/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 75 issues
* ![MAJOR][MAJOR] 35 major
* ![MINOR][MINOR] 40 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuilding.java#L39](https://github.com/Minecolonies/minecolonies/blob/b74b90d599ce5ed38008fc146f4e54e5e14bfe68/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L39): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 33 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L39](https://github.com/Minecolonies/minecolonies/blob/b74b90d599ce5ed38008fc146f4e54e5e14bfe68/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L39): class "AbstractBuilding" has 69 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L162](https://github.com/Minecolonies/minecolonies/blob/b74b90d599ce5ed38008fc146f4e54e5e14bfe68/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L162): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L162](https://github.com/Minecolonies/minecolonies/blob/b74b90d599ce5ed38008fc146f4e54e5e14bfe68/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L162): Remove this reference to "BuildingBaker". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L163](https://github.com/Minecolonies/minecolonies/blob/b74b90d599ce5ed38008fc146f4e54e5e14bfe68/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L163): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L163](https://github.com/Minecolonies/minecolonies/blob/b74b90d599ce5ed38008fc146f4e54e5e14bfe68/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L163): Remove this reference to "BuildingBlacksmith". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L164](https://github.com/Minecolonies/minecolonies/blob/b74b90d599ce5ed38008fc146f4e54e5e14bfe68/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L164): Remove this reference to "BuildingBuilder". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L165](https://github.com/Minecolonies/minecolonies/blob/b74b90d599ce5ed38008fc146f4e54e5e14bfe68/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L165): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L165](https://github.com/Minecolonies/minecolonies/blob/b74b90d599ce5ed38008fc146f4e54e5e14bfe68/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L165): Remove this reference to "BuildingHome". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)
1. ![MAJOR][MAJOR] [AbstractBuilding.java#L166](https://github.com/Minecolonies/minecolonies/blob/b74b90d599ce5ed38008fc146f4e54e5e14bfe68/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuilding.java#L166): Remove this reference to "BuildingFarmer". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2390)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by marchermans** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1044/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1044/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Pull request merged**
