### PR TITLE
Added new icons for all entities

### PR DESCRIPTION
**Pull request by Sandriell**
# Changes proposed in this pull request:

- Removed existing entity icons that were unused.
- Created new icons based on existing skins.
- Optimized icons using pngoptimizer reducing sizes by 80-90%

Some examples:

archerfemale1_a deliverymanmale1_w lumberjackmale1_w archerfemale1_a planterfemale1_w norsemen_shieldmaiden1 barbarian1

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
:shipit:

**Comment by someaddons** [comment]
ah you ran some png optimizer, that explains why its soo many changed files :D
So many changes usually smells like a git issue with wrongly uploading changes

**Comment by Sandriell** [comment]
> ah you ran some png optimizer, that explains why its soo many changed files :D
> So many changes usually smells like a git issue with wrongly uploading changes

There are so many files simply because that is how many I created. I did not optimize any existing images.

Every single possible skin has to have a corresponding icon.

**Comment by Raycoms** [comment]
It's basically one icon, per entity texture.

**Comment by someaddons** [comment]
oh wow then that was a ton of work thanks for that :D

**Review by marchermans — APPROVED** [review]

**Pull request merged**
