### PR TITLE
Add breeding toggle for herders

### PR DESCRIPTION
**Pull request by ToMe25**
Closes #
Closes #
Closes #

# Changes proposed in this pull request:
- Add a Button to the second page of the cowboy, shepard and chicken herder to disable them breeding the animals.
-
Here some images:

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/5380/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Review by someaddons — COMMENTED** [review]
looks nice, could you add that turning off breeding also does turn off random sheep dying? Since that won't work when breeding is off

**Comment by ToMe25** [comment]
I don't think thats a good idea, as it would either keep it turned off for when you re enable breeding, or would have to additionally store the old value, just to set it back as soon as breeding gets turned back on.
As long as this doesn't cause any issues i would leave the dying in the state it is when disabling breeding.

**Comment by ToMe25** [comment]
If this does however cause any problems it might be worth it to temporarily disable random dying while breeding is disabled, tho i would still probably look at whether there is a easier solution for whatever problems it might cause.

**Comment by someaddons** [comment]
well as is now a user could expect to have breeding off and random dying on

**Comment by MatthiasMann** [comment]
Just gray out the UI button to indicate that this switch has no effect while breeding is disabled?

**Review by someaddons — APPROVED** [review]
Its fine, dying happens on shearing not breeding

**Comment by ToMe25** [comment]
But random dying works while he isn't breeding them...
It just doesn't make much sense, but thats the players problem xD

**Pull request merged**
