### PR TITLE
Added new icons for all entities

### PR DESCRIPTION
**Pull request by Sandriell**
# Changes proposed in this pull request:

Created and added in new icons for all entities. Also removed the existing, unused entity icons in the base "entity_icon" folder.

Review please

### CODE REVIEW

**Comment by marchermans** [comment]
Thanks for your PR.

But as I can not see your changes on github, could you expand your PR message with all images, removed, added and or replaced with new ones?

**Comment by marchermans** [comment]
Oeps

**Comment by Sandriell** [comment]
Why can't you see the files on github? If I did the commit wrong, could you tell me how to properly do it?

**Comment by someaddons** [comment]
github doesnt display picture differences, so its not possible to tell what changed for which pictures, so an overview over that so we can estimate it would be nice

**Comment by Sandriell** [comment]
Oh! Gotchya.

How about this:

Deleted files: https://gist.github.com/Sandriell/399f38ff074415562b919b117384d6e4
(ignore the output.txt, that's just the file I used to make the list)

Added filed: https://gist.github.com/Sandriell/fdad3317a1bfa5ab795059f83d441c76

**Comment by ravenbuilder934** [comment]
It's not that, we can see the file name differences fine
We need to see the actual *pictures*

**Comment by Sandriell** [comment]
Closing this because I decided to tweak the icons slightly. Will create a new pull request when done and will include example images.

**Pull request closed without merging**
