### PR TITLE
HotFix 1.11 Fix null error exception in AbstractEntityAIBasic

### PR DESCRIPTION
**Pull request by xavierh**
`java.lang.NullPointerException
        at com.minecolonies.coremod.util.InventoryUtils.isItemStackEmpty(InventoryUtils.java:126) ~[InventoryUtils.class:?]
        at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic.shouldDumpItem(AbstractEntityAIBasic.java:1040) ~[AbstractEntityAIBasic.class:?]
        at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic.lambda$dumpOneMoreSlot$17(AbstractEntityAIBasic.java:1013) ~[AbstractEntityAIBasic.class:?]
`

# Changes proposed in this pull request:
- handleKeepX return InventoryUtils.EMPTY instead of null

Review please

### CODE REVIEW

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 48 issues
* ![MAJOR][MAJOR] 5 major
* ![MINOR][MINOR] 43 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java](https://github.com/Minecolonies/minecolonies/blob/1d9996b1601fbdeb227924eecac0ac1facd85a9c/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java): This file has 774 lines, which is greater than 750 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L36](https://github.com/Minecolonies/minecolonies/blob/1d9996b1601fbdeb227924eecac0ac1facd85a9c/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L36): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 25 to the maximum authorized 20 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L36](https://github.com/Minecolonies/minecolonies/blob/1d9996b1601fbdeb227924eecac0ac1facd85a9c/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L36): class "AbstractEntityAIBasic" has 61 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L200](https://github.com/Minecolonies/minecolonies/blob/1d9996b1601fbdeb227924eecac0ac1facd85a9c/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L200): Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1278](https://github.com/Minecolonies/minecolonies/blob/1d9996b1601fbdeb227924eecac0ac1facd85a9c/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1278): Merge this if statement with the enclosing one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1066)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/1d9996b1601fbdeb227924eecac0ac1facd85a9c/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/1d9996b1601fbdeb227924eecac0ac1facd85a9c/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/1d9996b1601fbdeb227924eecac0ac1facd85a9c/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/1d9996b1601fbdeb227924eecac0ac1facd85a9c/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/1d9996b1601fbdeb227924eecac0ac1facd85a9c/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

**Review by marchermans — APPROVED** [review]
Yep missed that one in the Port.
Thanks for Fixing @xavierh

**Comment by marchermans** [comment]
:shipit:

**Comment by marvin-bitterlich** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/929/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 48 issues
* ![MAJOR][MAJOR] 5 major
* ![MINOR][MINOR] 43 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java](https://github.com/Minecolonies/minecolonies/blob/cc62a8fcf80819bf309a58698d251762a6e28b87/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java): This file has 774 lines, which is greater than 750 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L36](https://github.com/Minecolonies/minecolonies/blob/cc62a8fcf80819bf309a58698d251762a6e28b87/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L36): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 25 to the maximum authorized 20 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L36](https://github.com/Minecolonies/minecolonies/blob/cc62a8fcf80819bf309a58698d251762a6e28b87/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L36): class "AbstractEntityAIBasic" has 61 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L200](https://github.com/Minecolonies/minecolonies/blob/cc62a8fcf80819bf309a58698d251762a6e28b87/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L200): Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1278](https://github.com/Minecolonies/minecolonies/blob/cc62a8fcf80819bf309a58698d251762a6e28b87/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1278): Merge this if statement with the enclosing one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1066)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/cc62a8fcf80819bf309a58698d251762a6e28b87/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/cc62a8fcf80819bf309a58698d251762a6e28b87/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/cc62a8fcf80819bf309a58698d251762a6e28b87/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/cc62a8fcf80819bf309a58698d251762a6e28b87/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/cc62a8fcf80819bf309a58698d251762a6e28b87/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

**Comment by xavierh** [comment]
@oriononline is it in 1.10 already then?

**Comment by marchermans** [comment]
@xavierh this was never an issue in 1.10. Itemstacks were always null there, so when you returned it would be equal to InventoryUtils.EMTPY.
In 1.11 InventoryUtils.EMPTY is set to ItemStack.EMPTY.

Which causes the crash when I returned null in one of the methods.

**Comment by xavierh** [comment]
@OrionDevelopment I know, in 1.10 we check if its null or not but for consitancy I propose https://github.com/Minecolonies/minecolonies/pull/931

**Pull request merged**
