### PR TITLE
Guards Request Armor  #2577

### PR DESCRIPTION
**Pull request by bob0bob**
tweaked the armor request to be building level/guard level on what armor is required.

build lvl 1
leather/golden

build lvl 2
golden/chain

build lvl3 
chain/iron

build lvl4
iron/diamond

build lvl5
diamond

### CODE REVIEW

**Review by LDTTeam-Buildsystem — DISMISSED** [review]
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  |   0   |  0  |  0  |  0   |
| Errors |   0   |  0  |  0  |  0   |
##### More Information:

**Review by LDTTeam-Buildsystem — DISMISSED** [review]
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  |   0   |  0  |  0  |  0   |
| Errors |   0   |  0  |  0  |  0   |
##### More Information:

**Comment by bob0bob** [comment]
I just checked in one file.  It is showing 18 files changed.   This is not correct.  Can I delete this and try again.  One github it only shows one file changed.  But when I did pull request from my branch to 1.12.  it pulled in 18.  How can you select on a pull request from one branch to another which files you wish to bring over?

**Review by LDTTeam-Buildsystem — DISMISSED** [review]
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  |   0   |  0  |  0  |  0   |
| Errors |   0   |  0  |  0  |  0   |
##### More Information:

**Review by LDTTeam-Buildsystem — DISMISSED** [review]
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  |   0   |  0  |  0  |  0   |
| Errors |   0   |  0  |  0  |  0   |
##### More Information:

**Comment by bob0bob** [comment]
fix for Guards - standing around like crash dummies. #2610

**Comment by bob0bob** [comment]
formatting changes.

**Review by LDTTeam-Buildsystem — DISMISSED** [review]
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  |   0   |  0  |  0  |  0   |
| Errors |   0   |  0  |  0  |  0   |
##### More Information:

**Review by marchermans — CHANGES_REQUESTED** [review]
Please rebuild this PR. You are merging several features in one PR. These PRs will not be accepted this way.

**Comment by bob0bob** [comment]
OrionDevelopment .   I've been asking how to do this for a week and one answers me.  When I do a pull request from my branch,  it automatically pulls in all files altered and I can't find anything where you can select files.  You can't have more than one OPEN PR merging from a different branch.  When you try to do a second bug, and there is NO "CREATE A NEW PR"   it just says see open PR.    I don't know if it is privileges or not.

Let me know,  the only other thing is stop submitting changes.   I'm frustrated as I've been asking for help for a long time and one answers me.

**Comment by bob0bob** [comment]
As you can see from the screen shot.  I do not have the option of creating more than one PR at a time.  Only thing I can think is wait until the first one is approved before beginning the second one.  If you have something else let me know.

image

**Comment by Raycoms** [comment]
Don't you have this?

2018-07-11 9:33 GMT-03:00 bob0bob <notifications@github.com>:

**Comment by marchermans** [comment]
The problem is not with git. The problem is that you make multiple changes in one branch. Make a new branch for each thing you solve. By simply selecting version/1.12 and creating a new branch from it.

**Comment by bob0bob** [comment]
OrionDevelopment , so each bug fix needs a new branch?  Just checking.

I've been programming for 30+ years and used many version control software and this is the first to not be able to select which files you want to merge.

I'm not trying to be difficult.   Thanks.

Ill think about it, but setting up a new build environment for each and every bug fix is not something I really want to do.

Thanks for your time.

**Comment by marchermans** [comment]
Git basically treats all files as binary blobs. It only cares about differences between states. So from one commit to the next. It does not care about files or directories for it that is just binary data that it can manipulate, nothing more. That is why it is so good when it comes to merging and why it runs into so few issues when conflicts arise.

But yeah one change per branch is our policy. Git does not enforce it, as said git only knows the 1 and 0 that make up the file nothing else. For us it is just simpler during review if we only have one feature to worry about.

**Comment by marchermans** [comment]
Also you do not need to setup a new environment every time. Simply switching a the branch is enough. It will not delete your eclipse/idea data or even your gradle caches so you can just keep on going once you switched, as long as you have all your changes committed and no uncommitted changes are present in the repo, git does not care neither does any ide or gradle. Simply switch the branch and you are good to go.

Of course this only flies if no dependencies have changed.

**Comment by Raycoms** [comment]
You just open a separate branch in your environment.

2018-07-11 11:00 GMT-03:00 Marc Hermans <notifications@github.com>:

**Review by LDTTeam-Buildsystem — DISMISSED** [review]
#### Analysis Complete
##### Statistics:
|        | Count | New  | Old  | Diff |
| ------ |:-----:|:----:|:----:|:----:|
| Total  | 33962 | 3549 | 2671 | +878 |
| Errors |  591  |  24  |  17  |  +7  |
##### More Information:
- [Analysis - Full](https://teamcity.minecolonies.com/viewLog.html?buildId=11269&tab=Inspection&buildTypeId=bt88)

**Comment by bob0bob** [comment]
Closed this PR.  To many things ended up combining into one PR.  Split all them into their own PR. This one is not needed anymore.

**Pull request closed without merging**
