### PR TITLE
XP Changes Port 1.11

### PR DESCRIPTION
**Pull request by ghost**
A port for the XP Changes I made to version 1.11

### CODE REVIEW

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 58 issues
* ![MAJOR][MAJOR] 23 major
* ![MINOR][MINOR] 32 minor
* ![INFO][INFO] 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/c2f57113472f6ad961d7d0e7511edb74d0f249da/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.311 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L72](https://github.com/Minecolonies/minecolonies/blob/c2f57113472f6ad961d7d0e7511edb74d0f249da/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L72): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 57 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L72](https://github.com/Minecolonies/minecolonies/blob/c2f57113472f6ad961d7d0e7511edb74d0f249da/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L72): class "EntityCitizen" has 95 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L353](https://github.com/Minecolonies/minecolonies/blob/c2f57113472f6ad961d7d0e7511edb74d0f249da/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L353): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L355](https://github.com/Minecolonies/minecolonies/blob/c2f57113472f6ad961d7d0e7511edb74d0f249da/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L355): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L356](https://github.com/Minecolonies/minecolonies/blob/c2f57113472f6ad961d7d0e7511edb74d0f249da/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L356): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L357](https://github.com/Minecolonies/minecolonies/blob/c2f57113472f6ad961d7d0e7511edb74d0f249da/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L357): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L359](https://github.com/Minecolonies/minecolonies/blob/c2f57113472f6ad961d7d0e7511edb74d0f249da/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L359): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L359](https://github.com/Minecolonies/minecolonies/blob/c2f57113472f6ad961d7d0e7511edb74d0f249da/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L359): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L360](https://github.com/Minecolonies/minecolonies/blob/c2f57113472f6ad961d7d0e7511edb74d0f249da/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L360): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Asherslab** [comment]
Also looks good :shipit: @OrionDevelopment @Raycoms 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1333/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Review by marchermans — APPROVED** [review]

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1333/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 58 issues
* ![MAJOR][MAJOR] 23 major
* ![MINOR][MINOR] 32 minor
* ![INFO][INFO] 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/69ef867c98ae8fc3f23e438d201999683a45b932/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.317 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L73](https://github.com/Minecolonies/minecolonies/blob/69ef867c98ae8fc3f23e438d201999683a45b932/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L73): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 57 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L73](https://github.com/Minecolonies/minecolonies/blob/69ef867c98ae8fc3f23e438d201999683a45b932/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L73): class "EntityCitizen" has 95 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L359](https://github.com/Minecolonies/minecolonies/blob/69ef867c98ae8fc3f23e438d201999683a45b932/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L359): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L361](https://github.com/Minecolonies/minecolonies/blob/69ef867c98ae8fc3f23e438d201999683a45b932/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L361): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L362](https://github.com/Minecolonies/minecolonies/blob/69ef867c98ae8fc3f23e438d201999683a45b932/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L362): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L363](https://github.com/Minecolonies/minecolonies/blob/69ef867c98ae8fc3f23e438d201999683a45b932/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L363): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L365](https://github.com/Minecolonies/minecolonies/blob/69ef867c98ae8fc3f23e438d201999683a45b932/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L365): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L365](https://github.com/Minecolonies/minecolonies/blob/69ef867c98ae8fc3f23e438d201999683a45b932/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L365): Extract this increment or decrement operator into a dedicated statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS881)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L366](https://github.com/Minecolonies/minecolonies/blob/69ef867c98ae8fc3f23e438d201999683a45b932/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L366): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
