### PR TITLE
Updated ru_RU.lang and item models

### PR DESCRIPTION
**Pull request by kraineff**
- Updated Russian translate for new versions.
- Updated item models.
- Added missing strings.

### CODE REVIEW

**Comment by Raycoms** [comment]
What do these changes of the models change?

**Comment by marvin-bitterlich** [comment]
@xMrVizzy can you elaborate what you changed and why?

**Comment by kraineff** [comment]
Yeah, i've change bultin/ to item/ in model .json file. It used in new minecraft version for correct item render!

**Comment by marvin-bitterlich** [comment]
@xMrVizzy can you extract the language file changes? We manage them with an external tool and they will be gone with the next translation update

**Comment by kraineff** [comment]
Like a changelog?

**Comment by marvin-bitterlich** [comment]
@xMrVizzy I'd say remove them and ask @Raycoms to give you access to our translation tool, so you can add them there

**Comment by kraineff** [comment]
"I'd say remove them and ask @Raycoms to give you access to our translation tool, so you can add them there", i'm not understand sorry what i need remove and @Raycoms is there in PR.

**Comment by kraineff** [comment]
It's a hard, can you just merge or give me access to push, i'm update translate on github so many popular mods and, you can trust me.

**Comment by marvin-bitterlich** [comment]
@xMrVizzy Thing is, they will be gone once we update them again. look for example at #333 that will override your pr

**Comment by Raycoms** [comment]
:shipit: I'd say @xMrVizzy you take a look at the link I've sent you. We already have some Russian translations there. But it would be nice if you could look and correct them if necessary.
We can push that for now I guess.

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/377/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by kraineff** [comment]
Yes, i fixed it in this commit. Do i need update it on site?

**Comment by kraineff** [comment]
How can i import all my new translate in this file on POEditor, when i import in format .propertes it imort only 95 string and update some.

**Comment by Raycoms** [comment]
You have to make one space before and after the " = " to import it.

2016-12-28 7:36 GMT-02:00 Alexey Krainev <notifications@github.com>:

**Comment by kraineff** [comment]
Yes, i make it, but it doesn't work for all strings, can you import for me please :)

**Comment by Raycoms** [comment]
I think it would be better if you look at the current translations and
compare them with yours. Sometimes the other translator (also russian)
found a better matching translation.

2016-12-28 11:09 GMT-02:00 Alexey Krainev <notifications@github.com>:

**Comment by kraineff** [comment]
Yes, i know it, but in my translate i'm using latest translate of translators, and change many strings because it was bad :(

**Comment by kraineff** [comment]
@Raycoms please!!!

**Pull request merged**
