### PR TITLE
Fix builder not seeing the new air types as air

### LINKED ISSUE #4795: Builder breaks cave air
### Minecolonies version
Version: 0.11.893

### Expected behavior
I expected the builder to ignore the new Cave Air block just like regular air and continue breaking blocks.

### Actual behaviour
If the miner encounters Cave Air in a place where he is meant to build something he will at the start in the block breaking phase break the cave air, which doesn't make that much sense.

### Steps to reproduce the problem

1. Go into a cave
2. create a build job
3. hope that this cave is actually filled with cave air, and not regular air
4. see the builder breaking air

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

### PR DESCRIPTION
**Pull request by ToMe25**
Closes #4795
Closes #
Closes #

# Changes proposed in this pull request:
- Fix the builders handling of the new air types
-
-

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
Was doing this concurrently: https://github.com/ldtteam/minecolonies/pull/4798
But I think the instanceof AirBlock is probably more generic

**Comment by ToMe25** [comment]
ok seems like Raycomms is doing this but everywhere, closing this then.

**Comment by Raycoms** [comment]
I was about to look into the builder water issues. If you want you can take that over?

**Comment by ToMe25** [comment]
I don't know how to correctly handle water as it has to get removed somehow, but not like this, so no.

**Pull request closed without merging**
