### PR TITLE
1.10-Rewrite handleKeepX to be identical than release/1.11

### PR DESCRIPTION
**Pull request by xavierh**
# Changes proposed in this pull request:
- handleKeepX return Empty instead of null
- package info

Review please

### CODE REVIEW

**Comment by xavierh** [comment]
@OrionDevelopment Could you have a look at this?

Trying to be consistent between  1.10 and 1.11.
Build but not tested

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 48 issues
* ![MAJOR][MAJOR] 5 major
* ![MINOR][MINOR] 43 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java](https://github.com/Minecolonies/minecolonies/blob/5eb49933065fcbe9e815d1cf31cc88eef918419e/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java): This file has 787 lines, which is greater than 750 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L37](https://github.com/Minecolonies/minecolonies/blob/5eb49933065fcbe9e815d1cf31cc88eef918419e/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L37): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 25 to the maximum authorized 20 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L37](https://github.com/Minecolonies/minecolonies/blob/5eb49933065fcbe9e815d1cf31cc88eef918419e/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L37): class "AbstractEntityAIBasic" has 62 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L195](https://github.com/Minecolonies/minecolonies/blob/5eb49933065fcbe9e815d1cf31cc88eef918419e/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L195): Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MAJOR][MAJOR] [AbstractEntityAIBasic.java#L1163](https://github.com/Minecolonies/minecolonies/blob/5eb49933065fcbe9e815d1cf31cc88eef918419e/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIBasic.java#L1163): Provide multiple methods instead of using "useItemDamage" to determine which action to take. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2301)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/5eb49933065fcbe9e815d1cf31cc88eef918419e/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/5eb49933065fcbe9e815d1cf31cc88eef918419e/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/5eb49933065fcbe9e815d1cf31cc88eef918419e/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/5eb49933065fcbe9e815d1cf31cc88eef918419e/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/5eb49933065fcbe9e815d1cf31cc88eef918419e/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

**Comment by marvin-bitterlich** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/931/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Review by marvin-bitterlich — APPROVED** [review]

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/931/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Pull request merged**
