### PR TITLE
EntityAiWorkShepherd: Fix deprecation warning for getEnchantmentLevel

### PR DESCRIPTION
**Pull request by niekschoemaker**
# Changes proposed in this pull request:
- Fixed deprecation warning for EnchantmentHelper.getEnchantmentLevel

Review please

### CODE REVIEW

**Comment by niekschoemaker** [comment]
Pretty minor change, but noticed this, so might as well fix it before it breaks something

**Comment by marchermans** [comment]
@niekschoemaker Please sign the CLA as requested. And update this PR.

**Comment by niekschoemaker** [comment]
> @niekschoemaker Please sign the CLA as requested. And update this PR.

Yes done, missed that comment.

I also see that the build task failed, but it appears this is due to the build task running under 1.18

**Comment by MotionlessTrain** [comment]
Version/main is the 1.18.2 branch, and the build tasks seemed to be using for forge 1.18.2

**Review by someaddons — APPROVED** [review]

**Pull request merged**
