### PR TITLE
Sapplings switching not saved correctly #2669

### PR DESCRIPTION
**Pull request by bob0bob**
The check if sapling exist is missing.   I couldn't locate missing saving from the game.

### CODE REVIEW

**Comment by marchermans** [comment]
How was this bug exactly caused?

**Review by LDTTeam-Buildsystem — DISMISSED** [review]
#### Analysis Complete
##### Statistics:
|        | Count | New  | Old  | Diff  |
| ------ |:-----:|:----:|:----:|:-----:|
| Total  | 34106 | 4109 | 3087 | +1022 |
| Errors |  592  |  26  |  18  |  +8   |
##### More Information:
- [Analysis - Full](https://teamcity.minecolonies.com/viewLog.html?buildId=13206&tab=Inspection&buildTypeId=bt88)

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/2676/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by Raycoms** [comment]
@OrionDevelopment can be caused by mods being removed by the player I guess

**Review by LDTTeam-Buildsystem — DISMISSED** [review]
#### Analysis Complete
##### Statistics:
|        | Count | New | Old | Diff |
| ------ |:-----:|:---:|:---:|:----:|
| Total  |   0   |  0  |  0  |  0   |
| Errors |   0   |  0  |  0  |  0   |
##### More Information:

**Comment by marchermans** [comment]
PLEASE UPDATE PR BY REMOVING THE SOUND COMMIT FROM @Nightenom

**Review by LDTTeam-Buildsystem — APPROVED** [review]
#### Analysis Complete
##### Statistics:
|        | Count | New  | Old  | Diff  |
| ------ |:-----:|:----:|:----:|:-----:|
| Total  | 38229 | 9807 | 5684 | +4123 |
| Errors |  592  |  0   |  0   |  +0   |
##### More Information:
- [Analysis - Full](https://teamcity.minecolonies.com/viewLog.html?buildId=13637&tab=Inspection&buildTypeId=bt88)

**Comment by bob0bob** [comment]
@OrionDevelopment   Not sure what you mean.  Remove Commit.  HOW??? You said update PR to do this.  Not sure what this mean.  I didn't locate a way to do this

**Pull request merged**
