### PR TITLE
More blocks

### LINKED ISSUE #1873: Implement new Shingle variation
Until now we have only the oak shingle variation.
What we need:

Implement all shingle variations with the models and textures we have.

What needs to be done:
- Create block and blockStates as well as recipe for those blocks.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #1873

# Changes proposed in this pull request:
- Implements the shingle block, fixes the item and other models
- Adds recipe

Review please

### CODE REVIEW

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 42 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 40 minor
* ![INFO][INFO] 1 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [ClientProxy.java#L135](https://github.com/Minecolonies/minecolonies/blob/eee1fc8e642f031d92dced06e693f9813c82daf0/src/main/java/com/minecolonies/coremod/proxy/ClientProxy.java#L135): This method has 102 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS138)
1. ![MINOR][MINOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/eee1fc8e642f031d92dced06e693f9813c82daf0/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [BlockShingle.java#](https://github.com/Minecolonies/minecolonies/blob/eee1fc8e642f031d92dced06e693f9813c82daf0/src/main/java/com/minecolonies/coremod/blocks/BlockShingle.java#): Add a new line at the end of this file. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00113)
1. ![MINOR][MINOR] [ModBlocks.java#](https://github.com/Minecolonies/minecolonies/blob/eee1fc8e642f031d92dced06e693f9813c82daf0/src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java#): Add a new line at the end of this file. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00113)
1. ![MINOR][MINOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/eee1fc8e642f031d92dced06e693f9813c82daf0/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render#](https://github.com/Minecolonies/minecolonies/blob/eee1fc8e642f031d92dced06e693f9813c82daf0/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony#](https://github.com/Minecolonies/minecolonies/blob/eee1fc8e642f031d92dced06e693f9813c82daf0/src/main/java/com/minecolonies/coremod/colony#): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings#](https://github.com/Minecolonies/minecolonies/blob/eee1fc8e642f031d92dced06e693f9813c82daf0/src/main/java/com/minecolonies/coremod/colony/buildings#): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions#](https://github.com/Minecolonies/minecolonies/blob/eee1fc8e642f031d92dced06e693f9813c82daf0/src/main/java/com/minecolonies/coremod/colony/permissions#): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [init#](https://github.com/Minecolonies/minecolonies/blob/eee1fc8e642f031d92dced06e693f9813c82daf0/src/main/java/com/minecolonies/coremod/colony/requestsystem/init#): Add a 'package-info.java' file to document the 'init' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 41 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 39 minor
* ![INFO][INFO] 1 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [ClientProxy.java#L135](https://github.com/Minecolonies/minecolonies/blob/9f71b091754efdc32175f8c8f9dfefcd98f91bb3/src/main/java/com/minecolonies/coremod/proxy/ClientProxy.java#L135): This method has 102 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS138)
1. ![MINOR][MINOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/9f71b091754efdc32175f8c8f9dfefcd98f91bb3/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [ModBlocks.java#](https://github.com/Minecolonies/minecolonies/blob/9f71b091754efdc32175f8c8f9dfefcd98f91bb3/src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java#): Add a new line at the end of this file. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00113)
1. ![MINOR][MINOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/9f71b091754efdc32175f8c8f9dfefcd98f91bb3/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render#](https://github.com/Minecolonies/minecolonies/blob/9f71b091754efdc32175f8c8f9dfefcd98f91bb3/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony#](https://github.com/Minecolonies/minecolonies/blob/9f71b091754efdc32175f8c8f9dfefcd98f91bb3/src/main/java/com/minecolonies/coremod/colony#): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings#](https://github.com/Minecolonies/minecolonies/blob/9f71b091754efdc32175f8c8f9dfefcd98f91bb3/src/main/java/com/minecolonies/coremod/colony/buildings#): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions#](https://github.com/Minecolonies/minecolonies/blob/9f71b091754efdc32175f8c8f9dfefcd98f91bb3/src/main/java/com/minecolonies/coremod/colony/permissions#): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [init#](https://github.com/Minecolonies/minecolonies/blob/9f71b091754efdc32175f8c8f9dfefcd98f91bb3/src/main/java/com/minecolonies/coremod/colony/requestsystem/init#): Add a 'package-info.java' file to document the 'init' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [locations#](https://github.com/Minecolonies/minecolonies/blob/9f71b091754efdc32175f8c8f9dfefcd98f91bb3/src/main/java/com/minecolonies/coremod/colony/requestsystem/locations#): Add a 'package-info.java' file to document the 'locations' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Review by marchermans — APPROVED** [review]
This looks good for now.

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 41 issues
* ![MAJOR][MAJOR] 1 major
* ![MINOR][MINOR] 39 minor
* ![INFO][INFO] 1 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [ClientProxy.java#L135](https://github.com/Minecolonies/minecolonies/blob/6f14e84023824fab504f1a9be8791e9d4bf79453/src/main/java/com/minecolonies/coremod/proxy/ClientProxy.java#L135): This method has 102 lines, which is greater than the 100 lines authorized. Split it into smaller methods. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS138)
1. ![MINOR][MINOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/6f14e84023824fab504f1a9be8791e9d4bf79453/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [ModBlocks.java#](https://github.com/Minecolonies/minecolonies/blob/6f14e84023824fab504f1a9be8791e9d4bf79453/src/main/java/com/minecolonies/coremod/blocks/ModBlocks.java#): Add a new line at the end of this file. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00113)
1. ![MINOR][MINOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/6f14e84023824fab504f1a9be8791e9d4bf79453/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render#](https://github.com/Minecolonies/minecolonies/blob/6f14e84023824fab504f1a9be8791e9d4bf79453/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony#](https://github.com/Minecolonies/minecolonies/blob/6f14e84023824fab504f1a9be8791e9d4bf79453/src/main/java/com/minecolonies/coremod/colony#): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings#](https://github.com/Minecolonies/minecolonies/blob/6f14e84023824fab504f1a9be8791e9d4bf79453/src/main/java/com/minecolonies/coremod/colony/buildings#): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions#](https://github.com/Minecolonies/minecolonies/blob/6f14e84023824fab504f1a9be8791e9d4bf79453/src/main/java/com/minecolonies/coremod/colony/permissions#): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [init#](https://github.com/Minecolonies/minecolonies/blob/6f14e84023824fab504f1a9be8791e9d4bf79453/src/main/java/com/minecolonies/coremod/colony/requestsystem/init#): Add a 'package-info.java' file to document the 'init' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [locations#](https://github.com/Minecolonies/minecolonies/blob/6f14e84023824fab504f1a9be8791e9d4bf79453/src/main/java/com/minecolonies/coremod/colony/requestsystem/locations#): Add a 'package-info.java' file to document the 'locations' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
