### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by EnterFor**
It was great for me, even though it was tiring

Config finds time to continue translating
I'm Chinese and I like this Mod

### CODE REVIEW

**Comment by EnterFor** [comment]
Emmm, why is no one checking

**Comment by Raycoms** [comment]
I'll merge this, in the future please contribute through translate.minecolonies.com

**Comment by EnterFor** [comment]
> 我将合并，以后请通过translate.minecolonies.com贡献

Thanks. I thought it was here. I'll be careful next time

**Comment by EnterFor** [comment]
> 我将合并，以后请通过translate.minecolonies.com贡献

I studied it for a while, and I found that I couldn't upload language files
I don't know how to use it, can I continue to commit on github?
I'm very, very, very sorry

**Pull request merged**
