### PR TITLE
Add journeymap support + npe fix

### LINKED ISSUE #1338: Exception caught during firing event when closing server
### Minecolonies version

minecolonies-universal-1.12-0.8.3238
forge-1.12-14.21.1.2428-universal

### Expected behavior

no error when stopping server

### Actual behaviour

Sometimes when I shutdown the server after a couple of hours uptime,
I see this error in console:

https://gist.github.com/FiveEYZ/f4cbaadd08cb7eaab3aaf553013d7ebd

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #1338

# Changes proposed in this pull request:
- Adds icons for the citizen on the journey map
- Fixes a crash on world load.

Review please

### CODE REVIEW

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 38 issues
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 35 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [ColonyManager.java#L40](https://github.com/Minecolonies/minecolonies/blob/8487d95bd7341a336bcbc957195569d25228fe82/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L40): class "ColonyManager" has 50 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ColonyManager.java#L94](https://github.com/Minecolonies/minecolonies/blob/8487d95bd7341a336bcbc957195569d25228fe82/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L94): Remove this unused "topColonyId" private field. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1068)
1. ![MAJOR][MAJOR] [ColonyManager.java#L742](https://github.com/Minecolonies/minecolonies/blob/8487d95bd7341a336bcbc957195569d25228fe82/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L742): Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/8487d95bd7341a336bcbc957195569d25228fe82/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/8487d95bd7341a336bcbc957195569d25228fe82/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/8487d95bd7341a336bcbc957195569d25228fe82/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/8487d95bd7341a336bcbc957195569d25228fe82/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [ColonyManager.java#L744](https://github.com/Minecolonies/minecolonies/blob/8487d95bd7341a336bcbc957195569d25228fe82/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L744): Use a logger to log this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1148)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/8487d95bd7341a336bcbc957195569d25228fe82/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions](https://github.com/Minecolonies/minecolonies/blob/8487d95bd7341a336bcbc957195569d25228fe82/src/main/java/com/minecolonies/coremod/colony/permissions): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 38 issues
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 35 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [ColonyManager.java#L40](https://github.com/Minecolonies/minecolonies/blob/7b8ffe027f701472fef3c4afeb3c8b287d8b6af2/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L40): class "ColonyManager" has 50 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [ColonyManager.java#L94](https://github.com/Minecolonies/minecolonies/blob/7b8ffe027f701472fef3c4afeb3c8b287d8b6af2/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L94): Remove this unused "topColonyId" private field. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1068)
1. ![MAJOR][MAJOR] [ColonyManager.java#L742](https://github.com/Minecolonies/minecolonies/blob/7b8ffe027f701472fef3c4afeb3c8b287d8b6af2/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L742): Either log or rethrow this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1166)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/7b8ffe027f701472fef3c4afeb3c8b287d8b6af2/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/7b8ffe027f701472fef3c4afeb3c8b287d8b6af2/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/7b8ffe027f701472fef3c4afeb3c8b287d8b6af2/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/7b8ffe027f701472fef3c4afeb3c8b287d8b6af2/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [ColonyManager.java#L744](https://github.com/Minecolonies/minecolonies/blob/7b8ffe027f701472fef3c4afeb3c8b287d8b6af2/src/main/java/com/minecolonies/coremod/colony/ColonyManager.java#L744): Use a logger to log this exception. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1148)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/7b8ffe027f701472fef3c4afeb3c8b287d8b6af2/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions](https://github.com/Minecolonies/minecolonies/blob/7b8ffe027f701472fef3c4afeb3c8b287d8b6af2/src/main/java/com/minecolonies/coremod/colony/permissions): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Asherslab** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1383/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Review by marchermans — COMMENTED** [review]
This is not done right?

**Comment by Asherslab** [comment]
'tis (Should be)

**Comment by Asherslab** [comment]
most of the support is on the JourneyMap end

**Comment by marchermans** [comment]
Does this work cause we have it in a specific directory or what? Cause we do not add any code in this PR with regards to this?

**Comment by Raycoms** [comment]
Yes Journeymap has an API which searches in that directory.

2017-08-22 19:20 GMT+01:00 Marc Hermans <notifications@github.com>:

**Comment by Raycoms** [comment]
@OrionDevelopment

**Review by marchermans — APPROVED** [review]

**Comment by marchermans** [comment]
Closes #1391 1391

**Pull request merged**
