### PR TITLE
Updated README for windows

### PR DESCRIPTION
**Pull request by Pawlost**
Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
Looks good :shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/3997/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Comment by someaddons** [comment]
oh that reminds me, probably should add that for the newer IntelliJ versions you need to set build and run to intelliJ instead of gradle to be able to use the generated runClient/server task. In settings -> Build Tools -> Gradle -> Build & Run to IntelliJ(default is gradle)

**Comment by Asherslab** [comment]
That latest commit was quite outside the scope of the PR

**Comment by Pawlost** [comment]
Yes sorry my mistake

**Pull request closed without merging**
