### PR TITLE
Recipes/tweaks

### PR DESCRIPTION
**Pull request by Mekle001**
# Changes proposed in this pull request:
- Add blaze rod as ingredient to Mechanic
- Add sticky piston as Mechanic product
- Add bamboo as plantation ingredient (Sticks and more sticks!)
- Add composting barrel to sawmill products.  
- Add a chance of prismarine shards and prismarine crystals to drop from fisherman
- Fix sponge so that it actually drops
- Use primary skill to enhance bonus drop rates
- Add recipes for Prismarine and Prismarine blocks to stonemason
- Add recipe for dark prismarine to dyer

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
Potentially the netherwart block should be for that nether/end farmer then?

**Comment by Mekle001** [comment]
Yeah, I was thinking about that, and almost pulled it as a result. Let's see how the discussion around colony self sufficiency goes, and see if we can get an idea how far out that might be.

**Comment by ravenbuilder934** [comment]
*goes and makes yet another draft PR for the wiki*

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/5518/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Review by someaddons — APPROVED** [review]

**Pull request merged**
