### PR TITLE
Barracks - Show list all citizens assigned to that building #2597

### PR DESCRIPTION
**Pull request by bob0bob**
This changes the default listing of hired workers for the building.  If there are more than one, then it creates a scroll bar with a list of all the workers assigned to this building.  This is really about the barracks where you can have up to 5 guards per barrack.

### CODE REVIEW

**Comment by Raycoms** [comment]
Looks good :shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/2616/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by bob0bob** [comment]
Updating code to reflect the changes.

**Review by LDTTeam-Buildsystem — APPROVED** [review]
#### Analysis Complete
##### Statistics:
|        | Count | New | Old  | Diff  |
| ------ |:-----:|:---:|:----:|:-----:|
| Total  | 31600 |  2  | 2420 | -2418 |
| Errors |  593  |  0  |  0   |   0   |
##### More Information:
- [Analysis - Full](https://teamcity.minecolonies.com/viewLog.html?buildId=11450&tab=Inspection&buildTypeId=bt88)

**Review by marchermans — APPROVED** [review]
Looks good.

**Pull request merged**
