### PR TITLE
Feature/better builder lj positioning

### LINKED ISSUE #943: Smarter build site calculation
Builder should calculate the place to build smarter and closer to the building to build.

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #943

# Changes proposed in this pull request:
Improves the builder and lumberjack positioning.

Review please

### CODE REVIEW

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 64 issues
* ![MAJOR][MAJOR] 8 major
* ![MINOR][MINOR] 46 minor
* ![INFO][INFO] 10 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EntityFishHook.java#L251](https://github.com/Minecolonies/minecolonies/blob/5a518b8ff53de1cd411f02da09d046f94af22601/src/main/java/com/minecolonies/coremod/entity/EntityFishHook.java#L251): Remove this expression which always evaluates to "false" [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2589)
1. ![MAJOR][MAJOR] [EntityFishHook.java#L738](https://github.com/Minecolonies/minecolonies/blob/5a518b8ff53de1cd411f02da09d046f94af22601/src/main/java/com/minecolonies/coremod/entity/EntityFishHook.java#L738): Remove this "return" statement or make it conditional. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1751)
1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L57](https://github.com/Minecolonies/minecolonies/blob/5a518b8ff53de1cd411f02da09d046f94af22601/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L57): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 29 to the maximum authorized 20 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L729](https://github.com/Minecolonies/minecolonies/blob/5a518b8ff53de1cd411f02da09d046f94af22601/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L729): Refactor this method to reduce its Cognitive Complexity from 32 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L47](https://github.com/Minecolonies/minecolonies/blob/5a518b8ff53de1cd411f02da09d046f94af22601/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L47): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 30 to the maximum authorized 20 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L185](https://github.com/Minecolonies/minecolonies/blob/5a518b8ff53de1cd411f02da09d046f94af22601/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L185): The Cyclomatic Complexity of this method "requestMaterials" is 16 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [InventoryUtils.java](https://github.com/Minecolonies/minecolonies/blob/5a518b8ff53de1cd411f02da09d046f94af22601/src/main/java/com/minecolonies/coremod/util/InventoryUtils.java): This file has 773 lines, which is greater than 750 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [InventoryUtils.java#L27](https://github.com/Minecolonies/minecolonies/blob/5a518b8ff53de1cd411f02da09d046f94af22601/src/main/java/com/minecolonies/coremod/util/InventoryUtils.java#L27): class "InventoryUtils" has 85 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/5a518b8ff53de1cd411f02da09d046f94af22601/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/5a518b8ff53de1cd411f02da09d046f94af22601/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 61 issues
* ![MAJOR][MAJOR] 6 major
* ![MINOR][MINOR] 46 minor
* ![INFO][INFO] 9 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L57](https://github.com/Minecolonies/minecolonies/blob/d21542e7c521d7678d6e38db159764837464e802/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L57): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 29 to the maximum authorized 20 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L729](https://github.com/Minecolonies/minecolonies/blob/d21542e7c521d7678d6e38db159764837464e802/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L729): Refactor this method to reduce its Cognitive Complexity from 32 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L47](https://github.com/Minecolonies/minecolonies/blob/d21542e7c521d7678d6e38db159764837464e802/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L47): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 30 to the maximum authorized 20 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L185](https://github.com/Minecolonies/minecolonies/blob/d21542e7c521d7678d6e38db159764837464e802/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L185): The Cyclomatic Complexity of this method "requestMaterials" is 16 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MAJOR][MAJOR] [InventoryUtils.java](https://github.com/Minecolonies/minecolonies/blob/d21542e7c521d7678d6e38db159764837464e802/src/main/java/com/minecolonies/coremod/util/InventoryUtils.java): This file has 773 lines, which is greater than 750 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [InventoryUtils.java#L27](https://github.com/Minecolonies/minecolonies/blob/d21542e7c521d7678d6e38db159764837464e802/src/main/java/com/minecolonies/coremod/util/InventoryUtils.java#L27): class "InventoryUtils" has 85 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/d21542e7c521d7678d6e38db159764837464e802/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/d21542e7c521d7678d6e38db159764837464e802/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/d21542e7c521d7678d6e38db159764837464e802/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/d21542e7c521d7678d6e38db159764837464e802/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 47 issues
* ![MAJOR][MAJOR] 4 major
* ![MINOR][MINOR] 40 minor
* ![INFO][INFO] 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L57](https://github.com/Minecolonies/minecolonies/blob/63bf9da94fa982d6bb4080d850b12992e3324d8b/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L57): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 29 to the maximum authorized 20 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L729](https://github.com/Minecolonies/minecolonies/blob/63bf9da94fa982d6bb4080d850b12992e3324d8b/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L729): Refactor this method to reduce its Cognitive Complexity from 32 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L47](https://github.com/Minecolonies/minecolonies/blob/63bf9da94fa982d6bb4080d850b12992e3324d8b/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L47): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 30 to the maximum authorized 20 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L185](https://github.com/Minecolonies/minecolonies/blob/63bf9da94fa982d6bb4080d850b12992e3324d8b/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L185): The Cyclomatic Complexity of this method "requestMaterials" is 16 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/63bf9da94fa982d6bb4080d850b12992e3324d8b/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/63bf9da94fa982d6bb4080d850b12992e3324d8b/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/63bf9da94fa982d6bb4080d850b12992e3324d8b/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/63bf9da94fa982d6bb4080d850b12992e3324d8b/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/63bf9da94fa982d6bb4080d850b12992e3324d8b/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/63bf9da94fa982d6bb4080d850b12992e3324d8b/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 45 issues
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 40 minor
* ![INFO][INFO] 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractEntityAIStructure.java#L729](https://github.com/Minecolonies/minecolonies/blob/63bf9da94fa982d6bb4080d850b12992e3324d8b/src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java#L729): Refactor this method to reduce its Cognitive Complexity from 32 to the 20 allowed. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3776)
1. ![MAJOR][MAJOR] [EntityAIStructureBuilder.java#L185](https://github.com/Minecolonies/minecolonies/blob/63bf9da94fa982d6bb4080d850b12992e3324d8b/src/main/java/com/minecolonies/coremod/entity/ai/citizen/builder/EntityAIStructureBuilder.java#L185): The Cyclomatic Complexity of this method "requestMaterials" is 16 which is greater than 15 authorized. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
1. ![MINOR][MINOR] [blockout](https://github.com/Minecolonies/minecolonies/blob/63bf9da94fa982d6bb4080d850b12992e3324d8b/src/main/java/com/minecolonies/blockout): Add a 'package-info.java' file to document the 'blockout' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [controls](https://github.com/Minecolonies/minecolonies/blob/63bf9da94fa982d6bb4080d850b12992e3324d8b/src/main/java/com/minecolonies/blockout/controls): Add a 'package-info.java' file to document the 'controls' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [views](https://github.com/Minecolonies/minecolonies/blob/63bf9da94fa982d6bb4080d850b12992e3324d8b/src/main/java/com/minecolonies/blockout/views): Add a 'package-info.java' file to document the 'views' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/63bf9da94fa982d6bb4080d850b12992e3324d8b/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/63bf9da94fa982d6bb4080d850b12992e3324d8b/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/63bf9da94fa982d6bb4080d850b12992e3324d8b/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/63bf9da94fa982d6bb4080d850b12992e3324d8b/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/63bf9da94fa982d6bb4080d850b12992e3324d8b/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by marvin-bitterlich** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/952/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Pull request merged**
