### PR TITLE
Abandoned colonies with noticeable decay

### PR DESCRIPTION
**Pull request by Aalandriel**
# Changes proposed in this pull request:
- Time has taken it's toll on abandoned colonies, buildings are now noticeably decayed
- Roads no longer pass through buildings in abandoned colonies
- Abandoned colonies can spawn as any medieval style, Caledonia or Asian.
- Parks can spawn as part of an abandoned colony

javaw_sfEGZ9isSW
javaw_5gUKFBkHCR
javaw_u7G74xhGk4
javaw_flEVNBddnj
javaw_AqmHAF2cD9
javaw_ojoktfIwg8
javaw_nbnrie5Dmd
javaw_S4Yd6dTtYr
javaw_Z5Uh5Kz4D7

Review please

# Creating your own style
In order to create your own abandoned colony style you need to import the Minecolonies structures into a world, add jigsaw block connecters at appropriate places and export the structure as an .nbt file. 
## Tagging and prepping 
The most important thing to ensure that colonies register as abandoned - and can be restored - is to use the tag tool to tag the building block:
- tag the building block with its style name. The name must match the style's folder name in the Minecolonies.jar or resource pack.
- then add the tag "abandoned"
If you right click the building with an empty hand it should now say that the building is abandoned, and tell you to seek out the town hall.

## Adding jigsaw blocks
Place jigsaw blocks where a structure would naturally connect to a road, or if creating a road, where it would connect to a structure. Make sure the block is placed at the edge of the structure facing toward a connecting block.
When editing a jigsaw block there are a few different properties that can be set.
- name. the name of this jigsaw block. The name can be unique or generic. For the styles in Minecolonies all buildings have the name "minecolonies:building_entrance" and all roads "minecolonies:street". Some styles will also use "minecolonies:field" this one is used exclusively to connect a field to farmer hut structure when the farmer hut does not have a field as part of the lvl 1 structure.
- target. When a structure is placed, the target of its jigsaw block determines the next jigsaw block that is added. The target of a placed structure must match the name of the to be placed one.
- pool. To restrict the list of applicable structures use the target pool. Minecolonies use 3 dedicated pools for each colony style. "`<stylename>/roads`", "`<stylename>/buildings`",  "`<stylename>/terminators`".

Edit the jigsaw block to set the following properties:

Buildings:
- name:"minecolonies:building_entrance"
- pool:"minecolonies:medieval_oak/roads"
- target:"minecolonies:building_entrance"
- turns into: minecraft:structure_void

Roads (road connector):
- name: "minecolonies:street"
- pool: "minecolonies:medieval_spruce/roads"
- target: "minecolonies:street"
- turns into: minecraft:structure_void

Roads (building connector):
- name: "minecolonies:building_entrance"
- pool: "minecolonies:medieval_spruce/buildings"
- target: "minecolonies:building_entrance"
- turns into: minecraft:structure_void

Terminators
Terminators are used to end roads in a more decorative fashion. They are also used as fallback structures for roads and buildings.
- name: "minecolonies:street"
- turns into: minecraft:structure_void

## Processors
Processors are used to alter the blocks of a structure during placement. Specifically for Minecolonies, we use different processors depending on the structure that is placed. 

There are three processor files for each styles
### street.json
Road processors are defined in "`<stylename>/street.json`". The main purpose of this processor is to replace porous materials like dirt, dirt path and gravel with wooden planks when the roads is in water. But will also add minor decay in form of grass blocks iso of dirt paths
### decoration.json
Park processors are defined in "`<stylename>/decoration.json`". This processor adds decay to the parks by turning some stone brick into weathered variants like mossy or cracked stone bricks or replaces some dirt blocks with coarse dirt.
### placeholder_replacement.json
Building processors are defined in "`<stylename>/placeholder_replacement.json`". Similar to how zombie villages decay, this processor removes various building blocks or replaces them with cobweb. Which blocks and how often depends on the given style. In addition to decay the placeholder replacement is also responsible for converting the Structurize substitution blocks into suitable in game blocks similar to how a builder treats these blocks when constructing a builder.
- structurize:blocksolidsubstitution turns into Dirt, which may converted to another block by a processor defined later in the same file
- structurize:blocksubstitution are ignored meaning that existing blocks in the world will remain in place when the structure generates.
#### Decay sample
The rule below replaces oak logs with cobweb at 4% probability. That probability may be fine for one style but be too high or too low for other styles.
`        {
          "output_state": {
            "Name": "minecraft:cobweb"
          },
          "input_predicate": {
            "block": "minecraft:oak_log",
            "probability": 0.04,
            "predicate_type": "minecraft:random_block_match"
          },
          "location_predicate": {
            "predicate_type": "minecraft:always_true"
          }
        },
`

### CODE REVIEW

**Comment by Raycoms** [comment]
I took a quick look overall and it seems all good. Could you do a quick writeup to the different processors you've added?
As far as I saw there are building and street processors for each style. (I guess as each style uses different materials and wants different "decays"). 

To allow easy addition of new styles by other people or through datapacks.

Did you test and double check if style and "abandoned" tags are properly set on each building? (I guess this can be done through a script that checks the file nbt contents too).

**Comment by Aalandriel** [comment]
Description in progress. 

> Did you test and double check if style and "abandoned" tags are properly set on each building? (I guess this can be done through a script that checks the file nbt contents too).

I manually checked each structure. They should all be good. Wouldn't know where to start to create a script to test this programmatically.

**Comment by Aalandriel** [comment]
@Raycoms Is the documentation I added along what you had in mind? I don't think it's feasible to document each processor in depth... Once you get the hang of them, they are pretty self explanatory and all rules are decently documented on the Minecraft community wiki.

**Review by someaddons — APPROVED** [review]

**Comment by Raycoms** [comment]
> @Raycoms Is the documentation I added along what you had in mind? I don't think it's feasible to document each processor in depth... Once you get the hang of them, they are pretty self explanatory and all rules are decently documented on the Minecraft community wiki.

Yes thank you, it's perfect.

**Pull request merged**
