### PR TITLE
Fix messages

### PR DESCRIPTION
**Pull request by someaddons**
# Changes proposed in this pull request:
-Fix colony deletion message
-Fix all messages formatting

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/4912/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Comment by LDTTeam-Buildsystem** [comment]
This PR has been automatically built and hosted by our build system, during this process there was a crash, error, or otherwise, please check on this at: https://teamcity.minecolonies.com/viewLog.html?buildId=39511&buildTypeId=LetSDevTogether_Minecolonies_PullRequests_2_DeployTestServer

**Comment by marchermans** [comment]
@someaddons Not building!

**Comment by someaddons** [comment]
it is, just the testserver appears to be broken again

**Comment by someaddons** [comment]
same with the other PR

**Comment by LDTTeam-Buildsystem** [comment]
This PR has been automatically built and hosted by our build system, during this process there was a crash, error, or otherwise, please check on this at: https://teamcity.minecolonies.com/viewLog.html?buildId=39535&buildTypeId=LetSDevTogether_Minecolonies_PullRequests_2_DeployTestServer

**Pull request merged**
