### PR TITLE
Advancements improvements

### PR DESCRIPTION
**Pull request by ShadowProtocol**
# Changes proposed in this pull request:
- Separate the advancements into three tabs: MineColonies, Production, and Military
- Add some more advancements
    - More ideas for raid related and research related advancements to come
- Shorten some of the needlessly long advancement ids

Still a work in progress - I don't think there is really any good way to lay these out.

Will need to be ported to 1.16

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
Overally it looks nice, some classes are missing some javadoc though. I didn't look through all the jsons so what I'm saying might be irrelevant, but we have to avoid all the item/recipe triggers. Because minecraft apparently constantly checks the inventory for those items for those vanilla triggers.

**Comment by ShadowProtocol** [comment]
Yeah I didn't add any advancements related to inventories.
And whatever javadocs missing was probably from a duplicated file that was also originally missing javadoc. Regardless I'll add some in.

**Comment by ShadowProtocol** [comment]
In fact I think the entire advancements section is missing javadoc. This may take a little bit.

**Comment by Raycoms** [comment]
Bad @Asherslab no javadoc!

**Comment by Asherslab** [comment]
bad @Raycoms you guys reviewed it originally =P

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/6071/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Review by someaddons — APPROVED** [review]

**Pull request merged**
