### PR TITLE
Citizen hut schematic change

### PR DESCRIPTION
**Pull request by MineShadow7**
# Changes proposed in this pull request:
- Changed citizens hut schematics.
- This made to make our schematic more "unique" and more fancy.

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
Can you post some screenshots?

**Comment by MineShadow7** [comment]
(Stone buildings are not part of PR)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 31 issues
* ![MINOR][MINOR] 31 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/ad72fc2a3adcd03c59faeb8e2ff865f58953801e/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/ad72fc2a3adcd03c59faeb8e2ff865f58953801e/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/ad72fc2a3adcd03c59faeb8e2ff865f58953801e/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/ad72fc2a3adcd03c59faeb8e2ff865f58953801e/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/ad72fc2a3adcd03c59faeb8e2ff865f58953801e/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions](https://github.com/Minecolonies/minecolonies/blob/ad72fc2a3adcd03c59faeb8e2ff865f58953801e/src/main/java/com/minecolonies/coremod/colony/permissions): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [requestsystem](https://github.com/Minecolonies/minecolonies/blob/ad72fc2a3adcd03c59faeb8e2ff865f58953801e/src/main/java/com/minecolonies/coremod/colony/requestsystem): Add a 'package-info.java' file to document the 'requestsystem' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [init](https://github.com/Minecolonies/minecolonies/blob/ad72fc2a3adcd03c59faeb8e2ff865f58953801e/src/main/java/com/minecolonies/coremod/colony/requestsystem/init): Add a 'package-info.java' file to document the 'init' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [locations](https://github.com/Minecolonies/minecolonies/blob/ad72fc2a3adcd03c59faeb8e2ff865f58953801e/src/main/java/com/minecolonies/coremod/colony/requestsystem/locations): Add a 'package-info.java' file to document the 'locations' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [requests](https://github.com/Minecolonies/minecolonies/blob/ad72fc2a3adcd03c59faeb8e2ff865f58953801e/src/main/java/com/minecolonies/coremod/colony/requestsystem/requests): Add a 'package-info.java' file to document the 'requests' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Raycoms** [comment]
@pmardle what do you think as the default style?

**Comment by pmardle** [comment]
Ok, although the material types may be a bit of a block (these seem to use Dark Oak? as the Columns.) - this would be better for the low level buildings to be standard Oak as this is far more readily available..

Without seeing the details / interiors is hard to assess if the material progression through the levels is relevant/difficult enough as each level is built.. (just a bigger building of the same old materials is not really a challenge - each level should add a number of new blocks/items etc that were not used in the previous and get increasingly rare..

Overall Design looks ok though :) and I do like the mix of wood and stone,

**Comment by MineShadow7** [comment]
I used spruce wood more. Interior wasn't changed (it's just rework of default style).

**Comment by Asherslab** [comment]
@pmardle @Raycoms What're we thinking with this? Go or no?
i say it's good =D

**Comment by MineShadow7** [comment]
Anyone?

**Comment by Raycoms** [comment]
I think we might want that as "default" style and not as the "wooden style".
Or as minecolonies style.

2017-09-19 12:56 GMT+01:00 MineShadow7 <notifications@github.com>:

**Comment by MineShadow7** [comment]
Sounds good. I'll change that to "default" style

**Comment by Raycoms** [comment]
:shipit: 
I still think we should have a range of custom blocks (~ 10) 1-2 for each biome.
Craftable from materials from the biome.

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1451/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 31 issues
* ![MINOR][MINOR] 31 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/499b5790ad4703adbb8866e0de6ce08ea46aafd6/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/499b5790ad4703adbb8866e0de6ce08ea46aafd6/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/499b5790ad4703adbb8866e0de6ce08ea46aafd6/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/499b5790ad4703adbb8866e0de6ce08ea46aafd6/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/499b5790ad4703adbb8866e0de6ce08ea46aafd6/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions](https://github.com/Minecolonies/minecolonies/blob/499b5790ad4703adbb8866e0de6ce08ea46aafd6/src/main/java/com/minecolonies/coremod/colony/permissions): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [requestsystem](https://github.com/Minecolonies/minecolonies/blob/499b5790ad4703adbb8866e0de6ce08ea46aafd6/src/main/java/com/minecolonies/coremod/colony/requestsystem): Add a 'package-info.java' file to document the 'requestsystem' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [init](https://github.com/Minecolonies/minecolonies/blob/499b5790ad4703adbb8866e0de6ce08ea46aafd6/src/main/java/com/minecolonies/coremod/colony/requestsystem/init): Add a 'package-info.java' file to document the 'init' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [locations](https://github.com/Minecolonies/minecolonies/blob/499b5790ad4703adbb8866e0de6ce08ea46aafd6/src/main/java/com/minecolonies/coremod/colony/requestsystem/locations): Add a 'package-info.java' file to document the 'locations' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [requests](https://github.com/Minecolonies/minecolonies/blob/499b5790ad4703adbb8866e0de6ce08ea46aafd6/src/main/java/com/minecolonies/coremod/colony/requestsystem/requests): Add a 'package-info.java' file to document the 'requests' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Asherslab** [comment]
Looking good! :shipit:

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1451/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 31 issues
* ![MINOR][MINOR] 31 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/8b1369c5e66230564d45f50107064e1679aed4fc/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/8b1369c5e66230564d45f50107064e1679aed4fc/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/8b1369c5e66230564d45f50107064e1679aed4fc/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/8b1369c5e66230564d45f50107064e1679aed4fc/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/8b1369c5e66230564d45f50107064e1679aed4fc/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions](https://github.com/Minecolonies/minecolonies/blob/8b1369c5e66230564d45f50107064e1679aed4fc/src/main/java/com/minecolonies/coremod/colony/permissions): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [requestsystem](https://github.com/Minecolonies/minecolonies/blob/8b1369c5e66230564d45f50107064e1679aed4fc/src/main/java/com/minecolonies/coremod/colony/requestsystem): Add a 'package-info.java' file to document the 'requestsystem' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [init](https://github.com/Minecolonies/minecolonies/blob/8b1369c5e66230564d45f50107064e1679aed4fc/src/main/java/com/minecolonies/coremod/colony/requestsystem/init): Add a 'package-info.java' file to document the 'init' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [locations](https://github.com/Minecolonies/minecolonies/blob/8b1369c5e66230564d45f50107064e1679aed4fc/src/main/java/com/minecolonies/coremod/colony/requestsystem/locations): Add a 'package-info.java' file to document the 'locations' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [requests](https://github.com/Minecolonies/minecolonies/blob/8b1369c5e66230564d45f50107064e1679aed4fc/src/main/java/com/minecolonies/coremod/colony/requestsystem/requests): Add a 'package-info.java' file to document the 'requests' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by pmardle** [comment]
We shouldnt really have a style called "Default"

There should be a option in teh Town Hall GUI to select a style as "Default"

I.e. if your building in the desert you can set "Sandstone" as teh default
style in the town hall GUI and then all future buildings will be defaulted
to Sandstone as the selected style :) - which of course you can manually
change if you want.

**Comment by Raycoms** [comment]
@pmardle We can also call it "basic", the idea is if the player doesn't choose any style there will be one chosen by default.

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 31 issues
* ![MINOR][MINOR] 31 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/2f2dbff862c598e77037bd6194de8899e5e72859/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/2f2dbff862c598e77037bd6194de8899e5e72859/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/2f2dbff862c598e77037bd6194de8899e5e72859/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/2f2dbff862c598e77037bd6194de8899e5e72859/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/2f2dbff862c598e77037bd6194de8899e5e72859/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions](https://github.com/Minecolonies/minecolonies/blob/2f2dbff862c598e77037bd6194de8899e5e72859/src/main/java/com/minecolonies/coremod/colony/permissions): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [requestsystem](https://github.com/Minecolonies/minecolonies/blob/2f2dbff862c598e77037bd6194de8899e5e72859/src/main/java/com/minecolonies/coremod/colony/requestsystem): Add a 'package-info.java' file to document the 'requestsystem' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [init](https://github.com/Minecolonies/minecolonies/blob/2f2dbff862c598e77037bd6194de8899e5e72859/src/main/java/com/minecolonies/coremod/colony/requestsystem/init): Add a 'package-info.java' file to document the 'init' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [locations](https://github.com/Minecolonies/minecolonies/blob/2f2dbff862c598e77037bd6194de8899e5e72859/src/main/java/com/minecolonies/coremod/colony/requestsystem/locations): Add a 'package-info.java' file to document the 'locations' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [requests](https://github.com/Minecolonies/minecolonies/blob/2f2dbff862c598e77037bd6194de8899e5e72859/src/main/java/com/minecolonies/coremod/colony/requestsystem/requests): Add a 'package-info.java' file to document the 'requests' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MineShadow7** [comment]
So what should I change?

**Comment by Raycoms** [comment]
Closed for now

**Pull request closed without merging**
