### PR TITLE
Fix crash when selecting warehouse in another colony using resource scroll [1.20]

### PR DESCRIPTION
**Pull request by Thodor12**
See #9499

### CODE REVIEW

**Review by Raycoms — COMMENTED** [review]
That seems like a lot of changes for such a small fix?

**Comment by Thodor12** [comment]
> That seems like a lot of changes for such a small fix?

It was easier this way, previously all of the warehouse handling was done in the window, all on the client, which wasn't ideal, had some troubles getting the fix in that way.

So I opted to pull the logic up to the item itself, prior to even opening the window, that way the window code is not so polluted and all the special conditions were easier to make before opening the window.

**Comment by Raycoms** [comment]
> Reference

that was intentional though, no need to involve the server with something that could be done entirely on the client.

**Comment by Thodor12** [comment]
> > Reference
> 
> that was intentional though, no need to involve the server with something that could be done entirely on the client.

That's not entirely true, the client was modifying the snapshot, which required a message class to persist that on the server, else the snapshot data would not be present.
Doing that on the server to begin with means I can also remove the message class (which I forgot, let me do that)

**Comment by Raycoms** [comment]
> > > Reference
> > 
> > 
> > that was intentional though, no need to involve the server with something that could be done entirely on the client.
> 
> That's not entirely true, the client was modifying the snapshot, which required a message class to persist that on the server, else the snapshot data would not be present. Doing that on the server to begin with means I can also remove the message class (which I forgot, let me do that)

Yeah, but I did not want to do this relatively expensive call to happen on the server. The entire indexing warehouse stuff for all the items in the list, not that amazing to do on the server if we can compute this entirely on the client and just synch the result.

**Review by Raycoms — CHANGES_REQUESTED** [review]
This intentionally was computed on the client

**Comment by Thodor12** [comment]
Then I'll modify it so the info is calculated upon calling openWindow, but not in the window itself.
I just got rid of all that code mess in there

**Comment by Raycoms** [comment]
> Then I'll modify it so the info is calculated upon calling openWindow, but not in the window itself. I just got rid of all that code mess in there

What does it matter if the exact same code is in the window, or in the item? From a maintenance perspective its easier in the window because thats where we expect code related to this feature, the item has a bunch of other features aside of that.

**Comment by Thodor12** [comment]
In the window it's a little bit messy, because I had to load the building as part of the constructor, which means it could optionally be null.

That meant in every single function I had to account for the building being null as well, which quickly becomes annoying.
Putting all that logic before the window constructor is even called means I can guarantee the building in the window is even there to begin with.
That also means I don't have to pass the compound data of the item around into the window itself (seperation of concern), the item itself should manage the compound data, not the window.

**Comment by Raycoms** [comment]
> In the window it's a little bit messy, because I had to load the building as part of the constructor, which means it could optionally be null.
> 
> That meant in every single function I had to account for the building being null as well, which quickly becomes annoying. Putting all that logic before the window constructor is even called means I can guarantee the building in the window is even there to begin with. That also means I don't have to pass the compound data of the item around into the window itself (seperation of concern), the item itself should manage the compound data, not the window.

I mean we can just do a colony id verification on the server before opening. Or, in the constructor once verify the building is not null, and else exit

**Review by Raycoms — APPROVED** [review]

**Review by someaddons — APPROVED** [review]

**Pull request merged**
