### PR TITLE
Feature/move again

### PR DESCRIPTION
**Pull request by marvin-bitterlich**
Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1070/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 264 issues
* ![MAJOR][MAJOR] 159 major
* ![MINOR][MINOR] 56 minor
* ![INFO][INFO] 49 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [WindowHireWorker.java#L125](https://github.com/Minecolonies/minecolonies/blob/fd7f19da62b0b9b0932782251e84f99ef8873ad4/src/main/java/com/minecolonies/coremod/client/gui/WindowHireWorker.java#L125): Reduce this anonymous class number of lines from 31 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowHutFarmer.java#L206](https://github.com/Minecolonies/minecolonies/blob/fd7f19da62b0b9b0932782251e84f99ef8873ad4/src/main/java/com/minecolonies/coremod/client/gui/WindowHutFarmer.java#L206): Reduce this anonymous class number of lines from 37 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowHutMiner.java#L59](https://github.com/Minecolonies/minecolonies/blob/fd7f19da62b0b9b0932782251e84f99ef8873ad4/src/main/java/com/minecolonies/coremod/client/gui/WindowHutMiner.java#L59): Reduce this anonymous class number of lines from 22 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L472](https://github.com/Minecolonies/minecolonies/blob/fd7f19da62b0b9b0932782251e84f99ef8873ad4/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L472): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L627](https://github.com/Minecolonies/minecolonies/blob/fd7f19da62b0b9b0932782251e84f99ef8873ad4/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L627): Reduce this anonymous class number of lines from 24 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L728](https://github.com/Minecolonies/minecolonies/blob/fd7f19da62b0b9b0932782251e84f99ef8873ad4/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L728): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L886](https://github.com/Minecolonies/minecolonies/blob/fd7f19da62b0b9b0932782251e84f99ef8873ad4/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L886): Reduce this anonymous class number of lines from 40 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [CitizenData.java#L23](https://github.com/Minecolonies/minecolonies/blob/fd7f19da62b0b9b0932782251e84f99ef8873ad4/src/main/java/com/minecolonies/coremod/colony/CitizenData.java#L23): class "CitizenData" has 43 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/fd7f19da62b0b9b0932782251e84f99ef8873ad4/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.223 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L46](https://github.com/Minecolonies/minecolonies/blob/fd7f19da62b0b9b0932782251e84f99ef8873ad4/src/main/java/com/minecolonies/coremod/colony/Colony.java#L46): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 43 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by marchermans** [comment]
:shipit:

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1070/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 261 issues
* ![MAJOR][MAJOR] 161 major
* ![MINOR][MINOR] 50 minor
* ![INFO][INFO] 50 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [WindowHireWorker.java#L125](https://github.com/Minecolonies/minecolonies/blob/b8a1a5c0507a5ea90a1108313f2f10e8a2c6d7cf/src/main/java/com/minecolonies/coremod/client/gui/WindowHireWorker.java#L125): Reduce this anonymous class number of lines from 31 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowHutFarmer.java#L206](https://github.com/Minecolonies/minecolonies/blob/b8a1a5c0507a5ea90a1108313f2f10e8a2c6d7cf/src/main/java/com/minecolonies/coremod/client/gui/WindowHutFarmer.java#L206): Reduce this anonymous class number of lines from 37 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowHutMiner.java#L59](https://github.com/Minecolonies/minecolonies/blob/b8a1a5c0507a5ea90a1108313f2f10e8a2c6d7cf/src/main/java/com/minecolonies/coremod/client/gui/WindowHutMiner.java#L59): Reduce this anonymous class number of lines from 22 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L472](https://github.com/Minecolonies/minecolonies/blob/b8a1a5c0507a5ea90a1108313f2f10e8a2c6d7cf/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L472): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L627](https://github.com/Minecolonies/minecolonies/blob/b8a1a5c0507a5ea90a1108313f2f10e8a2c6d7cf/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L627): Reduce this anonymous class number of lines from 24 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L728](https://github.com/Minecolonies/minecolonies/blob/b8a1a5c0507a5ea90a1108313f2f10e8a2c6d7cf/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L728): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L886](https://github.com/Minecolonies/minecolonies/blob/b8a1a5c0507a5ea90a1108313f2f10e8a2c6d7cf/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L886): Reduce this anonymous class number of lines from 40 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [CitizenData.java#L23](https://github.com/Minecolonies/minecolonies/blob/b8a1a5c0507a5ea90a1108313f2f10e8a2c6d7cf/src/main/java/com/minecolonies/coremod/colony/CitizenData.java#L23): class "CitizenData" has 43 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/b8a1a5c0507a5ea90a1108313f2f10e8a2c6d7cf/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.224 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L46](https://github.com/Minecolonies/minecolonies/blob/b8a1a5c0507a5ea90a1108313f2f10e8a2c6d7cf/src/main/java/com/minecolonies/coremod/colony/Colony.java#L46): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 44 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 261 issues
* ![MAJOR][MAJOR] 161 major
* ![MINOR][MINOR] 50 minor
* ![INFO][INFO] 50 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [WindowHireWorker.java#L125](https://github.com/Minecolonies/minecolonies/blob/296b04d1a01736558ab5fc12a0621ba9e2170e6f/src/main/java/com/minecolonies/coremod/client/gui/WindowHireWorker.java#L125): Reduce this anonymous class number of lines from 31 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowHutFarmer.java#L206](https://github.com/Minecolonies/minecolonies/blob/296b04d1a01736558ab5fc12a0621ba9e2170e6f/src/main/java/com/minecolonies/coremod/client/gui/WindowHutFarmer.java#L206): Reduce this anonymous class number of lines from 37 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowHutMiner.java#L59](https://github.com/Minecolonies/minecolonies/blob/296b04d1a01736558ab5fc12a0621ba9e2170e6f/src/main/java/com/minecolonies/coremod/client/gui/WindowHutMiner.java#L59): Reduce this anonymous class number of lines from 22 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L472](https://github.com/Minecolonies/minecolonies/blob/296b04d1a01736558ab5fc12a0621ba9e2170e6f/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L472): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L627](https://github.com/Minecolonies/minecolonies/blob/296b04d1a01736558ab5fc12a0621ba9e2170e6f/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L627): Reduce this anonymous class number of lines from 24 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L728](https://github.com/Minecolonies/minecolonies/blob/296b04d1a01736558ab5fc12a0621ba9e2170e6f/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L728): Extract this nested ternary operation into an independent statement. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS3358)
1. ![MAJOR][MAJOR] [WindowTownHall.java#L886](https://github.com/Minecolonies/minecolonies/blob/296b04d1a01736558ab5fc12a0621ba9e2170e6f/src/main/java/com/minecolonies/coremod/client/gui/WindowTownHall.java#L886): Reduce this anonymous class number of lines from 40 to at most 20, or make it a named class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1188)
1. ![MAJOR][MAJOR] [CitizenData.java#L23](https://github.com/Minecolonies/minecolonies/blob/296b04d1a01736558ab5fc12a0621ba9e2170e6f/src/main/java/com/minecolonies/coremod/colony/CitizenData.java#L23): class "CitizenData" has 43 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/296b04d1a01736558ab5fc12a0621ba9e2170e6f/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1,224 lines, which is greater than 1,000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L46](https://github.com/Minecolonies/minecolonies/blob/296b04d1a01736558ab5fc12a0621ba9e2170e6f/src/main/java/com/minecolonies/coremod/colony/Colony.java#L46): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 44 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 135 issues
* ![MAJOR][MAJOR] 96 major
* ![MINOR][MINOR] 33 minor
* ![INFO][INFO] 6 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [CitizenData.java#L23](https://github.com/Minecolonies/minecolonies/blob/2958b2a089c79f26d891ab0cdb032a6c5b9da4ae/src/main/java/com/minecolonies/coremod/colony/CitizenData.java#L23): class "CitizenData" has 43 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/2958b2a089c79f26d891ab0cdb032a6c5b9da4ae/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.226 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L48](https://github.com/Minecolonies/minecolonies/blob/2958b2a089c79f26d891ab0cdb032a6c5b9da4ae/src/main/java/com/minecolonies/coremod/colony/Colony.java#L48): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 44 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L48](https://github.com/Minecolonies/minecolonies/blob/2958b2a089c79f26d891ab0cdb032a6c5b9da4ae/src/main/java/com/minecolonies/coremod/colony/Colony.java#L48): class "Colony" has 83 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L182](https://github.com/Minecolonies/minecolonies/blob/2958b2a089c79f26d891ab0cdb032a6c5b9da4ae/src/main/java/com/minecolonies/coremod/colony/Colony.java#L182): Assign this magic number 5 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L562](https://github.com/Minecolonies/minecolonies/blob/2958b2a089c79f26d891ab0cdb032a6c5b9da4ae/src/main/java/com/minecolonies/coremod/colony/Colony.java#L562): Reduce the number of returns of this method 11, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L1026](https://github.com/Minecolonies/minecolonies/blob/2958b2a089c79f26d891ab0cdb032a6c5b9da4ae/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1026): Assign this magic number 20 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1027](https://github.com/Minecolonies/minecolonies/blob/2958b2a089c79f26d891ab0cdb032a6c5b9da4ae/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1027): Assign this magic number 60 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1151](https://github.com/Minecolonies/minecolonies/blob/2958b2a089c79f26d891ab0cdb032a6c5b9da4ae/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1151): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1153](https://github.com/Minecolonies/minecolonies/blob/2958b2a089c79f26d891ab0cdb032a6c5b9da4ae/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1153): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
