### PR TITLE
Add lables to the rack inventory screen

### PR DESCRIPTION
**Pull request by ToMe25**
# Changes proposed in this pull request:
- Fix the rack inv screen not containing any text
-
-

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/4985/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Comment by ToMe25** [comment]
Btw here images of the change:
before(double rack):

after(single rack):

**Review by marchermans — APPROVED** [review]

**Comment by Perlo0ung** [comment]
@ToMe25: The label is a bit off for [double racks](https://imgur.com/a/vTR9h5l) in warehouse with storage upgrade

**Comment by ToMe25** [comment]
I will look into that later :)

**Comment by ToMe25** [comment]
OK i made a PR for it.

**Pull request merged**
