### PR TITLE
Supply camp and ship enhancement

### PR DESCRIPTION
**Pull request by MotionlessTrain**
Closes #
Closes #
Closes #

# Changes proposed in this pull request:
- Made survival friendly versions of supply camps and ships
-

[ ] Yes I tested this before submitting it.
[ ] I also did a multiplayer test.

Review please

### CODE REVIEW

**Comment by someaddons** [comment]
what is a "survival friendly" supply camp?

**Comment by MotionlessTrain** [comment]
It is a decoration looking like a supply camp (or ship), which can be built in survival
(i.e. not needing any of the loot, build tool or town hall which is usually part of the supply camp)

**Comment by someaddons** [comment]
ah so a copy without filled inventories

**Comment by MotionlessTrain** [comment]
Yup

**Pull request merged**
