### PR TITLE
Update fields list visuals

### PR DESCRIPTION
**Pull request by Thodor12**
# Changes proposed in this pull request:
- Modified "calcDirection" to return an enum, not a component, which allows for some more flexibility in comparison before showing the component
- Fields list of the plantation and farm have been updated with an improved loo

Farm GUI

[X] Yes I tested this before submitting it.
[ ] I also did a multiplayer test.

Review please

### CODE REVIEW

**Review by Raycoms — APPROVED** [review]

**Comment by someaddons** [comment]
I think the "taken by other farm already" should be a disabled button thats crossed out instead of checked, checked kinda seems like you can take it once you free up a slot

**Comment by Raycoms** [comment]
> I think the "taken by other farm already" should be a disabled button thats crossed out instead of checked, checked kinda seems like you can take it once you free up a slot

Doubling down on this. Can you make a screenshot of how a field taken up by someone else looks like?

**Comment by Thodor12** [comment]
Fields that are taken by another farm simply do not appear on this list at all

**Comment by Thodor12** [comment]
This was the second farmer I had when I was testing this

**Review by someaddons — APPROVED** [review]

**Pull request merged**
