### PR TITLE
Adds two general utility schematics

### PR DESCRIPTION
**Pull request by uecasm**
Closes ldtteam/Structurize#429

# Changes proposed in this pull request:
- Adds `fill`, an 8x8x8 of solid placeholders (to fill an area with solid blocks).
- Adds `dig`, an 8x8x8 of air (to dig out or clear an area).

Review please

Inspired by a conversation with Shindria on Discord.

### CODE REVIEW

**Comment by Aduis1210** [comment]
Could we add additional sizes? 
2x2 3x3 4x4 ect?
Or even make a tweakable option?

**Comment by Raycoms** [comment]
> Could we add additional sizes?
> 2x2 3x3 4x4 ect?
> Or even make a tweakable option?

That would be the shape-tool integration then.

**Comment by Aduis1210** [comment]
> > Could we add additional sizes?
> > 2x2 3x3 4x4 ect?
> > Or even make a tweakable option?
> 
> That would be the shape-tool integration then.

If possible :) It would be an awesome addition to the builder
I'd imagine it would be very sought after in the community.

**Comment by uecasm** [comment]
Yeah, I'm planning to have a look at shape tool integration today.  But I still think these should be merged, they're faster to use, and 8x8x8 is a reasonably useful size.

**Pull request merged**
