### PR TITLE
[1.16/HotFix] CME When changing job.

### PR DESCRIPTION
**Pull request by marchermans**
Fixing the CME caused by premature optimization applied by @someaddons

### CODE REVIEW

**Comment by someaddons** [comment]
got a stacktrace of the issue? Can't think of a place where we'd remove an AI during iteration

**Comment by someaddons** [comment]
nvm, I see the goalselector immediately removes it

**Review by someaddons — APPROVED** [review]
Should PR this to 1.15 aswell

**Comment by Raycoms** [comment]
Is this necessary? Can't we iterate over new ArrayList<>(goals) ? (I have this also in my current upcoming PR)

**Pull request closed without merging**
