### PR TITLE
Possibility to turn the mourning off and on

### LINKED ISSUE #840: Supply Camp as Decoration Can't be built.
When trying to build the Supply Camp as a decoration Builder will just stand there and do nothing.
Builder has all the materials in the list (pg. 2 GUI), and even the space required is cleared and clean.
Fire/Hire will reset him to go back and stare at the spot eternally. 
Several Minecraft days and fire/hire again.. same thing.

### LINKED ISSUE #840: Possibility to turn the mourning off and on
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.20.1
- MineColonies Version: 1.20.1-1.1.581-BETA
- Related Mods and their Versions: -

## Is your feature request related to a problem?
I think mourning mechanism should be a toggle feature, that player can turn on and off depending in their liking.

## Enhancement or Change description
Add config value that disabled/enables mourning.

### Notes or related things
Already prepared a PR for that.

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by KamilPacanek**
Closes https://github.com/ldtteam/minecolonies-features/issues/840

# Changes proposed in this pull request:
- Add server configuration to disable/enable mourning mechanism

[ ] Yes I tested this before submitting it. (I have not)
[ ] I also did a multiplayer test. (I have not)

Review please

### CODE REVIEW

**Comment by Thodor12** [comment]
Hello, thank you for the contribution. However did you check with any of the developers if we actually want this?

I can't speak for the entire team but I reckon we don't want to provide options to turn off gameplay features.

**Comment by KamilPacanek** [comment]
> Hello, thank you for the contribution. However did you check with any of the developers if we actually want this?
> 
> I can't speak for the entire team but I reckon we don't want to provide options to turn off gameplay features.

Hi I have not, if this is why it wasn't added in the first place I think PR or issue is the right way to discuss this. It's open source, if the owners do not like that I expect them to state that and reject PRs and close issue. 
I guess after that happen I can learn how to create own mod to make that change happen.

**Comment by Thodor12** [comment]
I checked with Raycoms, we don't accept changes to the config that disable features like so.

Your best approach is to check out https://github.com/gisellevonbingen-Minecraft/MineColonies_Tweaks, they already modify some things in a third party way.
Do note that this mod does not belong to us and we do not support the usage of this mod, so you are on your own for that one.

**Comment by someaddons** [comment]
Mourning is an important core mechanic to the game, which serveral other things rely on, we dont allow disabling those things via config. Also please do not use minecolonies tweaks its a hacky and invasive way of undermining the design of minecolonies that is going against the creators whishes.

**Pull request closed without merging**
