### PR TITLE
Fix/op level (#1120)

### PR DESCRIPTION
**Pull request by xavierh**
No tested

BTW checkPermission is never used (even in version/1.11)

Review please

### CODE REVIEW

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 29 issues
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 26 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractSingleCommand.java#L115](https://github.com/Minecolonies/minecolonies/blob/19756bb420b0fdd7ca77451d56c719cd78593970/src/main/java/com/minecolonies/coremod/commands/AbstractSingleCommand.java#L115): Reduce the number of returns of this method 13, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [ChangeColonyOwnerCommand.java#L52](https://github.com/Minecolonies/minecolonies/blob/19756bb420b0fdd7ca77451d56c719cd78593970/src/main/java/com/minecolonies/coremod/commands/colonycommands/ChangeColonyOwnerCommand.java#L52): Reduce the number of returns of this method 7, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [RandomTeleportCommand.java#L132](https://github.com/Minecolonies/minecolonies/blob/19756bb420b0fdd7ca77451d56c719cd78593970/src/main/java/com/minecolonies/coremod/commands/generalcommands/RandomTeleportCommand.java#L132): Reduce the total number of break and continue statements in this loop to use at most one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS135)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/19756bb420b0fdd7ca77451d56c719cd78593970/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/19756bb420b0fdd7ca77451d56c719cd78593970/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/19756bb420b0fdd7ca77451d56c719cd78593970/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/19756bb420b0fdd7ca77451d56c719cd78593970/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/19756bb420b0fdd7ca77451d56c719cd78593970/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions](https://github.com/Minecolonies/minecolonies/blob/19756bb420b0fdd7ca77451d56c719cd78593970/src/main/java/com/minecolonies/coremod/colony/permissions): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [creativetab](https://github.com/Minecolonies/minecolonies/blob/19756bb420b0fdd7ca77451d56c719cd78593970/src/main/java/com/minecolonies/coremod/creativetab): Add a 'package-info.java' file to document the 'creativetab' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Raycoms** [comment]
The check permission will be called by forge itself.
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1218/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by xavierh** [comment]
ok, thanks for the info

**Review by marchermans — APPROVED** [review]

**Comment by Raycoms** [comment]
:shipit:

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 29 issues
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 26 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractSingleCommand.java#L115](https://github.com/Minecolonies/minecolonies/blob/e5811dee57043e1f5af1a4ddf78ec75100c2db99/src/main/java/com/minecolonies/coremod/commands/AbstractSingleCommand.java#L115): Reduce the number of returns of this method 13, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [ChangeColonyOwnerCommand.java#L52](https://github.com/Minecolonies/minecolonies/blob/e5811dee57043e1f5af1a4ddf78ec75100c2db99/src/main/java/com/minecolonies/coremod/commands/colonycommands/ChangeColonyOwnerCommand.java#L52): Reduce the number of returns of this method 7, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [RandomTeleportCommand.java#L132](https://github.com/Minecolonies/minecolonies/blob/e5811dee57043e1f5af1a4ddf78ec75100c2db99/src/main/java/com/minecolonies/coremod/commands/generalcommands/RandomTeleportCommand.java#L132): Reduce the total number of break and continue statements in this loop to use at most one. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS135)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/e5811dee57043e1f5af1a4ddf78ec75100c2db99/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/e5811dee57043e1f5af1a4ddf78ec75100c2db99/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/e5811dee57043e1f5af1a4ddf78ec75100c2db99/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/e5811dee57043e1f5af1a4ddf78ec75100c2db99/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/e5811dee57043e1f5af1a4ddf78ec75100c2db99/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions](https://github.com/Minecolonies/minecolonies/blob/e5811dee57043e1f5af1a4ddf78ec75100c2db99/src/main/java/com/minecolonies/coremod/colony/permissions): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [creativetab](https://github.com/Minecolonies/minecolonies/blob/e5811dee57043e1f5af1a4ddf78ec75100c2db99/src/main/java/com/minecolonies/coremod/creativetab): Add a 'package-info.java' file to document the 'creativetab' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
