### PR TITLE
Added new kill command to remove Phantoms

### LINKED ISSUE #7156: No kill commands to remove Phantoms
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: minecolonies-0.14.181-ALPHA-universal.jar
- Structurize Version: structurize-0.13.174-ALPHA.jar

## Problem description

There are no "easy to use" kill commands to remove Phantoms when playing at night.

This gets annoying when trying to complete tasks during the night, or when you are idling for whatever reason.

### Notes or related things

I've already developed the code for this.

## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by Stoovey**
Added new CommandKillPhantom subclass that allows OP's to use /mc kill phantom to remove them during the night.

I didn't include this in the CommandKillMonster class, as you may want to leave the mobs alive.

Closes #7156 

# Changes proposed in this pull request:
- Added new /mc kill phantom command to remove phantoms

Review please

### CODE REVIEW

**Comment by someaddons** [comment]
I do appreciate your contribution, however I don't think this really belongs into minecolonies, for what purpose does minecolonies need a kill phantom command? we got no interaction/spawning of them at all

**Comment by Stoovey** [comment]
Hi @someaddons,

Thanks for taking a look.

Although MineColonies doesn't have any interaction with Phantoms, the players do.

On my server, we have a number of players who are playing through the night (game-time) that get constantly attacked by Phantoms or if they are doing "Admin" tasks in their respective Colonys, they constantly get chased.

You could say that the /mc kill monster command doesn't have any "interaction/spawning" within Minecolonies, but the command is there and is probably used by quite a few people.

If anything, and I can change it if you want, Phantoms should be killed under /mc kill monster, but I decided to make a subclass because "for what ever reason like AFK Mob Spawning", you wouldn't want your afk spawner to be destroyed of the Mobs it has spawned. (I wouldn't anyway).

Thanks!
Steve

**Comment by uecasm** [comment]
If your server collectively hates phantoms, then `/gamerule doInsomnia false`.

**Comment by someaddons** [comment]
also vanilla has kill commands for all entities, the minecolonies kill command is specific for raiders only, as it also ends the raid event

**Comment by Stoovey** [comment]
Hi both,

I take it this command will not be pushed/merged with the project then with the backlash it's receiving?

Thanks,
Steve

**Comment by someaddons** [comment]
ye while I like that you'd want to contribute to us, this PR won't get pulled in due to beeing a vanilla-only thing which vanilla even has its own commands for, so there is no reason to add it at all

**Pull request closed without merging**
