### PR TITLE
Make minecolonnies build great again

### PR DESCRIPTION
**Pull request by xavierh**
Fix build issue for version/1.11
Review please

### CODE REVIEW

**Comment by marvin-bitterlich** [comment]
please switch it around the other way :) thats how i fixed it in 1.11

**Comment by Raycoms** [comment]
I already fixed the build of 1.11 didn't I?
In 8d87104a0f5fed087fb5bf30998b471ad46c0059

**Comment by marvin-bitterlich** [comment]
@Raycoms why filename not storelocation?

**Comment by Raycoms** [comment]
we can call it storeLocation but we will have to change the name at the
other places as well.

2017-01-30 10:09 GMT-02:00 Marvin Hofmann <notifications@github.com>:

**Comment by xavierh** [comment]
AFAIK it is not fix in version/1.11 unless i failed to pull the last changes

**Comment by xavierh** [comment]
already on a different pr

**Pull request closed without merging**
