### PR TITLE
Bug771/Fix egg monster in SimplePark

### LINKED ISSUE #771: Simple park requires monster egg
### Minecolonies version

version 0.7.3.2

### Expected behavior
Simple park does not require monster egg

### Actual behaviour

Simple park requires 4 cobblestone monster eggs

### Steps to reproduce the problem

1. Start a colony
2. Build a builder's hut
3. Use the building tool to place a Simple Park blueprint
4. Check the required resources at the builder's hut

### PR DESCRIPTION
**Pull request by xavierh**
Closes #771 

# Changes proposed in this pull request:
- Fix eggs monster
Review please

### CODE REVIEW

**Comment by marchermans** [comment]
Why does this PR exist twice? Duplicate off: #804 ?

**Comment by xavierh** [comment]
One for develop and one for version/1.11

**Comment by marchermans** [comment]
Ah okey.
Can you pull in the latest changes from develop, TeamCity is not compiling it as it is missing a critical component for the analysis?

**Comment by xavierh** [comment]
Ok I thought I did. Will do it soonish

**Comment by xavierh** [comment]
done

**Pull request merged**
