### PR TITLE
Fix compost barrel models

### PR DESCRIPTION
**Pull request by Sandriell**
# Changes proposed in this pull request:

Updated compost barrel block models to fix issues with compost not being visible through the "window". Also fixed issues with textures missing from some visible faces, tweaked the UV numbers, and set non-visible faces to transparent where appropriate.

This is my first time doing a pull request with github, so hopefully this works fine! :)

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
oh neat, ty for the pr

**Review by Raycoms — APPROVED** [review]

**Review by Mekle001 — APPROVED** [review]

**Comment by oddrobbia** [comment]
The compost part inside the composter barrer side view texture somehow setted to blank i fix it right now

**Comment by Sandriell** [comment]
> The compost part inside the composter barrer side view texture somehow setted to blank i fix it right now

Not sure what you mean? The compost faces are using "minecolonies:blocks/barrel_block/compost" for the texture.

**Comment by oddrobbia** [comment]
> > The compost part inside the composter barrer side view texture somehow setted to blank i fix it right now
> 
> Not sure what you mean? The compost faces are using "minecolonies:blocks/barrel_block/compost" for the texture.

I loaded the models in the model maker and the compost model element only the top have texture setting the other parts now idk how its supposted to work if the compost all sides not have seted the texture only top

**Comment by Sandriell** [comment]
> > > The compost part inside the composter barrer side view texture somehow setted to blank i fix it right now
> > 
> > 
> > Not sure what you mean? The compost faces are using "minecolonies:blocks/barrel_block/compost" for the texture.
> 
> I loaded the models in the model maker and the compost model element only the top have texture setting the other parts now idk how its supposted to work if the compost all sides not have seted the texture only top

Only two faces are ever visible for the compost portion, north and up, the others are all set to transparent.

**Comment by oddrobbia** [comment]
Yeah but i checked the 1.15 to and there is to only the top have texture

**Comment by Sandriell** [comment]
Sorry, I still don't understand what issue you are seeing? This is a screenshot from 1.15.2:

**Pull request merged**
