### PR TITLE
Courier delivers only necesary items

### PR DESCRIPTION
**Pull request by ImEr1c**
# Changes proposed in this pull request:
-Made the delivery man / courier deliver only the requested items with the right amounts

Review please

### CODE REVIEW

**Comment by ImEr1c** [comment]
Is it ok?

**Comment by Thodor12** [comment]
You do realize you can just push more commits to an existing PR and update them, you don't have to redo the PR each time

**Comment by ImEr1c** [comment]
Im new to github.. i dont know much

**Comment by ImEr1c** [comment]
Raycoms said to re-make the PR

**Comment by Thodor12** [comment]
Odd but ok, CLA should still be rechecked on every push

**Comment by ImEr1c** [comment]
I tried this code in creative and it works but if the courier picks up one of the items that he already have, it would stack up so it would transfer that item, thats why i made that map before and all that complicated stuff, to deliver the right amounts

**Comment by ImEr1c** [comment]
im going to wait for a review

**Review by Raycoms — APPROVED** [review]

**Comment by Raycoms** [comment]
> I tried this code in creative and it works but if the courier picks up one of the items that he already have, it would stack up so it would transfer that item, thats why i made that map before and all that complicated stuff, to deliver the right amounts

That's not a problem, usually players also give a bit more than needed, the problem is rather the "random crap" stuff.

**Comment by Raycoms** [comment]
Did you test this?

**Review by someaddons — APPROVED** [review]

**Comment by ImEr1c** [comment]
Yes

**Pull request merged**
