### PR TITLE
More pathblocks

### PR DESCRIPTION
**Pull request by ravenbuilder934**
Closes #
Closes #
Closes #

# Changes proposed in this pull request:
- Adds a lot of new pathblocks
- I probably missed some
-

Review please

### CODE REVIEW

**Comment by MatthiasMann** [comment]
I think stone brick stairs should stay - as it was the only way to make a path on hilly terrain so far and many colonies (including mine) use them.

**Comment by someaddons** [comment]
I wanted to exclude the stairs as path blocks give a speed bonus, which doesnt fit going upstairs as that should be slower, pathing should already prefer stair blocks over others

**Comment by someaddons** [comment]
ok think its better to do the speed modification another way, raven re-add the stairs please :D

**Comment by MatthiasMann** [comment]
Would it be possible to check if the top side of the block is solid to determine speed? or would that cause issues with the grass path?

**Comment by someaddons** [comment]
made it simpler, citizens just are a bit slower when changing y levels and dont get the path speed bonus there

**Review by Mekle001 — DISMISSED** [review]

**Review by Mekle001 — APPROVED** [review]

**Pull request merged**
