### PR TITLE
Eat when saturation at 0 either way!

### PR DESCRIPTION
**Pull request by Raycoms**
Review please

### CODE REVIEW

**Comment by someaddons** [comment]
I think this might be a bad idea, since the purpose of the eating flag is to protect the current AI task. Maybe just change some of the flags instead?

**Comment by Raycoms** [comment]
The idea of the eating flag for me is "in this state it's not nice to eat" but if the saturation dropped to 0 he should eat either way imo else he will get stuck there.

**Comment by someaddons** [comment]
hm technically the eating isnt vital since its just a stat, but interrupting an AI for it might be

**Review by marchermans — APPROVED** [review]

**Comment by Raycoms** [comment]
I know what you're trying to get at.
But stopping to eat something is actually not much of an issue, previously he would even change his state just to eat something every time.
For me, the states marked as "not for eating" is more because "it wouldn't be very good if he would eat right now"
But I believe, also for reasons of immersion. Always when he reaches 0 he should go after food no matter what.

**Comment by Raycoms** [comment]
A lot of people were reporting their citizens being on 0 hunger and not eating anything

**Comment by someaddons** [comment]
ye we can do it this way, although its more of an force overrule than integration. Afaik the issue with starving citizens is that the Waiting for a request status doesnt allow them to eat

**Comment by Raycoms** [comment]
The most common one was the issue in request state (since that one is the
most common) but we also already got complains with a lot of the other
states (basically ordered by how common the state is)
People are just bothered by a worker not eating anything when their
saturation hits 0.

>

**Comment by Raycoms** [comment]
It gets worse when we add one day that they take damage if they are at 0. So we should make sure that after a minimum limit they always go to eat no matter what.

**Review by someaddons — APPROVED** [review]

**Pull request merged**
