### PR TITLE
DRAFT: Information Tabs and Advancements

### PR DESCRIPTION
**Pull request by Asherslab**
# Changes proposed in this pull request:
- Adds in Advancements as a form of Guide through the mod
- Adds in Information Tabs in hut UIs for easier access to information about buildings

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
@Asherslab did you fix this?

**Comment by Asherslab** [comment]
@raycoms yeah fixed it ages ago, no one did the proofreading though

**Comment by Raycoms** [comment]
@OrionDevelopment can you review this. For me it looks fine, players find it fine too, I think we can finally merge this.

**Comment by marvin-bitterlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/api/java/com/minecolonies/api/util/AdvancementUtils.java  5
- src/api/java/com/minecolonies/api/advancements/click_gui_button/ClickGuiButtonCriterionInstance.java  4
- src/main/java/com/minecolonies/coremod/network/messages/ClickGuiButtonTriggerMessage.java  1
- src/api/java/com/minecolonies/api/advancements/colony_population/ColonyPopulationTrigger.java  2
- src/api/java/com/minecolonies/api/advancements/colony_population/ColonyPopulationListeners.java  1
- src/api/java/com/minecolonies/api/advancements/open_gui_window/OpenGuiWindowTrigger.java  2
- src/api/java/com/minecolonies/api/advancements/place_supply/PlaceSupplyCriterionInstance.java  1
- src/api/java/com/minecolonies/api/advancements/complete_build_request/CompleteBuildRequestCriterionInstance.java  7
- src/api/java/com/minecolonies/api/advancements/open_gui_window/OpenGuiWindowCriterionInstance.java  2
- src/api/java/com/minecolonies/api/advancements/place_structure/PlaceStructureCriterionInstance.java  3
- src/api/java/com/minecolonies/api/advancements/CriterionListeners.java  3
- src/api/java/com/minecolonies/api/advancements/complete_build_request/CompleteBuildRequestListeners.java  1
- src/api/java/com/minecolonies/api/advancements/complete_build_request/CompleteBuildRequestTrigger.java  5
- src/api/java/com/minecolonies/api/advancements/place_supply/PlaceSupplyTrigger.java  2
- src/api/java/com/minecolonies/api/advancements/building_add_recipe/BuildingAddRecipeListeners.java  1
- src/api/java/com/minecolonies/api/advancements/create_build_request/CreateBuildRequestListeners.java  1
- src/main/java/com/minecolonies/coremod/network/messages/BuildToolPlaceMessage.java  1
- src/main/java/com/minecolonies/coremod/colony/workorders/WorkManager.java  2
- src/api/java/com/minecolonies/api/advancements/AdvancementTriggers.java  1
- src/main/java/com/minecolonies/coremod/network/messages/OpenGuiWindowTriggerMessage.java  1
- src/api/java/com/minecolonies/api/advancements/place_supply/PlaceSupplyListeners.java  1
- src/api/java/com/minecolonies/api/advancements/place_structure/PlaceStructureListeners.java  1
- src/api/java/com/minecolonies/api/advancements/create_build_request/CreateBuildRequestTrigger.java  5
- src/api/java/com/minecolonies/api/advancements/citizen_eat_food/CitizenEatFoodTrigger.java  3
- src/api/java/com/minecolonies/api/advancements/citizen_eat_food/CitizenEatFoodCriterionInstance.java  4
- src/api/java/com/minecolonies/api/advancements/open_gui_window/OpenGuiWindowListeners.java  1
- src/api/java/com/minecolonies/api/advancements/create_build_request/CreateBuildRequestCriterionInstance.java  7
- src/api/java/com/minecolonies/api/advancements/place_structure/PlaceStructureTrigger.java  3
- src/api/java/com/minecolonies/api/advancements/click_gui_button/ClickGuiButtonTrigger.java  3
- src/api/java/com/minecolonies/api/advancements/click_gui_button/ClickGuiButtonListeners.java  1
- src/api/java/com/minecolonies/api/advancements/building_add_recipe/BuildingAddRecipeTrigger.java  3
- src/api/java/com/minecolonies/api/advancements/building_add_recipe/BuildingAddRecipeCriterionInstance.java  5
- src/api/java/com/minecolonies/api/advancements/citizen_eat_food/CitizenEatFoodListeners.java  1
- src/api/java/com/minecolonies/api/advancements/colony_population/ColonyPopulationCriterionInstance.java  1
- src/api/java/com/minecolonies/api/advancements/AbstractCriterionTrigger.java  3
         

Clones added
============
- src/api/java/com/minecolonies/api/advancements/complete_build_request/CompleteBuildRequestCriterionInstance.java  1
- src/api/java/com/minecolonies/api/advancements/create_build_request/CreateBuildRequestCriterionInstance.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/minecolonies/minecolonies/pullRequest?prid=4336169&bid=14746340)

**Comment by Asherslab** [comment]
@raycoms you think the translation strings are fine? (Space does too?)

**Comment by Raycoms** [comment]
@Asherslab I think they look fine, space got no muse to do so atm. So I'd say we merge it now, and can adjust them later still without a problem. Code is the most difficult part, adjusting lang strings is easy.

**Comment by marchermans** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/3944/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Comment by Asherslab** [comment]
Agreed on that ray, just making sure lol

**Comment by Raycoms** [comment]
:shipit: then

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/3944/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Pull request merged**
