### PR TITLE
add postbox block and stash block blueprints to infrastructure section.

### LINKED ISSUE #449: Add blueprints for Postbox and Stash to the infrastructure section build blueprints menu
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.14.197-ALPHA
- Related Mods and their Versions:

## Is your feature request related to a problem?

When designing structures one cannot manually place either the Postbox or the Stash without being in a colony. For other blocks like this (eg all the Hut blocks) there is a single block schematic containing just that block. Having to spin up a colony just to place a Postbox or Stash is frustrating.

## Enhancement or Change description

1. Add a single block schematic containing just the Postbox block
2. Add a signal block schematic containing just the Stash block

### Notes or related things

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by dupontct**
Closes ldtteam/minecolonies-features#449

# Changes proposed in this pull request:
- Add Postbox block schematic blueprint
- Add Stash block schematic blueprint

Review please

### CODE REVIEW

**Review by ravenbuilder934 — APPROVED** [review]

**Comment by marchermans** [comment]
Not relevant these blocks are not supposed to be placed by a wand and will most likely break if attempted.

**Review by marchermans — CHANGES_REQUESTED** [review]
Not functionally relevant. They are designed to be player placeable and don't need a wand

**Comment by Raycoms** [comment]
I don't see a reason for this either.

**Comment by uecasm** [comment]
Like the other schematics in the infrastructure/hutblocks folder, it would be needed if you wanted to include a stash/postbox in another schematic scan (since you're supposed to construct those outside of an active colony, and you can't place these blocks normally outside a colony), as mentioned in the linked feature request...

**Comment by Raycoms** [comment]
ohh, they are in the hutblocks folder, I totally overlooked that, sorry

**Review by Raycoms — APPROVED** [review]

**Comment by Raycoms** [comment]
That folder places non functional hut blocks.

**Comment by dupontct** [comment]
Do I need to do anything to satisfy OrionDevelopment's change request?

**Comment by marchermans** [comment]
Approved then

**Comment by dupontct** [comment]
These blueprints were taken of the postbox and stash blocks inside a colony. Does that matter?

I could update the schematics to be of the blocks but placed with the /setblock command

**Comment by Raycoms** [comment]
> These blueprints were taken of the postbox and stash blocks inside a colony. Does that matter?
> 
> I could update the schematics to be of the blocks but placed with the /setblock command

No, will be fine, that folder has special rules

**Comment by Raycoms** [comment]
Solved in other pr

**Pull request closed without merging**
