### PR TITLE
Several fixes

### LINKED ISSUE #4550: Requests disappear from Postbox randomly as if canceled
### Minecolonies version

Version: minecolonies-0.11.785-BETA-universal

### Expected behavior

when entering a request for something in the postbox, it would be expected to activate a delivery man or other workers as needed to deliver the requested item to the postbox. 
### Actual behavior

when I type in a block or item in the post box, I specify the amount and hit enter. Sometimes it works, most times it doesn't. The request will show up in the list of requests and sometimes stay there until the item is delivered, but most times it will just randomly disappear with no reason as to why. It acts like I canceled the request. This happens with both big and small orders, and when the selected item is in the warehouse and just needs to be delivered to the postbox, and also when it needs to be crafted by a separate worker and then delivered to the postbox. 

[Postbox Error.zip](https://github.com/ldtteam/minecolonies/files/4418225/Postbox.Error.zip)

### Steps to reproduce the problem

since its random, it's hard to reproduce, but these are the steps that I do in order for it to happen.

1. open postbox
2. select an item and type the amount
3. hit request
4. the time it takes for it to happen varies but it's usually 30 seconds to 1:30. when it does happen you'll open the postbox and see your request gone and the item not delivered. 

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: [latest.log](https://github.com/ldtteam/minecolonies/files/4418258/latest.log)
- crashlog: [crash-2019-10-13_17.19.04-client.txt](https://github.com/ldtteam/minecolonies/files/4418261/crash-2019-10-13_17.19.04-client.txt)
this crash report is old but it's the latest one I have.

### LINKED ISSUE #4559: [1.15.2]Server crash
### Minecolonies version
790

Version: 
1.15.2
### Expected behavior
I don't know how he happened

[debug.log](https://github.com/ldtteam/minecolonies/files/4424942/debug.log)
[crash-2020-04-02_23.22.56-server.txt](https://github.com/ldtteam/minecolonies/files/4424945/crash-2020-04-02_23.22.56-server.txt)

### LINKED ISSUE #4562: Lumberjack exception
### Minecolonies version

Version: minecolonies-0.11.802-BETA-universal

Lumberjack threw several AI exceptions, see attached log file. I like the in-game error message, makes knowing when to report much easier. Game did not crash, and other citizens kept going.

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: 
[latest.log](https://github.com/ldtteam/minecolonies/files/4425842/latest.log)

- crashlog:

### LINKED ISSUE #4563: University research and effect
### Minecolonies version

Version: Newest

### Expected behavior

Should show the actual benefit of the research, and display an error message when the university level is too low
- 

### Actual behaviour

image
Says +50 damage but in reality it is +0.5

Clicking an university research which needs a higher university level doesnt have any error message.
-

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #4550
Closes #4559
Closes #4562
Closes #4563

# Changes proposed in this pull request:
- Improve university button description
- Fix crash
- Add "failed" request state
- Fix tree crashes

Review please

### CODE REVIEW

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAICrafting.java  1
- src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/PostBox.java  2
- src/main/java/com/minecolonies/coremod/commands/citizencommands/CommandCitizenTriggerWalkTo.java  7
- src/main/java/com/minecolonies/coremod/commands/citizencommands/CommandCitizenTeleport.java  7
- src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRequestManager.java  1
         

Clones added
============
- src/main/java/com/minecolonies/coremod/commands/citizencommands/CommandCitizenTriggerWalkTo.java  2
- src/main/java/com/minecolonies/coremod/commands/citizencommands/CommandCitizenTeleport.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=5302613&bid=17355180)

**Review by someaddons — DISMISSED** [review]

**Review by marchermans — CHANGES_REQUESTED** [review]
When you create the retry request in the postbox please also copy the count.

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/commands/citizencommands/CommandCitizenTeleport.java  7
- src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRequestManager.java  1
- src/main/java/com/minecolonies/coremod/commands/citizencommands/CommandCitizenTriggerWalkTo.java  7
- src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/PostBox.java  2
- src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAICrafting.java  1
         

Clones added
============
- src/main/java/com/minecolonies/coremod/commands/citizencommands/CommandCitizenTeleport.java  2
- src/main/java/com/minecolonies/coremod/commands/citizencommands/CommandCitizenTriggerWalkTo.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=5302613&bid=17355180)

**Review by marchermans — DISMISSED** [review]

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/PostBox.java  2
- src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAICrafting.java  1
- src/main/java/com/minecolonies/coremod/commands/citizencommands/CommandCitizenTeleport.java  7
- src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRequestManager.java  1
- src/main/java/com/minecolonies/coremod/commands/citizencommands/CommandCitizenTriggerWalkTo.java  7
         

Clones added
============
- src/main/java/com/minecolonies/coremod/commands/citizencommands/CommandCitizenTeleport.java  2
- src/main/java/com/minecolonies/coremod/commands/citizencommands/CommandCitizenTriggerWalkTo.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=5302613&bid=17355180)

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/PostBox.java  2
- src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAICrafting.java  1
- src/main/java/com/minecolonies/coremod/commands/citizencommands/CommandCitizenTeleport.java  7
- src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRequestManager.java  1
- src/main/java/com/minecolonies/coremod/commands/citizencommands/CommandCitizenTriggerWalkTo.java  7
         

Clones added
============
- src/main/java/com/minecolonies/coremod/commands/citizencommands/CommandCitizenTeleport.java  2
- src/main/java/com/minecolonies/coremod/commands/citizencommands/CommandCitizenTriggerWalkTo.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=5302613&bid=17355180)

**Review by someaddons — DISMISSED** [review]

**Review by marchermans — DISMISSED** [review]

**Comment by marvin-bitterlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/commands/citizencommands/CommandCitizenTeleport.java  7
- src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAICrafting.java  1
- src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/PostBox.java  2
- src/main/java/com/minecolonies/coremod/colony/requestsystem/management/manager/StandardRequestManager.java  1
- src/main/java/com/minecolonies/coremod/commands/citizencommands/CommandCitizenTriggerWalkTo.java  7
         

Clones added
============
- src/main/java/com/minecolonies/coremod/commands/citizencommands/CommandCitizenTeleport.java  2
- src/main/java/com/minecolonies/coremod/commands/citizencommands/CommandCitizenTriggerWalkTo.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=5302613&bid=17355180)

**Pull request merged**
