### PR TITLE
Hotfix building tool is null! issue

### LINKED ISSUE #3885: Building is null issue - version 0.10.393-ALPHA / 0.10.396
### Minecolonies version
version 0.10.393-ALPHA

Version: 

### Expected behavior
Expect town hall lectern to be placed and be useable.

When trying to place a new town hall using the buidling tool I have set the template to what should be the correct area, double checked the area for drops, planets and missing bricks. I have confirmed the building. expect town hall to place and book to be useable.
 

### Actual behaviour
Town Hall Lectern appears but is not useable

When trying to place a new town hall using the buidling tool I have set the template to what should be the correct area, double checked the area for drops, planets and missing bricks. I have confirmed the building. Lectern (town hall book block) appears on its own or floating in the air, i try to right click on it to use it - nothing happens.  

server log prints out this exception :  [Server thread/ERROR] [minecolonies/]: BuildTool: building is null!

in addition, when then trying to place a builders hut, it states that i need to place a townhall first.
which i have already done.

I am trying to place in a badlands biome

### Steps to reproduce the problem

1. construct camp, 
2. retrieve townhall and building tool from chest
3. attempt to place town hall.
4. ... Profit

### PR DESCRIPTION
**Pull request by someaddons**
Closes #3885

# Changes proposed in this pull request:
-Fixes building tool null issue, shields in offhand became active on rightclick and changed the active hand to offhand

### CODE REVIEW

**Comment by marvin-bitterlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/main/java/com/minecolonies/coremod/blocks/huts/BlockHutTownHall.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Minecolonies/minecolonies/pullRequest?prid=4630878&bid=15522401)

**Comment by Asherslab** [comment]
1.12 port?

**Comment by Raycoms** [comment]
We never got the report in 1.12

**Comment by Asherslab** [comment]
We’ve had it tonnes of times

**Comment by Raycoms** [comment]
Really? Those reports only started coming in with 1.14 though

**Comment by Asherslab** [comment]
@raycoms nah we were receiving them before 1.14

**Pull request merged**
