### PR TITLE
Enables citizens to use lever to toggle T-cross railway

### PR DESCRIPTION
**Pull request by HexatomicRing**
Citizens now are able to toggle the direction of a RailBlock using the Lever next to it. There only exists a small chance that more than one citizens are on the same rail block in one tick that they may go to wrong direction.
Let citizens use railways more efficiently!

## Testing
- [√] Yes I tested this before submitting it.
- [×] I also did a multiplayer test.

Review please

// Sorry that I deleted my fork by mistake, so I had to re-create this pull request😭.

### CODE REVIEW

**Comment by Raycoms** [comment]
This should probably not be a goal, but should be handled by the pathfollow mechanism + should not need a lever even (just auto rotate the rail)

**Comment by HexatomicRing** [comment]
> This should probably not be a goal, but should be handled by the pathfollow mechanism + should not need a lever even (just auto rotate the rail)

Yes, in future versions, due to the adjustable speed of the mining car, continuing to use Goal will have a certain probability of failure. I will modify my code later.
In addition, if two citizens heading in different directions pass through the same railway track in the same tick, one citizen will go in the wrong direction. Then he will walk the rest path instead of using a minecart. I haven't figured out how to treat this situation yet.

**Comment by Raycoms** [comment]
> > This should probably not be a goal, but should be handled by the pathfollow mechanism + should not need a lever even (just auto rotate the rail)
> 
> Yes, in future versions, due to the adjustable speed of the mining car, continuing to use Goal will have a certain probability of failure. I will modify my code later. In addition, if two citizens heading in different directions pass through the same railway track in the same tick, one citizen will go in the wrong direction. Then he will walk the rest path instead of using a minecart. I haven't figured out how to treat this situation yet.

There is also the option of ignoring the rail and telling the railcart entity the junctions at which it would have to change direction.

**Comment by someaddons** [comment]
better solution would be a T cross rail block :D

**Comment by Raycoms** [comment]
> better solution would be a T cross rail block :D

Agreed, but it would still require at least to tell the cart which direction to go =D

**Pull request closed without merging**
