### PR TITLE
Feature/1.10 better chat (#994)

### PR DESCRIPTION
**Pull request by xavierh**
* Suppress some warning

* Add worker name to the message when chest is full

* remove warnings

* Builder say when then start/end a job

* Shorter chat version for colony owner

* D-man only say that the chest if full when ihe cannot swap
D-man say whose chest is full

* Change dman saying

* Compare itemstack properly

* Different message when pick axe requested level is greater than hut level

* D-man hold the item he will deliver or the item he did gather
Fix javadoc

* EntityCitizen does not know about BuildingFarmer now

* remove most of the Jobs from EnityCitizen

* dman hold the correct item
Review please

### CODE REVIEW

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 71 issues
* ![MAJOR][MAJOR] 24 major
* ![MINOR][MINOR] 43 minor
* ![INFO][INFO] 4 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L90](https://github.com/Minecolonies/minecolonies/blob/60882d1273b5031f2f1ecfee33d175ac8bd454f8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L90): Remove this unused method parameter "stack". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L264](https://github.com/Minecolonies/minecolonies/blob/60882d1273b5031f2f1ecfee33d175ac8bd454f8/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L264): Reduce this class from 32 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [BuildingFarmer.java#L505](https://github.com/Minecolonies/minecolonies/blob/60882d1273b5031f2f1ecfee33d175ac8bd454f8/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java#L505): Reduce this class from 86 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/60882d1273b5031f2f1ecfee33d175ac8bd454f8/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.285 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L60](https://github.com/Minecolonies/minecolonies/blob/60882d1273b5031f2f1ecfee33d175ac8bd454f8/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L60): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 57 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L60](https://github.com/Minecolonies/minecolonies/blob/60882d1273b5031f2f1ecfee33d175ac8bd454f8/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L60): class "EntityCitizen" has 94 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L345](https://github.com/Minecolonies/minecolonies/blob/60882d1273b5031f2f1ecfee33d175ac8bd454f8/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L345): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L346](https://github.com/Minecolonies/minecolonies/blob/60882d1273b5031f2f1ecfee33d175ac8bd454f8/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L346): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L346](https://github.com/Minecolonies/minecolonies/blob/60882d1273b5031f2f1ecfee33d175ac8bd454f8/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L346): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L347](https://github.com/Minecolonies/minecolonies/blob/60882d1273b5031f2f1ecfee33d175ac8bd454f8/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L347): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 70 issues
* ![MAJOR][MAJOR] 24 major
* ![MINOR][MINOR] 42 minor
* ![INFO][INFO] 4 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L90](https://github.com/Minecolonies/minecolonies/blob/468aeddfe5bff4117ed78e0ada4fce8b86ecf82c/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L90): Remove this unused method parameter "stack". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L264](https://github.com/Minecolonies/minecolonies/blob/468aeddfe5bff4117ed78e0ada4fce8b86ecf82c/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L264): Reduce this class from 32 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [BuildingFarmer.java#L505](https://github.com/Minecolonies/minecolonies/blob/468aeddfe5bff4117ed78e0ada4fce8b86ecf82c/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java#L505): Reduce this class from 86 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/468aeddfe5bff4117ed78e0ada4fce8b86ecf82c/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.285 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L60](https://github.com/Minecolonies/minecolonies/blob/468aeddfe5bff4117ed78e0ada4fce8b86ecf82c/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L60): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 57 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L60](https://github.com/Minecolonies/minecolonies/blob/468aeddfe5bff4117ed78e0ada4fce8b86ecf82c/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L60): class "EntityCitizen" has 94 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L345](https://github.com/Minecolonies/minecolonies/blob/468aeddfe5bff4117ed78e0ada4fce8b86ecf82c/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L345): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L346](https://github.com/Minecolonies/minecolonies/blob/468aeddfe5bff4117ed78e0ada4fce8b86ecf82c/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L346): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L346](https://github.com/Minecolonies/minecolonies/blob/468aeddfe5bff4117ed78e0ada4fce8b86ecf82c/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L346): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L347](https://github.com/Minecolonies/minecolonies/blob/468aeddfe5bff4117ed78e0ada4fce8b86ecf82c/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L347): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Raycoms** [comment]
:shipit: did you test it on 1.10?

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1007/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by xavierh** [comment]
@Raycoms not yet doing it tonight

**Comment by xavierh** [comment]
@Raycoms tested and working well

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 68 issues
* ![MAJOR][MAJOR] 24 major
* ![MINOR][MINOR] 40 minor
* ![INFO][INFO] 4 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L90](https://github.com/Minecolonies/minecolonies/blob/78c68935ebe8e781b9397683e1c4219fa145b3f2/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L90): Remove this unused method parameter "stack". [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1172)
1. ![MAJOR][MAJOR] [AbstractBuildingWorker.java#L264](https://github.com/Minecolonies/minecolonies/blob/78c68935ebe8e781b9397683e1c4219fa145b3f2/src/main/java/com/minecolonies/coremod/colony/buildings/AbstractBuildingWorker.java#L264): Reduce this class from 32 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [BuildingFarmer.java#L505](https://github.com/Minecolonies/minecolonies/blob/78c68935ebe8e781b9397683e1c4219fa145b3f2/src/main/java/com/minecolonies/coremod/colony/buildings/BuildingFarmer.java#L505): Reduce this class from 86 to the maximum allowed 30 or externalize it in a public class. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2972)
1. ![MAJOR][MAJOR] [EntityCitizen.java](https://github.com/Minecolonies/minecolonies/blob/78c68935ebe8e781b9397683e1c4219fa145b3f2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java): This file has 1.285 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L60](https://github.com/Minecolonies/minecolonies/blob/78c68935ebe8e781b9397683e1c4219fa145b3f2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L60): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 57 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L60](https://github.com/Minecolonies/minecolonies/blob/78c68935ebe8e781b9397683e1c4219fa145b3f2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L60): class "EntityCitizen" has 94 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L345](https://github.com/Minecolonies/minecolonies/blob/78c68935ebe8e781b9397683e1c4219fa145b3f2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L345): Assign this magic number 3.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L346](https://github.com/Minecolonies/minecolonies/blob/78c68935ebe8e781b9397683e1c4219fa145b3f2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L346): Assign this magic number 5.0F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L346](https://github.com/Minecolonies/minecolonies/blob/78c68935ebe8e781b9397683e1c4219fa145b3f2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L346): Assign this magic number 0.02F to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [EntityCitizen.java#L347](https://github.com/Minecolonies/minecolonies/blob/78c68935ebe8e781b9397683e1c4219fa145b3f2/src/main/java/com/minecolonies/coremod/entity/EntityCitizen.java#L347): Assign this magic number 0.6D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1007/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by marvin-bitterlich** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1007/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Pull request merged**
