### PR TITLE
Minor improvement and fix to some worker models

### PR DESCRIPTION
**Pull request by carlansor**
# Changes proposed in this pull request:
-Fixed hat in male model not attached to bipedHead
-Added an extra layer for the head.
-Separated boots detail to not overlap with the hat in the male model.
-Fixed textures to match these changes.
-Fixed uv overlapping and texture issues with beekeper, concrete mixer, and rabbit herder

Review please

### CODE REVIEW

**Review by marchermans — CHANGES_REQUESTED** [review]
Your build is failing.
Please fix the code.

**Comment by carlansor** [comment]
i believe all code is as it should be now

**Review by marchermans — DISMISSED** [review]

**Comment by carlansor** [comment]
sorry i merged more model fixes, didnt know a couple of things about gith.

**Comment by marchermans** [comment]
Fix the merge conflicts.

**Comment by carlansor** [comment]
how do i fix conflicting files? i dont have write access.

**Comment by Raycoms** [comment]
Let me close this and reopen a new one I'll work on then

**Pull request closed without merging**
