### PR TITLE
Builder considers Grass as Dirt

### LINKED ISSUE #3265: fix Builder should consider grass as dirt
### Expected behavior

Builder threats grass as dirt

### Actual behaviour

Builder picks up one dirt block at a time and places it.
 

### Steps to reproduce the problem

Build a building in which the builder has to place grass.

### PR DESCRIPTION
**Pull request by schafhierte204**
Closes #3265 

# Changes proposed in this pull request:
-Builder treats grass like dirt

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
Not sure what you mean the problem is, that the list of resources on page 2 shows grass but he actually only needs dirt?

**Comment by schafhierte204** [comment]
The Problem is that he runs back to his hut and picks up a dirt block every time he needs to place a grass block

**Comment by Raycoms** [comment]
Ahhh, now I understand what you mean. Did you test this, did this patch solve this problem for you?

**Comment by schafhierte204** [comment]
I have the game running at the moment and the problem is gone.

**Comment by schafhierte204** [comment]
The only minor side affect is that the grass blocks now show up as dirt in the resource list

**Comment by Raycoms** [comment]
Can you fix the parenthesis to go down? like:
{

}

**Pull request merged**
