### PR TITLE
Bugfixes ported to 1.12

### PR DESCRIPTION
**Pull request by someaddons**
## Changes proposed in this pull request:
Ported various small bugfixes and the fake citizen fix to 1.12

Fixes:
Fake Citizens
Structure despawn errors
ItemstackUtils NBT matching
Some Interactions
ResourceList crash
Eventhandler removal on world unload
Crusher requesting recipes
setDelay pathing/lag removed
Improved efficient tool detection
Fixed Eating AI lag
Fix pathing using ladders when only running by

Review please

### CODE REVIEW

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java  1
- src/main/java/com/minecolonies/coremod/util/WorkerUtil.java  3
- src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCrusher.java  1
- src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenColonyHandler.java  1
         

Complexity decreasing per file
==============================
+ src/main/java/com/minecolonies/coremod/colony/ColonyManagerWorldAccess.java  -1
+ src/main/java/com/minecolonies/coremod/colony/CitizenData.java  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=5213568&bid=17095110)

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/util/WorkerUtil.java  3
- src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCrusher.java  1
- src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenColonyHandler.java  1
- src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java  1
         

Complexity decreasing per file
==============================
+ src/main/java/com/minecolonies/coremod/colony/ColonyManagerWorldAccess.java  -1
+ src/main/java/com/minecolonies/coremod/network/messages/RecallCitizenMessage.java  -2
+ src/main/java/com/minecolonies/coremod/colony/CitizenData.java  -6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=5213568&bid=17095110)

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java  1
- src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenColonyHandler.java  1
- src/main/java/com/minecolonies/coremod/util/WorkerUtil.java  3
- src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCrusher.java  1
         

Complexity decreasing per file
==============================
+ src/main/java/com/minecolonies/coremod/colony/ColonyManagerWorldAccess.java  -1
+ src/main/java/com/minecolonies/coremod/colony/CitizenData.java  -6
+ src/main/java/com/minecolonies/coremod/network/messages/RecallCitizenMessage.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=5213568&bid=17095110)

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenColonyHandler.java  1
- src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCrusher.java  1
- src/main/java/com/minecolonies/coremod/util/WorkerUtil.java  3
- src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java  1
         

Complexity decreasing per file
==============================
+ src/main/java/com/minecolonies/coremod/colony/CitizenData.java  -6
+ src/main/java/com/minecolonies/coremod/colony/ColonyManagerWorldAccess.java  -1
+ src/main/java/com/minecolonies/coremod/network/messages/RecallCitizenMessage.java  -2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=5213568&bid=17095110)

**Comment by marvin-bitterlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenColonyHandler.java  1
- src/main/java/com/minecolonies/coremod/util/WorkerUtil.java  3
- src/main/java/com/minecolonies/coremod/entity/ai/minimal/EntityAIEatTask.java  1
- src/main/java/com/minecolonies/coremod/colony/buildings/workerbuildings/BuildingCrusher.java  1
         

Complexity decreasing per file
==============================
+ src/main/java/com/minecolonies/coremod/network/messages/RecallCitizenMessage.java  -2
+ src/main/java/com/minecolonies/coremod/colony/CitizenData.java  -6
+ src/main/java/com/minecolonies/coremod/colony/ColonyManagerWorldAccess.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=5213568&bid=17095110)

**Pull request merged**
