### PR TITLE
Improve/fix some chunk data issues

### PR DESCRIPTION
**Pull request by someaddons**
# Changes proposed in this pull request:
- made sure the chunk is mark dirty whenever the capability data changes
- removed unecessary chunk load counter which goes out of sync and could cause orphaned chunks
- changed backup loading to not re-claim all colonies when auto-reloading
- Fixed three more chunk cache merging issues, where we didnt end up with the correct data.
- Chunk-cache claims are now done in-order to avoid information loss and end up with the correct data.

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/4036/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Review by Asherslab — DISMISSED** [review]
Looks good to me, only question is if there’s an IChunk interface or something similar we can use instead, just for greater compatibility with mods that may change that, if not then sure.

**Comment by someaddons** [comment]
they added the IChunk stuff with 1.14^^

**Comment by Asherslab** [comment]
ahh, well then in the 1.14 port if you could use that instead that'd be great

**Comment by someaddons** [comment]
ye I'll try to use it where possible, I remember the interface has a few missing functions yet :D

**Comment by someaddons** [comment]
seems I've found another bug, don't merge it yet xD

**Comment by someaddons** [comment]
Ready to be reviewed again :)

**Comment by Raycoms** [comment]
:shipit: amazing work on this, great job on finding these small bugs by debugging it over and over and over... =D

@OrionDevelopment @Asherslab

**Review by marchermans — APPROVED** [review]

**Pull request merged**
