### PR TITLE
Ai exception

### LINKED ISSUE #4496: Farmer requesting axe for farming
### Minecolonies version

Version: 0.11.788-ALPHA

### Expected behavior

-Farmer to use a hoe to farm instead of using an axe 

### Actual behaviour

- Farmer constantly requests an axe to farm, while having a hoe in his inventory which he isn't using. Cancelling the request doesn't help.

IMG 1
IMG 2
img 3

### Steps to reproduce the problem

1. Open farmer
2. Look at requests 
3. See Axe instead of Hoe
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

### PR DESCRIPTION
**Pull request by someaddons**
Closes #4496

# Changes proposed in this pull request:
Adds an interaction for AI exceptions, to make issue more recognizeable /easier to report and debug.
Fix efficient tools for blocks without hardness like wheat

Review please

### CODE REVIEW

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/util/WorkerUtil.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=5246898&bid=17195892)

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/4511/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Review by marchermans — DISMISSED** [review]
Good work!

**Comment by marvin-bitterlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/util/WorkerUtil.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/Minecolonies/minecolonies/pullRequest?prid=5246898&bid=17195892)

**Pull request merged**
