### PR TITLE
Added deepslate stuff

### PR DESCRIPTION
**Pull request by anonymous563**
Polished deepslate, deepslate bricks, deepslate tiles
Base block, slabs, and stairs

Closes #
Closes #
Closes #

# Changes proposed in this pull request:
-
-
-

Review please

### CODE REVIEW

**Comment by anonymous563** [comment]
Disclaimer: I don't actually know what the block names are. Please check to make sure they're doing something!

**Comment by uecasm** [comment]
> Disclaimer: I don't actually know what the block names are. Please check to make sure they're doing something!

Use F3+H to include block ids in tooltips, then you can check this yourself.

**Comment by KamilPacanek** [comment]
Any comment why this got reverted? I was going to create PR myself for that.

**Comment by anonymous563** [comment]
This was on 1.16, which doesn't have deepslate. 1.17 has the changes, though.

**Comment by KamilPacanek** [comment]
> This was on 1.16, which doesn't have deepslate. 1.17 has the changes, though.

I must check again when I get back home because last time I was checking, the *.jar file deepslate entries were not there. And I'm on Valhesia 4 (it is on 1.17.1).

**Pull request merged**
