### PR TITLE
fix sign rendering

### PR DESCRIPTION
**Pull request by Raycoms**
Interestingly the sign doesn't rotate if we simulate it in the fakeWorld or in the world.

Review please

### CODE REVIEW

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 38 issues
* ![BLOCKER][BLOCKER] 3 blocker
* ![MAJOR][MAJOR] 3 major
* ![MINOR][MINOR] 32 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![BLOCKER][BLOCKER] [Structure.java#L137](https://github.com/Minecolonies/minecolonies/blob/505ad222cac9be022e7fcf198b9957f2901d34c8/src/main/java/com/minecolonies/structures/helpers/Structure.java#L137): Close this "InputStream" in a "finally" clause. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2095)
1. ![BLOCKER][BLOCKER] [Structure.java#L247](https://github.com/Minecolonies/minecolonies/blob/505ad222cac9be022e7fcf198b9957f2901d34c8/src/main/java/com/minecolonies/structures/helpers/Structure.java#L247): Close this "InputStream" in a "finally" clause. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2095)
1. ![BLOCKER][BLOCKER] [Structure.java#L260](https://github.com/Minecolonies/minecolonies/blob/505ad222cac9be022e7fcf198b9957f2901d34c8/src/main/java/com/minecolonies/structures/helpers/Structure.java#L260): Close this "InputStream" in a "finally" clause. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS2095)
1. ![MAJOR][MAJOR] [Structure.java#L63](https://github.com/Minecolonies/minecolonies/blob/505ad222cac9be022e7fcf198b9957f2901d34c8/src/main/java/com/minecolonies/structures/helpers/Structure.java#L63): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 37 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Structure.java#L464](https://github.com/Minecolonies/minecolonies/blob/505ad222cac9be022e7fcf198b9957f2901d34c8/src/main/java/com/minecolonies/structures/helpers/Structure.java#L464): Assign this magic number 99 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Structure.java#L466](https://github.com/Minecolonies/minecolonies/blob/505ad222cac9be022e7fcf198b9957f2901d34c8/src/main/java/com/minecolonies/structures/helpers/Structure.java#L466): Assign this magic number 500 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/505ad222cac9be022e7fcf198b9957f2901d34c8/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/505ad222cac9be022e7fcf198b9957f2901d34c8/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/505ad222cac9be022e7fcf198b9957f2901d34c8/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/505ad222cac9be022e7fcf198b9957f2901d34c8/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[BLOCKER]: https://sonarsource.github.io/sonar-github/severity-blocker.png 'Severity: BLOCKER'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Asherslab** [comment]
Fakeworld? :shipit:

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1435/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by Raycoms** [comment]
Yeah we need to simulate a world to render things sometimes

**Comment by Asherslab** [comment]
Any chance this also fixes the fact that long messages only show on the first line of the sign (thus being cut off)

**Comment by Raycoms** [comment]
No, this only fixes the positioning

2017-09-09 13:37 GMT+01:00 Asherslab <notifications@github.com>:

> Any chance this also fixes the fact that long messages only show on the
> first line of the sign (thus being cut off)
>

**Comment by Asherslab** [comment]
Okay cool, any chance you are able to fix that too? I was trying to find where to fix that earlier, but yeah. I'm partially blind lol

**Comment by Raycoms** [comment]
I think I won't have the time, but where we write into the sign we could
simply just check if the line is too long and write it on two.

2017-09-09 14:26 GMT+01:00 Asherslab <notifications@github.com>:

> Okay cool, any chance you are able to fix that too? I was trying to find
> where to fix that earlier, but yeah. I'm partially blind lol
>

**Review by marchermans — APPROVED** [review]

**Pull request merged**
