### PR TITLE
Feature/#18 Using Ore Dictionary in crafting recipes

### LINKED ISSUE #18: Using Ore Dictionary in crafting recipes
So, what about adding support for ore dictionary in our crafting recipes.
Could result in better mod compatibility and in less code for creating the crafting
recipes.

Should be checked if this is possible for our use with wooden planks.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/36918921-using-ore-dictionary-in-crafting-recipes?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F43175463&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by carif**
Implemented ore dictionary to crafting recipes.

Closes #18 

# Changes proposed in this pull request:
- Using ore dictionary now in crafting recipes.

Review please

### CODE REVIEW

**Review by marchermans — APPROVED** [review]
Yep should do it.

**Comment by Raycoms** [comment]
Can we make constants for the string literals we use often?
Makes it easier later to add new recipes.

**Comment by marchermans** [comment]
Goddammit i hate laptop mousepads........

**Comment by carif** [comment]
@Raycoms Ok. Just changed it so that we are using constants now. ;)

**Comment by Raycoms** [comment]
:shipit: for me

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/732/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by marvin-bitterlich** [comment]
LGTM!

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/732/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Review by marvin-bitterlich — APPROVED** [review]
Awesome!

**Pull request merged**
