### PR TITLE
adding `./gradlew runClient` to README.md

### PR DESCRIPTION
**Pull request by gluneau**
# Changes proposed in this pull request:

By adding these little suggestions, you make it easier for anyone to get the client running and seeing the project working.

Review please

### CODE REVIEW

**Comment by BuildTeamLinter** [comment]
SonarQube analysis reported 48 issues
* ![MAJOR][MAJOR] 48 major

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [blocks#](https://github.com/Minecolonies/minecolonies/blob/f667e46a9ede46b868294ff823b9249461a69f31/src/main/java/com/minecolonies/coremod/blocks#): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [gui#](https://github.com/Minecolonies/minecolonies/blob/f667e46a9ede46b868294ff823b9249461a69f31/src/main/java/com/minecolonies/coremod/client/gui#): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [render#](https://github.com/Minecolonies/minecolonies/blob/f667e46a9ede46b868294ff823b9249461a69f31/src/main/java/com/minecolonies/coremod/client/render#): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [colony#](https://github.com/Minecolonies/minecolonies/blob/f667e46a9ede46b868294ff823b9249461a69f31/src/main/java/com/minecolonies/coremod/colony#): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [buildings#](https://github.com/Minecolonies/minecolonies/blob/f667e46a9ede46b868294ff823b9249461a69f31/src/main/java/com/minecolonies/coremod/colony/buildings#): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [permissions#](https://github.com/Minecolonies/minecolonies/blob/f667e46a9ede46b868294ff823b9249461a69f31/src/main/java/com/minecolonies/coremod/colony/permissions#): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [requestable#](https://github.com/Minecolonies/minecolonies/blob/f667e46a9ede46b868294ff823b9249461a69f31/src/main/java/com/minecolonies/coremod/colony/requestable#): Add a 'package-info.java' file to document the 'requestable' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [data#](https://github.com/Minecolonies/minecolonies/blob/f667e46a9ede46b868294ff823b9249461a69f31/src/main/java/com/minecolonies/coremod/colony/requestsystem/data#): Add a 'package-info.java' file to document the 'data' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [init#](https://github.com/Minecolonies/minecolonies/blob/f667e46a9ede46b868294ff823b9249461a69f31/src/main/java/com/minecolonies/coremod/colony/requestsystem/init#): Add a 'package-info.java' file to document the 'init' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MAJOR][MAJOR] [locations#](https://github.com/Minecolonies/minecolonies/blob/f667e46a9ede46b868294ff823b9249461a69f31/src/main/java/com/minecolonies/coremod/colony/requestsystem/locations#): Add a 'package-info.java' file to document the 'locations' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by marchermans** [comment]
If you use gradlew then you should use an ide. With idea and eclipse Forge provides support for this directly or indirectly. Anybody else can download the jar.

**Comment by mkienenb** [comment]
Sometimes the situation is such that an IDE isn't required, but running the latest build from gradle is still useful.   That's how I got started last week.  The official launchers were unavailable, so I started it up by downloading the source and using runClient.

Another situation might be to have a savy end-user test a fix.   Telling someone to git clone, gradlew setup..., switch-to-branch, gradlew build, gradlew runClient is easier than providing someone with a jar, especially if there could be multiple iterations of the fix.

None of the above requires that it go into the README, but you could potentially get a new contributor out of it if someone's willing to take the effort to build and run from source.

**Comment by Raycoms** [comment]
:shipit: it's something which is "good to know" to check if the installation went well

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/2166/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Review by marchermans — APPROVED** [review]

**Review by marchermans — APPROVED** [review]

**Pull request merged**
