### PR TITLE
Fix/colony crash10

### PR DESCRIPTION
**Pull request by Raycoms**
# Changes proposed in this pull request:
- Stops crashing if other worlds trigger on worldTick

Review please

### CODE REVIEW

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 54 issues
* ![MAJOR][MAJOR] 12 major
* ![MINOR][MINOR] 40 minor
* ![INFO][INFO] 2 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/11c9f09397b931d0a56c3680b31000b16487455a/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.231 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L43](https://github.com/Minecolonies/minecolonies/blob/11c9f09397b931d0a56c3680b31000b16487455a/src/main/java/com/minecolonies/coremod/colony/Colony.java#L43): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 43 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L43](https://github.com/Minecolonies/minecolonies/blob/11c9f09397b931d0a56c3680b31000b16487455a/src/main/java/com/minecolonies/coremod/colony/Colony.java#L43): class "Colony" has 82 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L641](https://github.com/Minecolonies/minecolonies/blob/11c9f09397b931d0a56c3680b31000b16487455a/src/main/java/com/minecolonies/coremod/colony/Colony.java#L641): Reduce the number of returns of this method 11, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L1163](https://github.com/Minecolonies/minecolonies/blob/11c9f09397b931d0a56c3680b31000b16487455a/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1163): Assign this magic number 20 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1164](https://github.com/Minecolonies/minecolonies/blob/11c9f09397b931d0a56c3680b31000b16487455a/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1164): Assign this magic number 60 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1276](https://github.com/Minecolonies/minecolonies/blob/11c9f09397b931d0a56c3680b31000b16487455a/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1276): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1278](https://github.com/Minecolonies/minecolonies/blob/11c9f09397b931d0a56c3680b31000b16487455a/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1278): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1280](https://github.com/Minecolonies/minecolonies/blob/11c9f09397b931d0a56c3680b31000b16487455a/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1280): Assign this magic number 128 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1401](https://github.com/Minecolonies/minecolonies/blob/11c9f09397b931d0a56c3680b31000b16487455a/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1401): Assign this magic number 0.5D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 54 issues
* ![MAJOR][MAJOR] 12 major
* ![MINOR][MINOR] 40 minor
* ![INFO][INFO] 2 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/452196a582bed18cb48e31ae77936aa3073f7727/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1.231 lines, which is greater than 1.000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L43](https://github.com/Minecolonies/minecolonies/blob/452196a582bed18cb48e31ae77936aa3073f7727/src/main/java/com/minecolonies/coremod/colony/Colony.java#L43): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 43 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L43](https://github.com/Minecolonies/minecolonies/blob/452196a582bed18cb48e31ae77936aa3073f7727/src/main/java/com/minecolonies/coremod/colony/Colony.java#L43): class "Colony" has 82 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L641](https://github.com/Minecolonies/minecolonies/blob/452196a582bed18cb48e31ae77936aa3073f7727/src/main/java/com/minecolonies/coremod/colony/Colony.java#L641): Reduce the number of returns of this method 11, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L1163](https://github.com/Minecolonies/minecolonies/blob/452196a582bed18cb48e31ae77936aa3073f7727/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1163): Assign this magic number 20 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1164](https://github.com/Minecolonies/minecolonies/blob/452196a582bed18cb48e31ae77936aa3073f7727/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1164): Assign this magic number 60 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1276](https://github.com/Minecolonies/minecolonies/blob/452196a582bed18cb48e31ae77936aa3073f7727/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1276): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1278](https://github.com/Minecolonies/minecolonies/blob/452196a582bed18cb48e31ae77936aa3073f7727/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1278): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1280](https://github.com/Minecolonies/minecolonies/blob/452196a582bed18cb48e31ae77936aa3073f7727/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1280): Assign this magic number 128 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1401](https://github.com/Minecolonies/minecolonies/blob/452196a582bed18cb48e31ae77936aa3073f7727/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1401): Assign this magic number 0.5D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 54 issues
* ![MAJOR][MAJOR] 12 major
* ![MINOR][MINOR] 40 minor
* ![INFO][INFO] 2 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Colony.java](https://github.com/Minecolonies/minecolonies/blob/452196a582bed18cb48e31ae77936aa3073f7727/src/main/java/com/minecolonies/coremod/colony/Colony.java): This file has 1,231 lines, which is greater than 1,000 authorized. Split it into smaller files. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS00104)
1. ![MAJOR][MAJOR] [Colony.java#L43](https://github.com/Minecolonies/minecolonies/blob/452196a582bed18cb48e31ae77936aa3073f7727/src/main/java/com/minecolonies/coremod/colony/Colony.java#L43): Split this class into smaller and more specialized ones to reduce its dependencies on other classes from 43 to the maximum authorized 30 or less. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1200)
1. ![MAJOR][MAJOR] [Colony.java#L43](https://github.com/Minecolonies/minecolonies/blob/452196a582bed18cb48e31ae77936aa3073f7727/src/main/java/com/minecolonies/coremod/colony/Colony.java#L43): class "Colony" has 82 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [Colony.java#L641](https://github.com/Minecolonies/minecolonies/blob/452196a582bed18cb48e31ae77936aa3073f7727/src/main/java/com/minecolonies/coremod/colony/Colony.java#L641): Reduce the number of returns of this method 11, down to the maximum allowed 6. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1142)
1. ![MAJOR][MAJOR] [Colony.java#L1163](https://github.com/Minecolonies/minecolonies/blob/452196a582bed18cb48e31ae77936aa3073f7727/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1163): Assign this magic number 20 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1164](https://github.com/Minecolonies/minecolonies/blob/452196a582bed18cb48e31ae77936aa3073f7727/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1164): Assign this magic number 60 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1276](https://github.com/Minecolonies/minecolonies/blob/452196a582bed18cb48e31ae77936aa3073f7727/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1276): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1278](https://github.com/Minecolonies/minecolonies/blob/452196a582bed18cb48e31ae77936aa3073f7727/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1278): Assign this magic number 16 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1280](https://github.com/Minecolonies/minecolonies/blob/452196a582bed18cb48e31ae77936aa3073f7727/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1280): Assign this magic number 128 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MAJOR][MAJOR] [Colony.java#L1401](https://github.com/Minecolonies/minecolonies/blob/452196a582bed18cb48e31ae77936aa3073f7727/src/main/java/com/minecolonies/coremod/colony/Colony.java#L1401): Assign this magic number 0.5D to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by marvin-bitterlich** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/998/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by marvin-bitterlich** [comment]
@Raycoms backport pls

**Pull request merged**
