### PR TITLE
Fixes the recipe

### LINKED ISSUE #1448: Warehouse does not exist
### Minecolonies version

version 1.12.1  file 0.8.3530 from curse 
Single player
### Expected behavior

- Put in the updated recipe to get warehouse.

### Actual behaviour

- No recipe exists but suggests there should be a recipe. It worked in the previous versions but doesn't now.

### Steps to reproduce the problem (missing recipe)

I tried all kinds of formulas, I even restarted the game a few times. It just gives me a blank space on the crafting bar.

### PR DESCRIPTION
**Pull request by MineShadow7**
Closes #1448 

# Changes proposed in this pull request:
- Warehouse recipe use chest instead of gold in centre.

Review please

### CODE REVIEW

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 31 issues
* ![MINOR][MINOR] 31 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/1739ec7dcfbe7130b093ab2f9873d0b13c5e658b/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/1739ec7dcfbe7130b093ab2f9873d0b13c5e658b/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/1739ec7dcfbe7130b093ab2f9873d0b13c5e658b/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/1739ec7dcfbe7130b093ab2f9873d0b13c5e658b/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/1739ec7dcfbe7130b093ab2f9873d0b13c5e658b/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions](https://github.com/Minecolonies/minecolonies/blob/1739ec7dcfbe7130b093ab2f9873d0b13c5e658b/src/main/java/com/minecolonies/coremod/colony/permissions): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [requestsystem](https://github.com/Minecolonies/minecolonies/blob/1739ec7dcfbe7130b093ab2f9873d0b13c5e658b/src/main/java/com/minecolonies/coremod/colony/requestsystem): Add a 'package-info.java' file to document the 'requestsystem' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [init](https://github.com/Minecolonies/minecolonies/blob/1739ec7dcfbe7130b093ab2f9873d0b13c5e658b/src/main/java/com/minecolonies/coremod/colony/requestsystem/init): Add a 'package-info.java' file to document the 'init' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [locations](https://github.com/Minecolonies/minecolonies/blob/1739ec7dcfbe7130b093ab2f9873d0b13c5e658b/src/main/java/com/minecolonies/coremod/colony/requestsystem/locations): Add a 'package-info.java' file to document the 'locations' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [requests](https://github.com/Minecolonies/minecolonies/blob/1739ec7dcfbe7130b093ab2f9873d0b13c5e658b/src/main/java/com/minecolonies/coremod/colony/requestsystem/requests): Add a 'package-info.java' file to document the 'requests' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1450/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by Asherslab** [comment]
Looks good :shipit:

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1450/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by marvin-bitterlich** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1450/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by marvin-bitterlich** [comment]
can we port this @MineShadow7

**Comment by Raycoms** [comment]
I think it is fixed in the other versions, was only a problem in 1.12

**Comment by MineShadow7** [comment]
Yes, port this.

**Pull request merged**
