### PR TITLE
Bug#778/level 5 builder requests tools of maximum grade

### LINKED ISSUE #778: Level 5 builder requests tools of maximum grade of .
### Minecolonies version

version 1.11-0.6.3282

### Expected behavior

- The builder requests the maximum available tool. (Diamond), or tells you you can get a supported mod that gives him other tools that he can now use.

### Actual behaviour

- The builder requests a tool of maximum grade of . (As you can see, he doesn't say what grade)

### Steps to reproduce the problem

1. Build a colony
2. Build and level the worker to level 5
3. Have its tool run out, and have none available in a warehouse.
4. Observe strange request.

### PR DESCRIPTION
**Pull request by xavierh**
Closes #778

# Changes proposed in this pull request:
- same implementation as the develop branch

Review please

### CODE REVIEW

**Comment by OrionDevelopment** [comment]
Please pull in the latest Develop changes. Build is failing because it is missing some parts from the gradle file.

**Comment by xavierh** [comment]
This is for version 1.11

**Comment by Raycoms** [comment]
:shipit: 

Forgot to merge that to 1.11

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/817/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by marchermans** [comment]
Yeah deleted the Comment already, also am merging that right now 👍

**Pull request merged**
