### PR TITLE
Removed logging from AbstractEntityAIInteract.java

### LINKED ISSUE #2976: ForgeHook not in sync with EfficientTool - Dump
As per the error, I'm reporting all the times this has been listed in the server logs. I've deduped the list and sorted it alphanumerically to make it easier to read (and stipped off the "ForgeHook not in sync with EfficientTool..." bit from each line).

```
Block{extrabees:hive} and 1xitem.pickaxeDiamond@1245
Block{forestry:beehives} and 1xitem.hatchetIron@217
Block{forestry:beehives} and 1xitem.pickaxeIron@101
Block{forestry:beehives} and 1xitem.pickaxeIron@207
Block{forestry:beehives} and 53xtile.torch@0
Block{forestry:beehives} and 6xtile.dirt@0
Block{ic2:resource} and 0xtile.air@0
Block{ic2:resource} and 10xtile.oreGold@0
Block{ic2:resource} and 14xitem.coal@0
Block{ic2:resource} and 14xtile.oreIron@0
Block{ic2:resource} and 18xitem.redstone@0
Block{ic2:resource} and 1xitem.emerald@0
Block{ic2:resource} and 1xitem.fish@0
Block{ic2:resource} and 1xitem.gem@7
Block{ic2:resource} and 1xitem.shovelIron@127
Block{ic2:resource} and 1xitem.shovelIron@128
Block{ic2:resource} and 1xitem.shovelIron@129
Block{ic2:resource} and 1xitem.shovelIron@130
Block{ic2:resource} and 1xtile.OreBlock@0
Block{ic2:resource} and 1xtile.oreGold@0
Block{ic2:resource} and 2xtile.actuallyadditions.block_misc@3
Block{ic2:resource} and 2xtile.nuclearcraft.ore@3
Block{ic2:resource} and 31xtile.stone@5
Block{ic2:resource} and 32xtile.dirt@0
Block{ic2:resource} and 35xtile.stonebrick@0
Block{ic2:resource} and 3xtile.oreGold@0
Block{ic2:resource} and 40xitem.coal@0
Block{ic2:resource} and 47xtile.torch@0
Block{ic2:resource} and 52xitem.coal@0
Block{ic2:resource} and 53xtile.dirt@0
Block{ic2:resource} and 59xtile.stonebrick@0
Block{ic2:resource} and 5xtile.stone@5
Block{ic2:resource} and 64xtile.dirt@0
Block{ic2:resource} and 64xtile.stonebrick@0
Block{ic2:resource} and 6xitem.coal@0
Block{ic2:resource} and 9xtile.rustic.slate@0
Block{magicbees:hiveblock} and 58xtile.stonebrick@0
Block{magicbees:hiveblock} and 64xtile.stairsWoodBirch@0
Block{nuclearcraft:ore} and 1xitem.natura.darkwood_pickaxe@10
Block{nuclearcraft:ore} and 1xitem.natura.darkwood_pickaxe@102
Block{nuclearcraft:ore} and 1xitem.natura.darkwood_pickaxe@113
Block{nuclearcraft:ore} and 1xitem.natura.darkwood_pickaxe@123
Block{nuclearcraft:ore} and 1xitem.natura.darkwood_pickaxe@20
Block{nuclearcraft:ore} and 1xitem.natura.darkwood_pickaxe@3
Block{nuclearcraft:ore} and 1xitem.natura.darkwood_pickaxe@32
Block{nuclearcraft:ore} and 1xitem.natura.darkwood_pickaxe@33
Block{nuclearcraft:ore} and 1xitem.natura.darkwood_pickaxe@39
Block{nuclearcraft:ore} and 1xitem.natura.darkwood_pickaxe@4
Block{nuclearcraft:ore} and 1xitem.natura.darkwood_pickaxe@76
Block{nuclearcraft:ore} and 1xitem.natura.darkwood_pickaxe@83
Block{nuclearcraft:ore} and 1xitem.natura.darkwood_pickaxe@86
Block{nuclearcraft:ore} and 1xitem.natura.netherquartz_pickaxe@63
Block{nuclearcraft:ore} and 1xitem.natura.netherquartz_pickaxe@67
Block{nuclearcraft:ore} and 1xitem.pickaxeStone@35
Block{nuclearcraft:ore} and 1xitem.pickaxeStone@36
Block{nuclearcraft:ore} and 1xitem.pickaxeStone@40
Block{nuclearcraft:ore} and 1xitem.pickaxeStone@41
Block{nuclearcraft:ore} and 1xitem.pickaxeStone@42
Block{nuclearcraft:ore} and 1xitem.pickaxeStone@43
Block{nuclearcraft:ore} and 1xitem.pickaxeStone@55
Block{nuclearcraft:ore} and 1xitem.pickaxeStone@56
Block{nuclearcraft:ore} and 1xitem.pickaxeStone@59
Block{nuclearcraft:ore} and 1xitem.pickaxeStone@60
Block{nuclearcraft:ore} and 1xitem.pickaxeStone@67
Block{nuclearcraft:ore} and 1xitem.pickaxeStone@68
Block{nuclearcraft:ore} and 1xitem.thermalfoundation.tool.silverPickaxe@27
Block{nuclearcraft:ore} and 1xitem.thermalfoundation.tool.silverPickaxe@32
Block{nuclearcraft:ore} and 1xitem.thermalfoundation.tool.silverPickaxe@33
Block{nuclearcraft:ore} and 1xitem.thermalfoundation.tool.silverPickaxe@34
Block{nuclearcraft:ore} and 1xitem.thermalfoundation.tool.silverPickaxe@35
Block{nuclearcraft:ore} and 1xitem.thermalfoundation.tool.silverPickaxe@36
Block{nuclearcraft:ore} and 1xitem.thermalfoundation.tool.silverPickaxe@46
Block{terraqueous:doodads} and 1xitem.hatchetDiamond@1258
Block{terraqueous:doodads} and 1xitem.hatchetIron@173
Block{terraqueous:doodads} and 1xitem.hatchetIron@8
Block{terraqueous:doodads} and 1xitem.hatchetStone@2
Block{terraqueous:doodads} and 1xitem.hatchetStone@81
Block{terraqueous:doodads} and 1xitem.hatchetStone@87
Block{terraqueous:doodads} and 1xitem.hatchetWood@0
Block{terraqueous:doodads} and 1xitem.hatchetWood@17
Block{terraqueous:doodads} and 1xitem.hatchetWood@3
Block{terraqueous:doodads} and 1xitem.thermalfoundation.tool.aluminumAxe@150
Block{terraqueous:doodads} and 1xitem.thermalfoundation.tool.aluminumAxe@31
Block{thermalfoundation:ore_fluid} and 1xitem.actuallyadditions.item_shovel_emerald@16
Block{thermalfoundation:ore_fluid} and 1xitem.actuallyadditions.item_shovel_emerald@17
Block{thermalfoundation:ore_fluid} and 1xitem.actuallyadditions.item_shovel_emerald@18
Block{thermalfoundation:ore_fluid} and 1xitem.actuallyadditions.item_shovel_emerald@19
Block{thermalfoundation:ore_fluid} and 1xitem.shovelIron@220
Block{thermalfoundation:ore_fluid} and 1xitem.shovelIron@221
Block{thermalfoundation:ore_fluid} and 1xitem.shovelIron@222
Block{thermalfoundation:ore} and 1xitem.natura.netherquartz_pickaxe@47
Block{thermalfoundation:ore} and 1xitem.natura.netherquartz_pickaxe@73
Block{thermalfoundation:ore} and 1xitem.natura.netherquartz_pickaxe@94
Block{thermalfoundation:ore} and 1xitem.pickaxeStone@0
Block{thermalfoundation:ore} and 1xitem.pickaxeStone@131
Block{thermalfoundation:ore} and 1xitem.pickaxeStone@19
Block{thermalfoundation:ore} and 1xitem.pickaxeStone@20
Block{thermalfoundation:ore} and 1xitem.pickaxeStone@21
Block{thermalfoundation:ore} and 1xitem.pickaxeStone@22
Block{thermalfoundation:ore} and 1xitem.pickaxeStone@74
Block{thermalfoundation:ore} and 1xitem.pickaxeStone@75
```

### PR DESCRIPTION
**Pull request by Elrol**
Closes #2976 

# Changes proposed in this pull request:
- Removes the logging of Forgehooks not being in sync with EfficientTools

Review please

### CODE REVIEW

**Comment by Asherslab** [comment]
LGTM looks good


[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/3555/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Comment by Asherslab** [comment]
hmm, on second thought, those imports man

**Review by Asherslab — DISMISSED** [review]
Please change the Imports back to previous

**Comment by Asherslab** [comment]
Looks much better LGTM

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/3555/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Comment by Elrol** [comment]
Eclipse will be Eclipse

**Comment by Raycoms** [comment]
:shipit: yeah, we got this in spamming for eternity and it never was any use besides spamming the log

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/3555/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Comment by Elrol** [comment]
glad to remove it lol.

**Pull request merged**
