### PR TITLE
Add a breeding setting to the apiary

### LINKED ISSUE #364: There is no turn off button for bee breeding in the apiary GUI
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- (x) I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:
- Structurize Version:
- Related Mods and their Versions:

## Expected behavior
Toggle for whether the beekeeper will ask for flowers to breed bees

## Actual behavior
 
There is no toggle to turn off bee breeding

## Steps to reproduce the issue

1. 
2. 
3. 

### Logs

- latest.log: 
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

### PR DESCRIPTION
**Pull request by chandler05**
Closes ldtteam/minecolonies-features#364
Closes #
Closes #

# Changes proposed in this pull request:
- Add a setting in the apiary/beekeeper hut that allows disabling or enabling bee breeding
-
-

Review please

### CODE REVIEW

**Comment by uecasm** [comment]
I'm curious why this was needed?  Don't they already stop breeding once you have enough bees to fill your hives?  (Or if not, perhaps that's a better fix?)

**Comment by chandler05** [comment]
Yes, the beekeeper does stop breeding whenever the hive is full. This setting is more for consistency than anything, as all other herder buildings have this setting included. With larger apiaries, it may also be nice to stop breeding the bees due to large population sizes.

**Comment by ravenbuilder934** [comment]
actually the swineherder doesn't, as there isn't really a point - there's nothing else the swineherder can collect besides meat. If there's no point here either, don't add it

**Comment by chandler05** [comment]
Swineherder does have the breeding setting, or at least according to the code it does.

**Comment by ravenbuilder934** [comment]
...apparently it does. I could've sworn it didn't...
never mind then!

**Review by Raycoms — APPROVED** [review]

**Review by someaddons — APPROVED** [review]
In the future please pm/talk in discord about the features you want to implement beforehand, the suggestion repo has quite a few which we do not want to implement, so that you'll not spend effort doing so and having it get rejected.

**Pull request merged**
