### PR TITLE
Remove duplicated method calls, unneccessary method calls, and attemp…

### PR DESCRIPTION
**Pull request by cltnschlosser**
…t to improve performance. Needs server testing.

Translation still appears to work fine when testing as a single player. If someone could test this on a server, preferably with multiple people that would be cool. I'm most worried about any code that calls sendPlayersMessage (notice plural), because I'm only creating one text component. but I believe this should be alright because it looks like vanilla code does the same thing, should help server performance slightly.

### CODE REVIEW

**Comment by cltnschlosser** [comment]
@Kostronor @Raycoms

**Comment by Raycoms** [comment]
the chatSpamFilter tests didn't like it, they're failing =D

**Comment by Raycoms** [comment]
If you get it to build I can send the jar to some players to test it.

**Comment by marvin-bitterlich** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/535/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by cltnschlosser** [comment]
@Raycoms Status on the server testing?

**Comment by Raycoms** [comment]
:shipit: I'd say. No one complained about it.

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/535/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Pull request merged**
