### PR TITLE
Removes fulfill and cancel from clipboard detail view

### LINKED ISSUE #5174: Clipboard has fulfill button
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: 

### Expected behavior

- 

### Actual behaviour

- 

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

### PR DESCRIPTION
**Pull request by PowerSchill**
Closes #5174

Signed-off-by: Mark E. Schill <Mark.Schill@cmschill.net>

Closes #
Closes #
Closes #

# Changes proposed in this pull request:
-
-
-

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
Cancel can stay

**Comment by PowerSchill** [comment]
Cancel is on the main window so I thought it was redundant to have it on the detail view as well but I can add it back.

**Comment by Raycoms** [comment]
ye

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/5180/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Pull request merged**
