### PR TITLE
Fix/flint n steel handling

### LINKED ISSUE #4148: Builder is only using Flint and Steel once, then requesting a unused one
### Minecolonies version

Version: 0.10.567-ALPHA

### Expected behavior

- When a building/upgrade requires the use of "Flint and Steel" he will use the one in its inventory, instead of requesting a completly new one.

### Actual behaviour

- Everytime he needs to use Flint and Steel he make a request for a unused one.
- This get's really annoying...

### Steps to reproduce the problem

1. Build or Upgrade a building which needs "Fire". In my Case "Medievalbirchalternative Citizen Hut" from 3 to 4
2. The builder use the Flint of Steel once
3. For the next upgrade he wants a unused one
4. ... Profit

### PR DESCRIPTION
**Pull request by Raycoms**
Closes #4148 

# Changes proposed in this pull request:
- Handle flint and steel like a real tool
-
-

Review please

### CODE REVIEW

**Comment by marvin-bitterlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/java/com/minecolonies/coremod/entity/ai/basic/AbstractEntityAIStructure.java  2
- src/api/java/com/minecolonies/api/colony/requestsystem/requestable/Tool.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Minecolonies/minecolonies/pullRequest?prid=4678897&bid=15652478)

**Comment by marchermans** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/4152/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Comment by Raycoms** [comment]
Don't merge yet, I was testing and ran into some issues

**Comment by marchermans** [comment]
Okey

**Pull request closed without merging**
