### PR TITLE
Adds completion notice (but not fireworks) to decorations

### LINKED ISSUE #4988: No chat message when decorations finish building
### Expected behavior

After the builder finishes building a decoration, there is fireworks and a chat message like there is for huts.

### Actual behaviour

No fireworks, no chat message. (There is a message when the builder starts building a decoration though.)

### Steps to reproduce the problem
1. Have the builder build a decoration
2. Wait for him to finish
4. ... Profit

### PR DESCRIPTION
**Pull request by PowerSchill**
Closes #4988
Closes #
Closes #

# Changes proposed in this pull request:
-
-
-

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/5114/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Comment by ravenbuilder934** [comment]
Why not fireworks?

**Comment by Raycoms** [comment]
So that people don't abuse it to trigger fireworks all the time.

**Comment by ravenbuilder934** [comment]
Oh, okay.

**Review by someaddons — APPROVED** [review]

**Pull request merged**
