### PR TITLE
move compatibility

### PR DESCRIPTION
**Pull request by marvin-bitterlich**
Move one package cleanly 
Review please @Minecolonies/maintainers

### CODE REVIEW

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 46 issues
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 36 minor
* ![INFO][INFO] 8 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [InventoryUtils.java#L26](https://github.com/Minecolonies/minecolonies/blob/30738d1d0a03d1f87fabb750df734d589f471651/src/main/java/com/minecolonies/coremod/util/InventoryUtils.java#L26): class "InventoryUtils" has 84 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [InventoryUtils.java#L1619](https://github.com/Minecolonies/minecolonies/blob/30738d1d0a03d1f87fabb750df734d589f471651/src/main/java/com/minecolonies/coremod/util/InventoryUtils.java#L1619): Assign this magic number 3 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/30738d1d0a03d1f87fabb750df734d589f471651/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/30738d1d0a03d1f87fabb750df734d589f471651/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/30738d1d0a03d1f87fabb750df734d589f471651/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/30738d1d0a03d1f87fabb750df734d589f471651/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/30738d1d0a03d1f87fabb750df734d589f471651/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions](https://github.com/Minecolonies/minecolonies/blob/30738d1d0a03d1f87fabb750df734d589f471651/src/main/java/com/minecolonies/coremod/colony/permissions): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [configuration](https://github.com/Minecolonies/minecolonies/blob/30738d1d0a03d1f87fabb750df734d589f471651/src/main/java/com/minecolonies/coremod/configuration): Add a 'package-info.java' file to document the 'configuration' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [creativetab](https://github.com/Minecolonies/minecolonies/blob/30738d1d0a03d1f87fabb750df734d589f471651/src/main/java/com/minecolonies/coremod/creativetab): Add a 'package-info.java' file to document the 'creativetab' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 46 issues
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 36 minor
* ![INFO][INFO] 8 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [InventoryUtils.java#L26](https://github.com/Minecolonies/minecolonies/blob/0545a95b12efc84d50954fd001e270e31d769af2/src/main/java/com/minecolonies/coremod/util/InventoryUtils.java#L26): class "InventoryUtils" has 84 methods, which is greater than the 35 authorized. Split it into smaller classes. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1448)
1. ![MAJOR][MAJOR] [InventoryUtils.java#L1619](https://github.com/Minecolonies/minecolonies/blob/0545a95b12efc84d50954fd001e270e31d769af2/src/main/java/com/minecolonies/coremod/util/InventoryUtils.java#L1619): Assign this magic number 3 to a well-named constant, and use the constant instead. [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS109)
1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/0545a95b12efc84d50954fd001e270e31d769af2/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/0545a95b12efc84d50954fd001e270e31d769af2/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/0545a95b12efc84d50954fd001e270e31d769af2/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/0545a95b12efc84d50954fd001e270e31d769af2/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/0545a95b12efc84d50954fd001e270e31d769af2/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions](https://github.com/Minecolonies/minecolonies/blob/0545a95b12efc84d50954fd001e270e31d769af2/src/main/java/com/minecolonies/coremod/colony/permissions): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [configuration](https://github.com/Minecolonies/minecolonies/blob/0545a95b12efc84d50954fd001e270e31d769af2/src/main/java/com/minecolonies/coremod/configuration): Add a 'package-info.java' file to document the 'configuration' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [creativetab](https://github.com/Minecolonies/minecolonies/blob/0545a95b12efc84d50954fd001e270e31d769af2/src/main/java/com/minecolonies/coremod/creativetab): Add a 'package-info.java' file to document the 'creativetab' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by xavierh** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1065/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Comment by Raycoms** [comment]
:shipit: 

[Approved with PullApprove](https://pullapprove.com/Minecolonies/minecolonies/pull-request/1065/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=Minecolonies/minecolonies)

**Review by marchermans — DISMISSED** [review]
It is good to have the compatibility core classes in the API, yet i donnot think that we would need to put the acual core implementations of the compatibility stuff inside that package.

**Comment by marvin-bitterlich** [comment]
@OrionDevelopment thats for another pr imo

we can move it later but your pr has it the same

**Comment by marchermans** [comment]
Okey then lets Keep it this way.
That way People who want to use the API have an example directly there.

**Pull request merged**
