### PR TITLE
Blah/1.16

### PR DESCRIPTION
**Pull request by MrMeender**
Closes #
Closes #
Closes #

# Changes proposed in this pull request:
- More social interactions between colonists
- Families: they live in the same house and are the only ones to mourne the death of a colonist instead of blocking the whole colony
- Aging cicle for colonists: 0-2 days old newborn (does nothing and forces the mother to do nothing), 3-12 toddler (is Pupil), 13-19 teen(studies at library or trains as guard), 20-30 young adult (works), 31-75 adult (works), 76+ senior (wanders around) and dies at about 80 days (Deaths of old age shouldn't cause colonists to be too sad)

Review please

### CODE REVIEW

**Comment by Raycoms** [comment]
That's not how you create feature suggestions. Try again

**Comment by MrMeender** [comment]
I didn't understand how to create one

**Comment by ShadowProtocol** [comment]
Go to the issues in the minecolonies-features repository (github.com/ldtteam/minecolonies-features) and create a new issue using the button at the top right. Issues and Pull-Requests are very different!
Here's a shortcut: https://github.com/ldtteam/minecolonies-features/issues/new/choose

**Comment by MrMeender** [comment]
ok thanks

**Pull request closed without merging**
