### PR TITLE
Replace furnace building type with module

### PR DESCRIPTION
**Pull request by Raycoms**
# Changes proposed in this pull request:
- This is one of the last building modules. No more extends AbstractBuildingFurnace but instead a proper module
-
-

Review please

### CODE REVIEW

**Review by someaddons — APPROVED** [review]

**Comment by uecasm** [comment]
Shouldn't this be merged into the `AbstractCraftingBuildingModule.Smelting` module rather than being a separate one?

Is there ever any reason to have a building be able to use furnaces but not know furnace recipes, or vice versa?  (You can still disable teaching furnace recipes in the building's smelting module if you like.)

Of the buildings in this PR, it looks like the only one that lacks a smelting module is the Baker ... which might possibly be why the baker has been having trouble turning dough into bread?  (Although their crafting module does contain the recipe for it...)

**Comment by Raycoms** [comment]
> Shouldn't this be merged into the `AbstractCraftingBuildingModule.Smelting` module rather than being a separate one?
> 
> Is there ever any reason to have a building be able to use furnaces but not know furnace recipes, or vice versa? (You can still disable teaching furnace recipes in the building's smelting module if you like.)
> 
> Of the buildings in this PR, it looks like the only one that lacks a smelting module is the Baker ... which might possibly be why the baker has been having trouble turning dough into bread? (Although their crafting module does contain the recipe for it...)

Not necessarily, technically, the cook AI uses it, without doing recipes.

But yes, that might be the problem of the Baker

**Comment by uecasm** [comment]
The cook does have a smelting module.

**Comment by Raycoms** [comment]
> The cook does have a smelting module.

But that one is only used for requests, not for regular cooking, right?

**Comment by uecasm** [comment]
The crafting modules themselves don't really **do** anything, they're just storage for recipes and helpers for JEI integration, and related recipe queries.  It's always the AI that drives actually doing work one way or the other.

The point being that the cook still has one so it doesn't break the pattern where the two modules could be merged.  The only one that does break the pattern is the baker, which might itself be a bug.

**Comment by Raycoms** [comment]
> The crafting modules themselves don't really **do** anything, they're just storage for recipes and helpers for JEI integration, and related recipe queries. It's always the AI that drives actually doing work one way or the other.
> 
> The point being that the cook still has one so it doesn't break the pattern where the two modules could be merged. The only one that does break the pattern is the baker, which might itself be a bug.

Yeah, the baker is probably the one where it's a bug because it's actually a request smelter too. 
But I don't see why we have to mix them, not necessarily they have to be together and having modules be pretty self contained is a big advantage in terms of maintenance.

**Comment by uecasm** [comment]
They don't _have_ to be mixed, but it does seem kinda silly for them to be separate if, as we've determined, when you want one you always want the other too.  And it just makes sense to me for the furnace crafting module to also contain the list of furnaces that can be crafted at.

Imagine adding some third type of crafting that also needed work blocks (e.g. something like Domum but where the schem did have to contain an Architect's Cutter, or some other mod integration, or even something like the concrete mixer's water mixing) -- it makes sense to have one module that wraps all of that up into a neat package, including both the list of work blocks and the recipes that can be made using them, and helpers for the building and AI to actually use them.

**Pull request merged**
