### PR TITLE
Goalselector/worker AI removal fix

### PR DESCRIPTION
**Pull request by someaddons**
# Changes proposed in this pull request:
Fixes an issues where sometimes the workerAI was not correctly removed when a different goal was active, like eating since we only accessed the currently running goals.

Adds a faster, custom goalselector which keeps the vanilla functionality but runs a lot faster. 
Testing against the vanilla one (system.nano, averaging 100k ticks) with vanilla entities showed a gain of 3-4 times less tick time used, which includes the execution time of the actual goals. Now when adding that non-running tasks are only checked every 4 ticks, like 1.12 vanilla did the total tick time goes down to about 20% of vanilla. 
In an in-precise test(running the custom one's tick and then the vanilla one's tick on the same goals) the selector itself ran about 5-6 times faster.
Testing with /forge tps and spawning about 150 sheeps reduced the mean tick time from 37ms to 25ms.

Originally this custom goalselector was aimed for a small performance increasing mod, but since minecolonies relies on entities a lot I think it is beneficial for us aswell.

Might be good to let a few ppl test this, to make sure our entities work as before incase I missed anything.

Review please

### CODE REVIEW

**Comment by reggaemuffin** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/api/java/com/minecolonies/api/entity/CustomGoalSelector.java  15
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/minecolonies/minecolonies/pullRequest?prid=4615328&bid=15479915)

**Comment by Olfi01** [comment]
Does this perhaps fix #3106 ?

**Comment by someaddons** [comment]
no this keeps the same priorities as vanilla, gotta check why the eating AI doesnt take prio

**Comment by marchermans** [comment]
Approved 

[Approved with PullApprove](https://pullapprove.com/ldtteam/minecolonies/pull-request/4120/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ldtteam/minecolonies)

**Review by Raycoms — APPROVED** [review]

**Comment by marvin-bitterlich** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/api/java/com/minecolonies/api/entity/CustomGoalSelector.java  15
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Minecolonies/minecolonies/pullRequest?prid=4615328&bid=15479915)

**Pull request merged**
