### PR TITLE
Added and corrected text for translation into Portuguese (Brazil)

### PR DESCRIPTION
**Pull request by scriptsengineer**
# Changes proposed in this pull request:
-Added and corrected text for translation into Portuguese (Brazil)
Review please

### CODE REVIEW

**Comment by MinecoloniesSonar** [comment]
SonarQube analysis reported 26 issues
* ![MINOR][MINOR] 26 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [blocks](https://github.com/Minecolonies/minecolonies/blob/caf671f4d7e300a2c3b2b4ca43a62d2f78f1a7e9/src/main/java/com/minecolonies/coremod/blocks): Add a 'package-info.java' file to document the 'blocks' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [gui](https://github.com/Minecolonies/minecolonies/blob/caf671f4d7e300a2c3b2b4ca43a62d2f78f1a7e9/src/main/java/com/minecolonies/coremod/client/gui): Add a 'package-info.java' file to document the 'gui' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [render](https://github.com/Minecolonies/minecolonies/blob/caf671f4d7e300a2c3b2b4ca43a62d2f78f1a7e9/src/main/java/com/minecolonies/coremod/client/render): Add a 'package-info.java' file to document the 'render' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [colony](https://github.com/Minecolonies/minecolonies/blob/caf671f4d7e300a2c3b2b4ca43a62d2f78f1a7e9/src/main/java/com/minecolonies/coremod/colony): Add a 'package-info.java' file to document the 'colony' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [buildings](https://github.com/Minecolonies/minecolonies/blob/caf671f4d7e300a2c3b2b4ca43a62d2f78f1a7e9/src/main/java/com/minecolonies/coremod/colony/buildings): Add a 'package-info.java' file to document the 'buildings' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [permissions](https://github.com/Minecolonies/minecolonies/blob/caf671f4d7e300a2c3b2b4ca43a62d2f78f1a7e9/src/main/java/com/minecolonies/coremod/colony/permissions): Add a 'package-info.java' file to document the 'permissions' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [creativetab](https://github.com/Minecolonies/minecolonies/blob/caf671f4d7e300a2c3b2b4ca43a62d2f78f1a7e9/src/main/java/com/minecolonies/coremod/creativetab): Add a 'package-info.java' file to document the 'creativetab' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [entity](https://github.com/Minecolonies/minecolonies/blob/caf671f4d7e300a2c3b2b4ca43a62d2f78f1a7e9/src/main/java/com/minecolonies/coremod/entity): Add a 'package-info.java' file to document the 'entity' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [basic](https://github.com/Minecolonies/minecolonies/blob/caf671f4d7e300a2c3b2b4ca43a62d2f78f1a7e9/src/main/java/com/minecolonies/coremod/entity/ai/basic): Add a 'package-info.java' file to document the 'basic' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)
1. ![MINOR][MINOR] [baker](https://github.com/Minecolonies/minecolonies/blob/caf671f4d7e300a2c3b2b4ca43a62d2f78f1a7e9/src/main/java/com/minecolonies/coremod/entity/ai/citizen/baker): Add a 'package-info.java' file to document the 'baker' package [rule](https://sonar.minecolonies.com/coding_rules#rule_key=squid%3AS1228)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Raycoms** [comment]
Hello Rafael:
Thanks for the effort.
If you kindly send me your email I can invite you to our translate tool which would facilitate this integration essentially.
(Qualquer email dá)

**Comment by scriptsengineer** [comment]
Hello Raycoms, I'm proud of the answer because I became a fan of this modification, I admit that this translation was simple and in fact I just wanted to test github, because I'm excited to help with the project. My email is rafaelmoraiscorrea@gmail.com.

**Comment by marchermans** [comment]
Since we are using an external system for this, i am closing this.

**Pull request closed without merging**
